### ISSUE TITLE
Update

### ISSUE THREAD

**Issue by mayokingcomics** [opendns/autotask-php#1]
I am trying to update with this. Are there any examples? I do not get a response from autotask.

**Comment by zbuttram** [comment]
@reynolek Just ran into this issue as well. Would you be open to accepting a PR adding this fix to the update method?

**Comment by reynolek** [comment]
I am always open to PRs if you think you have a fix -- with a caveat of depending on what it does I may or may not merge it unless it fits in with the goal of the project.
