### ISSUE TITLE
Reoccurring Sales

### ISSUE THREAD

**Issue by thekingster** [opendns/autotask-php#100]
Hi All

I am trying to find where the data is for reoccurring sales and wondered if anyone knew? I want to find how much each resource sells per month on reoccurring

For example for Feb, I have billingitem.itemdate > 01/02/2018 but I cannot see where I get the owner of that billingitem? I have looked in contracts and cannot find it.

Any ideas please?

Thanks

Dave

**Comment by SirPoot-** [comment]
@thekingster did you look at the 'About Recurring Service Contract Entity Relationships' in the API documentation? It is on page 79 on API version 1.5.11. This may give you some guidance.

> A Recurring Service type contract can have one or more associated Services (ContractService) and/or Service Bundles (ContractServiceBundle). The Web Services API presents four additional entities related to ContractService or ContractServiceBundle entities: ContractServiceAdjustment, ContractServiceBundleAdjustment, ContractServiceUnit, and ContractServiceBundleUnit.

When we are looking for this information - we query the contract, generate a spread based on the contract, and use the spread to calculate the deferred costs which gives is the amount they brought in for that month. This also helps with deferred revenue.

---

After re-reading your question. On the bill item, you can see the object (Project, Contract, Task, Ticket, etc) that bill is referencing. With that information, you can query that object to additional information like the creator. I often have to chain queries to get data like this.

**Comment by SirPoot-** [comment]
@thekingster can you update #94 since you as requesting additional assistance?

**Comment by thekingster** [comment]
busy today, but will look into by end of the week. Thank you
