### ISSUE TITLE
Select field data to variables?

### ISSUE THREAD

**Issue by ts91nz** [opendns/autotask-php#102]
Hi Team, thank you for your work on this API. I would like to select a field, such as ticket number, from an API query and add the result to a variable in PHP website. I am unsure how to do this, can you please advise? I am creating a custom web portal and wish to display ticket information per customer. At the moment all I get is a full dump of information, I only want particular fields. Thank you. 

![image](https://user-images.githubusercontent.com/37311639/37308739-cf2486fe-26a3-11e8-89c8-4cd7eacc5a4b.png)

![image](https://user-images.githubusercontent.com/37311639/37308766-de7abbaa-26a3-11e8-81ad-20ba933ec661.png)

**Comment by reynolek** [comment]
When making the request, there is no direct way to say "Only return this field". The QueryResponse object you are getting back contains everything that your query returned.

```php
$result = $client->query($query);
foreach ($result->queryResult->EntityResults->Entity as $ticket) {
    print_r($ticket);
    var_dump($ticket->TicketNumber);
}
```

The objects provided back via the Autotask Client are PHP Objects, so you have to access them with `->` -- they work slightly differently than Associative Arrays.
