### ISSUE TITLE
Several variables declared twice in AutotaskObjects in v0.2.0

### ISSUE THREAD

**Issue by reynolek** [opendns/autotask-php#107]
Will update this list as I find them.

InstalledProduct::$ProductID
AllocationCode::$UnitCost
AllocationCode::$UnitPrice
ContractCost::$CostType
Invoice::$InvoiceDateTime
InvoiceTemplate::$DateFormat

ContractServiceUnit missing closing `}`

**Comment by SirPoot-** [comment]
Sorry about that @reynolek

**Comment by reynolek** [comment]
Fixed in https://github.com/opendns/autotask-php/pull/108 and deployed as v0.2.1

**Comment by reynolek** [comment]
Not a big deal -- I just happened to find one of them due to our internal unit tests. Pretty hard to spot overall.
