### ISSUE TITLE
Every customer

### ISSUE THREAD

**Issue by whatsnow** [opendns/autotask-php#11]
Hi,

I'm using this autotask-php scripts and its work fine but i want to know is there possble way to get every account with the api ?

Kind regards,

David

**Comment by Egahras** [comment]
Yes ans no. The apiis limited toba specific amount of results. I think it was something around 200?... So you Need to request all accounts step by step. Request them ordered by id. Than a second request with the last returned id+1 ans up... And so on ans so on toll you get an empty result.

**Comment by Egahras** [comment]
Wow sorry for the typing mistakes... First time with my windowsphone... Fast typing is terrible on This....

**Comment by sulfurcode** [comment]
The API returns a maximum of 500 results per request. To get more you make additional requests looking for an id greater than the last one in the previous results. if there are less than 500 results in a request then there's no need to make subsequent requests.

**Comment by reynolek** [comment]
Exactly what they said, you have to pull them down in batches. The efficient thing to do (depending on what you are trying to do anyway) is to pull in batches and process each batch as you pull them rather than getting them all first and then processing.

**Comment by reynolek** [comment]
Closing this issue, let us know if you need any other help.
