### ISSUE TITLE
Supporting TLS 1.2

### ISSUE THREAD

**Issue by cadavis22** [opendns/autotask-php#112]
After the TLS 1.2 update by Autotask I started getting the following error:

PHP Fatal error:  Uncaught SoapFault exception: [WSDL] SOAP-ERROR: Parsing WSDL: Couldn't load from 'https://webservices.autotask.net/atservices/1.5/atws.wsdl' : failed to load external entity "https://webservices.autotask.net/atservices/1.5/atws.wsdl"
 
You need to force the SOAP client to use TLS.  Below is the working code:

$username = '';
$password = '';
$authWsdl = 'https://webservices.autotask.net/atservices/1.5/atws.wsdl';

$arrContextOptions=array("ssl"=>array( "verify_peer"=>false, "verify_peer_name"=>false,'crypto_method' => STREAM_CRYPTO_METHOD_TLS_CLIENT));

$opts = array('soap_version'=>'SOAP_1_2',
				'trace' => 1,
				'stream_context' => stream_context_create($arrContextOptions),
			);
$client = new ATWS\Client($authWsdl, $opts);
$zoneInfo = $client->getZoneInfo($username);
// Begins procedure
$authOpts = array(
	'login' => $username,
	'password' => $password,
	'soap_version'=>'SOAP_1_2',
	'trace' => 1,  // Allows us to debug by getting the XML requests sent
	'stream_context' => stream_context_create($arrContextOptions),
);
$wsdl = str_replace('.asmx', '.wsdl', $zoneInfo->getZoneInfoResult->URL);
$client = new ATWS\Client($wsdl, $authOpts);

**Comment by SirPoot-** [comment]
@cadavis22 have you taken a look at #98?

What are you using for your SSL library? If its OpenSSL make sure it is higher than 1.0.1. Also, in that issue, I explain how to force a TLS 1.2 connection. Looks like you may need to swap out your crypto_method.

**Comment by SirPoot-** [comment]
@cadavis22 any update?

**Comment by cadavis22** [comment]
No updated needed, I have it working.  I was posting a solution not an
issue.

**Comment by SirPoot-** [comment]
Okay. Thanks. Can you close this issue?
