### ISSUE TITLE
Create a ticket

### ISSUE THREAD

**Issue by mcl12345** [opendns/autotask-php#113]
Hi,

**I have an error, I need a Picklist value for the field QueueID**

```
<?php
// This is an example script for creating a ticket in Autotask
// via the autotask-php client by OpenDNS

require_once __DIR__ . '/src/autoload.php';

// Edit these variables to get this example to work for you
$username = "*******************";
$password = "*******************";

$ticket = new ATWS\AutotaskObjects\Ticket();
// Set required fields
$ticket->id= 0;     // Set to 0 for create, or a ticket id for update
$ticket->AccountID = 0;
$ticket->DueDateTime = '2015-12-17';
$ticket->Title = 'Test Ticket';
$ticket->Status = 1;
$ticket->Priority = 1;

// Set extra, but helpful, fields
$ticket->QueueID = "Level I Support";
//$ticket->AllocationCodeID = ;
//$ticket->TicketType = ;
//$ticket->IssueType = ;
//$ticket->SubIssueType = ;

// End Edit Region

$authWsdl = 'https://webservices.autotask.net/atservices/1.5/atws.wsdl';
$opts = array('trace' => 1);
$client = new ATWS\Client($authWsdl, $opts);
$zoneInfo = $client->getZoneInfo($username);

$authOpts = array(
    'login' => $username,
    'password' => $password,
    'trace' => 1,   // Allows us to debug by getting the XML requests sent
);
$wsdl = str_replace('.asmx', '.wsdl', $zoneInfo->getZoneInfoResult->URL);
$client = new ATWS\Client($wsdl, $authOpts);

print_r($client->create($ticket));
?>
```

**The error :**
ATWS\AutotaskObjects\CreateResponse Object ( [createResult] => ATWS\AutotaskObjects\ATWSResponse Object ( [EntityResults] => ATWS\AutotaskObjects\ArrayOfEntity Object ( [Entity] => ) [EntityResultType] => ticket [EntityReturnInfoResults] => ATWS\AutotaskObjects\ArrayOfEntityReturnInfo Object ( [EntityReturnInfo] => [Fields] => [UserDefinedFields] => ) [Errors] => ATWS\AutotaskObjects\ArrayOfATWSError Object ( [ATWSError] => ATWS\AutotaskObjects\ATWSError Object ( [Message] => **Picklist value [Level I Support] does not exist for QueueID.** ; on record number [1]. ) [Fields] => [UserDefinedFields] => ) [ReturnCode] => -1 ) )

**Comment by SirPoot-** [comment]
@mcl12345 it would be great if you responded to your existing issue #111. We are more than happy to help and we do not want lingering issues.

You can systematically get these values by FieldPickListValue or within the UI by reviewing the drop <ul> code for the field.

Keep in mind, almost everything is referred by id.
