### ISSUE TITLE
Required IntegrationCode tracking

### ISSUE THREAD

**Issue by tekoyaki** [opendns/autotask-php#118]
Autotask just required this. It's nowhere in the docs, but attached is the instructions we got.
[AutotaskIntegrationTrackingIdentifier.pdf](https://github.com/opendns/autotask-php/files/2199563/AutotaskIntegrationTrackingIdentifier.pdf)

Our current implementation (not yet confirmed by Autotask):

```
$client = new ATWS\Client($wsdl, $options);

// Required tracking
// Create and assign Soap Header.
$header = new SOAPHeader('http://autotask.net/ATWS/v1_5/', 'AutotaskIntegrations', [
  'IntegrationCode' => AUTOTASK_INTEGRATION_CODE
]);
$client->__setSoapHeaders($header);
```

**Comment by SirPoot-** [comment]
I am not signed up for Autotask's 'Integration Developers' and do not have this requirement. I am not sure if your code is correct. You could always review the last request, $client->__getLastRequest() and see if it is set.

**Comment by tekoyaki** [comment]
It does seem to work in testing, here's the header output for anyone interested:

```
    <SOAP-ENV:Header>
        <ns1:AutotaskIntegrations>
            <ns1:IntegrationCode>xxx</ns1:IntegrationCode>
        </ns1:AutotaskIntegrations>
    </SOAP-ENV:Header>
```

And ns1 declaration: `xmlns:ns1="http://autotask.net/ATWS/v1_5/"`

**Comment by reynolek** [comment]
#121 addresses this and gives an easy client call to handle this situation. Not required to use, but should be easier than doing it by hand.

**Comment by reynolek** [comment]
v0.2.3 has been released with this functionality.
