### ISSUE TITLE
Need Information about contact groups

### ISSUE THREAD

**Issue by harshek** [opendns/autotask-php#119]
I checked the API but unable to find out a endpoint from where I can get contact groups.
Endpoint through which I can get contacts which are assigned to the group.
Also the groups assigned to a particular contact.

TIA.

**Comment by SirPoot-** [comment]
This is not accessible via the API.

**Comment by SirPoot-** [comment]
@harshek if there is nothing else, can you close this issue?

**Comment by SirPoot-** [comment]
@reynolek Can we close this issue? It is not possible via the API and @harshek has had no response.

**Comment by harshek** [comment]
@sirpoot, actually we are looking for this API if you can provide solution for it, we will be very much thankful.
Or guide us how we can update the API to fetch those details. we will try that too.

**Comment by JoshNW** [comment]
@harshek The contact group area has not been exposed by Autotask. 

If you would like to modify this area of autotask via API in the future, Autotask would have to update their API. This typically occurs during major releases. The product support road map and ideas page is a great resources to see what changes are planned at this time. 

Please review the Autotask Core API documentation for details regarding what is s available via API [https://ww14.autotask.net/help/Content/LinkedDOCUMENTS/WSAPI/T_WebServicesAPIv1_5.pdf](url)

**Comment by SirPoot-** [comment]
@JoshNW close request.

**Comment by SirPoot-** [comment]
@harshek The ContactGroup entity will be added to the 2018.3 release which is scheduled mid January 2018

**Comment by harshek** [comment]
I was researching on the Autotask again and found contactgroup API is in v1.6 can you please help how we can get the result for contactgroup api using the code?

TIA

**Comment by harshek** [comment]
@JoshNW Is it possible that with your existing 1.5 code we can do some alteration and execute 1.6 code to handle those API too.

Also how to use 1.6 can you help in that, it will be very much appreciable.

**Comment by SirPoot-** [comment]
@harshek @JoshNW I created a pull request #137 that explains how to use the API version 1.6 with the most recent build. You can review that until it gets pushed in.
