### ISSUE TITLE
Adding content to UDF when creating a ticket

### ISSUE THREAD

**Issue by orangevan** [opendns/autotask-php#12]
I am having troubles adding content to a UDF when creating (or updating) a ticket.
I've got the process to retreive the data, but am having issues with the code.  
Is this supported by the API at this time, do you have any example PHP on how to do this?

**Comment by reynolek** [comment]
I believe this should be supported fine. At OpenDNS, we have a second system that pushes to autotask that is written in python, so I do not immediately have an example to copy/paste in PHP.

It looks like there are a few things that need to be done when modifying UDFs:

1. Ensure you are creating an `ArrayOfUserDefinedField` object (we will call it `AoUDF` for now)
2. Create a normal PHP `array` of all of the `UserDefinedField` objects you want to push up (we will call this array `udfs`)
3. Set `AoUDF->UserDefinedField = udfs`

Below I have written this out into PHP, but without having tried it.
```php
$AoUDF = new \ATWS\AutotaskObjects\ArrayOfUserDefinedField();
$udfs = array();
$exampleUDF = new \ATWS\AutotaskObjects\UserDefinedField();
$exampleUDF->Name = 'Example';
$exampleUDF->Value = 'Sweet Example Value';

$udfs[] = $exampleUDF;

$AoUDF->UserDefinedField = $udfs;
```

Hope this helps.

**Comment by orangevan** [comment]
That worked!  Thanks!  Much appreciated, I couldn't figure it out!
Final code section for new ticket looks like this for anyone's reference who is trying to do the same or similar.
```php
    $ticket = new ATWS\AutotaskObjects\Ticket();
    $ticket->Title = $subject;
    $ticket->Description = $description; 
    $ticket->AccountID = $actid; //looked up earlier in code by email
    $ticket->ContactID = $cntcid; //looked up earlier in code by email
    $ticket->DueDateTime = date('Y-m-d\TH:i:s',strtotime('+7 day'));//->modify('+7 day');; //required, setting due to one week from submission
    $ticket->id = 0;  //required
    $ticket->Priority = 3; //normal
    $ticket->Status = 1; //new
    $ticket->QueueID = number;
    $ticket->Source = number;
    $ticket->IssueType = number;
    $ticket->SubIssueType = number; 

      $AoUDF = new \ATWS\AutotaskObjects\ArrayOfUserDefinedField();
      $udfs = array();
      $exampleUDF = new \ATWS\AutotaskObjects\UserDefinedField();
      $exampleUDF->Name = 'NameofUDF';
      $exampleUDF->Value = '123456';
      $udfs[] = $exampleUDF;
      $AoUDF->UserDefinedField = $udfs;

    $ticket->UserDefinedFields = $AoUDF; //adds UDF values to ticket 

    $newticketresponse = $client->create($ticket); //creates ticket
```

**Comment by reynolek** [comment]
Cool, glad you were able to get up and running!
