### ISSUE TITLE
Possible XML Bug - Query with QueryConditions as the only children

### ISSUE THREAD

**Issue by ryleeferguson** [opendns/autotask-php#120]
Just ran into a minor bug with the QueryConditions.
If, for example, you wish to query on multiple fields using only QueryConditions (with Fields/Expressions within), you get a null return (no errors though)

E.g.
```
$query = new ATWS\AutotaskObjects\Query('Ticket');
$condition = new ATWS\AutotaskObjects\QueryCondition('OR');

$f1 = new ATWS\AutotaskObjects\QueryField('id');
$f1->addExpression('Equals',20852);
$f2 = new ATWS\AutotaskObjects\QueryField('id');
$f2->addExpression('Equals',20853);

$condition->addField($f1);
$condition->addField($f2);

$query->addCondition($condition);
$qr = $ATClient->query($query);
```

To get around this, I had to add a field to the query
```
$query = new ATWS\AutotaskObjects\Query('Ticket');
$condition = new ATWS\AutotaskObjects\QueryCondition('OR');

$f1 = new ATWS\AutotaskObjects\QueryField('id');
$f1->addExpression('Equals',20852);
$f2 = new ATWS\AutotaskObjects\QueryField('id');
$f2->addExpression('Equals',20853);

$query->addField($f1); //Instead of all children as QueryConditions, add the first as a Field
$condition->addField($f2);

$query->addCondition($condition);
$qr = $ATClient->query($query);
```

**Comment by JoshNW** [comment]
I believe that is working as designed. The query condition tag impacts the group relative to another group, not the items within it. 

I have also struggled with this one and had to do some silly things to get work through it. Here is an example: 
//Create Wrapping condition to House all Owners (WIll be treated as 'And' With the next condition))
$wrappingCondition = new ATWS\AutotaskObjects\QueryCondition('');

//Adds Resource filter
$Condition1 = new ATWS\AutotaskObjects\QueryCondition('Or');
$Owner1 = new ATWS\AutotaskObjects\QueryField('OwnerResourceID');
$Owner1->addExpression('Equals', '29682955');
$Condition1->addField($Owner1);
$wrappingCondition->addCondition($Condition1);

//Adds Resource filter
$Condition2 = new ATWS\AutotaskObjects\QueryCondition('Or');
$Owner2 = new ATWS\AutotaskObjects\QueryField('OwnerResourceID');
$Owner2->addExpression('Equals', '29682902'); 
$Condition2->addField($Owner2);
$wrappingCondition->addCondition($Condition2);

//Adds Resource filter
$Condition3 = new ATWS\AutotaskObjects\QueryCondition('Or');
$Owner3 = new ATWS\AutotaskObjects\QueryField('OwnerResourceID');
$Owner3->addExpression('Equals', '29682900'); 
$Condition3->addField($Owner3);
$wrappingCondition->addCondition($Condition3);

//Adds Resource filter
$Condition4 = new ATWS\AutotaskObjects\QueryCondition('Or');
$Owner4 = new ATWS\AutotaskObjects\QueryField('OwnerResourceID');
$Owner4->addExpression('Equals', '29682898'); 
$Condition4->addField($Owner4);
$wrappingCondition->addCondition($Condition4);

//Adds Resource filter
$Condition5 = new ATWS\AutotaskObjects\QueryCondition('Or');
$Owner5 = new ATWS\AutotaskObjects\QueryField('OwnerResourceID');
$Owner5->addExpression('Equals', '29682899'); 
$Condition5->addField($Owner5);
$wrappingCondition->addCondition($Condition5);

$query->addCondition($wrappingCondition);

$OppStatus = new ATWS\AutotaskObjects\QueryField('Status');
$OppStatus->addExpression('Lessthan', '2');
$query->addField($OppStatus);

**Comment by SirPoot-** [comment]
@ryleeferguson need any other assistance on this issue?
