### ISSUE TITLE
PHP Error

### ISSUE THREAD

**Issue by kkiotes** [opendns/autotask-php#122]
Hello,

maybe i just have a "thinking" error but i get the following error:
[:error] [pid xxxxx] [client x.x.x.x] PHP Fatal error:  require_once(): Failed opening required '/../../../src//SoapClient.php' (include_path='.:/usr/share/php') in /../../../src/autoload.php on line 9

I think that the problem is the double "//".

Maybe you can provide me some help :)

best regards

**Comment by SirPoot-** [comment]
Looks like you are trying to manually import it. I would make sure you are referencing the proper autoload.php file and location. There is no SoapClient.php in this repo. The only reference to SoapClient is the to the native SoapClient. You could try deleting everything and attempting again.

If you could use composer, I would recommend that.

**Comment by kkiotes** [comment]
Good Morning,

thank you for your response.

Thats what i did actually.
But i will give it another shot!

Mit freundlichen Grüssen / Best regards

tecRacer GmbH & Co. KG
Konstantinos Kiotes
Teamlead AWS Managed Services
Vahrenwalder Str. 156
30165 Hannover, Germany

Phone: +49 511 59095-964
E-Mail: kkiotes@tecracer.de<mailto:kkiotes@tecracer.de>
Internet: https://www.tecracer.de

Registergericht Hannover HRA 200331
Geschäftsführer: Markus P. Herrlich, Sven Ramuschkat, Torsten Höpfner
Komplementär: tecRacer Verwaltungs GmbH, Hannover HRB 200935

Von: Devin Hyden <notifications@github.com>
Antworten an: opendns/autotask-php <reply@reply.github.com>
Datum: Freitag, 31. August 2018 um 17:42
An: opendns/autotask-php <autotask-php@noreply.github.com>
Cc: Konstantinos Kiotes - tecRacer ☁ <kkiotes@tecracer.de>, Author <author@noreply.github.com>
Betreff: Re: [opendns/autotask-php] PHP Error (#122)


Looks like you are trying to manually import it. I would make sure you are referencing the proper autoload.php file and location. There is no SoapClient.php in this repo. The only reference to SoapClient is the to the native SoapClient. You could try deleting everything and attempting again.

If you could use composer, I would recommend that.

**Comment by SirPoot-** [comment]
@kkiotes Any luck?

**Comment by kkiotes** [comment]
Thank you for asking but i didn’t have the time to test it.

Mit freundlichen Grüssen / Best regards

tecRacer GmbH & Co. KG
Konstantinos Kiotes
Teamlead AWS Managed Services
Vahrenwalder Str. 156
30165 Hannover, Germany

Phone: +49 511 59095-964
E-Mail: kkiotes@tecracer.de<mailto:kkiotes@tecracer.de>
Internet: https://www.tecracer.de

Registergericht Hannover HRA 200331
Geschäftsführer: Markus P. Herrlich, Sven Ramuschkat, Torsten Höpfner
Komplementär: tecRacer Verwaltungs GmbH, Hannover HRB 200935

Von: Devin Hyden <notifications@github.com>
Antworten an: opendns/autotask-php <reply@reply.github.com>
Datum: Dienstag, 11. September 2018 um 15:42
An: opendns/autotask-php <autotask-php@noreply.github.com>
Cc: Konstantinos Kiotes - tecRacer ☁ <kkiotes@tecracer.de>, Mention <mention@noreply.github.com>
Betreff: Re: [opendns/autotask-php] PHP Error (#122)


@kkiotes<https://github.com/kkiotes> Any luck?

**Comment by SirPoot-** [comment]
@kkiotes any update? If not, can you close this issue?
