### ISSUE TITLE
Relation between Invoices, BillingItems and GeneralLedgerCode?

### ISSUE THREAD

**Issue by Rodeveer** [opendns/autotask-php#123]
I'm currently busy with getting the whole structure of Invoices from Autotask. But I'm stuck on getting the ledger codes for the BillingItems. There is in the admin a settings place with 'services' and General Ledger accounts. Though I can't find any of these items in a logical 'section' of the Autotask API.

I was looking into the 'AllocationCode' section but that didn't give me the exact right rows that I expected.
It would be nice to have to some feedback about this issue that I have with the relationships.

And maybe its nice to have an UML Diagram that shows the 'connections' in between the classes!
The rest is well made. Soap clients are always a pain to work with as a developer.

Thanks in advance!

**Comment by SirPoot-** [comment]
Hello @Rodeveer. I do not have experience with this request, I've not needed the gather this information. 

As you mentioned, the allocation code was the only reference I've seen in the API docs. When I called the getFieldInfo() against the AllocationCode entity, one of the fields had the name "GeneralLedgerCode" with picklist values and these were the same values I found under the Admin > General Ledger Accounts.

No UML Diagram that I'm aware of.

**Comment by Rodeveer** [comment]
Hello @SirPoot- !

Thanks for the headsup about the PickList values and the `getFieldInfo`! I did exactly the same thing and I see also the correct data.
Are these kinda things mentioned in the readme or something? Would be nice for other people to know also in the future! 

Thanks for the help. I'll close this for now and when I'm stuck again I'll reopen it! 👍
