### ISSUE TITLE
Limit my result

### ISSUE THREAD

**Issue by Cidvond** [opendns/autotask-php#127]
I have been doing some googling and searching past issues and I still can not get this code to work. I am wanting to search a Resource by their email address and return only their EntityId. I am able to find the resource but cannot figure out how to limit the output to just their EntityId so I can set that to a variable. 

Thanks for the help!

```
$query = new ATWS\AutotaskObjects\Query('Resource');

$emailField = new ATWS\AutotaskObjects\QueryField('Email');
$emailField->addExpression('Contains', 'agent@domain.com');

$query->addField($emailField);
print_r($client->query($query)); //returns everything about the Resource 
```

I tried adding the following but could not get it to work. I get the error "Undefined property: ATWS\AutotaskObjects\ArrayOfUserDefinedField::$EntityId"

```
$result = $client->query($query);
$entities = $result->queryResult->EntityResults->Entity;
foreach ($entities as $entity) {
    print($entity->EntityId . "\n");
}
```

**Comment by SirPoot-** [comment]
@Cidvond you are on the right track; however, there is no property called 'EntityId'. Sounds like you are looking to get the ID of the Resource which is the 'id' property.

Another note - I am sure you found out when you were searching past issues, you cannot perform any limits on the query. You will always get the full object in return and it is up to you to remove or use the data you want.

For a full list of fields (properties) you can reference the following WebService API document.
https://ww5.autotask.net/help/Content/LinkedDOCUMENTS/WSAPI/T_WebServicesAPIv1_5.pdf

**Comment by Cidvond** [comment]
@SirPoot- Thank you for getting back to me. That is correct, I was seeing that it would return everything. In one example it was showing to do this foreach to cut out what you didn't need. The issue is that no matter what I put  in the line print($entity->ANYTHING . "\n") I get an error back asking Undefined property: ATWS\AutotaskObjects\ArrayOfUserDefinedField::ANYTHING. I have tried a few things like ID and Email as well as FirstName, LastName. I am going to guess I have something wrong with the foreach statement then.

**Comment by Cidvond** [comment]
Resolved my issue. I was not going far enough to grab the ID. I ended up changing ending code to what is below. Thanks!

```
$result = $client->query($query);
$agentid = $result->queryResult->EntityResults->Entity->id;
```
