### ISSUE TITLE
Product Category API

### ISSUE THREAD

**Issue by ravisoni** [opendns/autotask-php#128]
Hello,
Is there any Entity/API which can pull product parent and child category ?

Thanks in advance

**Comment by SirPoot-** [comment]
All of the product information is under the 'Product' entity. There is a ProductCategory field you can include on your query for filtering. To find the ProductCategory values, run getFieldInfo('Product') when look for the field with the label 'Product Category', there will be a list of PickListValues.

**Comment by ravisoni** [comment]
Thank you for replying I checked the suggested entity and node, we re getting category Id only nothing more mean we are unable to know that "Product Category" node having parent category or child also what is the name of category. Another thing is if our product is not setup in any category we can not map those category with site.
What my concern is:
1 - We want to sync/map all parent and child category with our site. Either we have any product or not at AutoTask under that category.
2 - Separate entity of category also need to know if any category deleted at AutoTask we can take necessary action on site for that category as well as its product.
---
Thanks again to look into it.

**Comment by SirPoot-** [comment]
Can you confirm you are looking for a 'product' and not an 'installed product/asset'? If you are looking for a product and the respected product category, there is no way to manage the product categories via the API.

**Comment by ravisoni** [comment]
Hello,
Yes we are not looking for installed product/asset but for the product section is there any we to sync category as we do not want to create new category from API but want to map existing category so can sync and show product on the basis of category itself .
Also if not having such then is there any way that we can get in near future ?

Thanks for looking into it.

**Comment by reynolek** [comment]
There is not a way to manage the product categories via the API. You can make a request to Autotask to support this. The code provided is merely an interface to the API, and not owned by Autotask.
