### ISSUE TITLE
Portal button not visible

### ISSUE THREAD

**Issue by ravisoni** [opendns/autotask-php#129]
Hello,

When set contact portal using "ClientPortalUser" entity Portal button not visible even pass all required parameter with it.

In case we create contact and set portal detail directly in AutoTask that show the portal button but using API its not working.

Let me know how to fix the issue...?

**Comment by SirPoot-** [comment]
Make sure the client portal is enabled at the account level for the contact.

**Comment by ravisoni** [comment]
Thank you for replying, as per the code we are sending ClientPortalActive = TRUE node with "ClientPortalUser" entity.
You can see attached screenshot there two type of user we have created, one from the AutoTask panel and one using API.
![atp](https://user-images.githubusercontent.com/376508/50902764-ce6a1800-1441-11e9-8e27-8937fa1d3a74.png)
with the API user portal button not visible even after using all required node.
Is there any other setting for API or what is missing please help to sort out the issue.
---
Thanks again to look into it.

**Comment by SirPoot-** [comment]
Setting the ClientPortalActive to true enables the portal at the **CONTACT** level, but the client portal _also_ needs to be enabled at the **ACCOUNT** level so the contacts can use client portal. I have a strong feeling both contacts images you provided are from DIFFERENT **ACCOUNTS** which would explain why one contact has a client portal tab is shown on one other the other. The the client portal is enabled at the **ACCOUNT** level, there will be a client portal tab regardless of the client portal status, it where you go to setup the client portal in the UI.

Go through the following Autotask help article to make sure the client portal is setup at the ACCOUNT level of the contact with no 'client portal' tab. This account level management of the client portal is not accessible via the API.

https://ww5.autotask.net/Help/Content/AdminSetup/2ExtensionsIntegrations/ClientPortalTaskfire/Admin/ManageClientsAndUsers/MANAGECLIENTS.htm?cshid=1340

**Comment by SirPoot-** [comment]
@ravisoni still need to be open?

**Comment by ravisoni** [comment]
Yes I tried to use "ClientPortalActive = TRUE" in both portal and company API. But still its not sowing button there. Do you need API code to cross check what missing or wrong ??

**Comment by SirPoot-** [comment]
@ravisoni Any update?

**Comment by ravisoni** [comment]
Hello,

Will get back to you couple of days as tried it once but that not worked, so will follow the link again and test it. 
Will let you know soon if its work or not.

**Comment by SirPoot-** [comment]
@ravisoni @reynolek Close Request

**Comment by ravisoni** [comment]
Portal button visible in AutoTask Panel. Thanks for your support, meanwhile if you can guide to login contact in portal directly from website using any API or method that would be good, if we don't have that facility yet then we can close this issue for now...

**Comment by SirPoot-** [comment]
There is no way of auto-login in a user via a client access portal nor is there a way to use Autotask Client Portal login as an authentication source.
