### ISSUE TITLE
Using UDF id

### ISSUE THREAD

**Issue by czkoudy** [opendns/autotask-php#130]
Hi,

Fairly new to this and until now i have been using google and forums, but I am a bit lost now.

I have the following output of printf.

`=> ATWS\AutotaskObjects\Ticket Object ( 

[SubIssueType] => 276 
[TicketCategory] => 3 
[TicketNumber] => T20190109.0020 
[TicketType] => 1 
[Fields] => 
[UserDefinedFields] => ATWS\AutotaskObjects\ArrayOfUserDefinedField Object ( [UserDefinedField] => ) [id] => 52569 ) )`

I can access all the fields and their value.

However, I can't get the id in UDF.

and this is the rest of my code.

`$query = new ATWS\AutotaskObjects\Query('Ticket');
$package = new ATWS\AutotaskObjects\QueryField('TicketNumber');
$package->addExpression('Equals', $_GET['ticket-id']);

$query->addField($package);
// If you want to debug the XML produced by the Query object
//print($query->asXml());
// Print the results of the query
print_r($client->query($query));

$result = $client->query($query);

// This is an Array of Objects. In your case, \ATWS\AutotaskObjects\Ticket
$TicketDetail = $result->queryResult->EntityResults->Entity;`

Any help will be appreciated.

Thank you

**Comment by SirPoot-** [comment]
If there are no User Definied Fields set on an entity, nothing would be returned, like what you see above.

Just making sure your $GET[‘ticket-id’] value is T20190109.0020.

There is normal a lot more on the ticket like the AccountID

**Comment by JoshNW** [comment]
@czkoudy 

Can you explain the purpose of the code above?

**Comment by czkoudy** [comment]
@JoshNW i need to access the tickets by this fields rather than the autotaskID (Txxxxxxx.xxxx)

**Comment by SirPoot-** [comment]
@czkoudy That makes perfect sense. We just wanted to make sure. 

The ticket you are querying most likely does not have UDF set which is why they nothing is returned. Make sure or set some UDFs and then requery.
