### ISSUE TITLE
SoapClient issues with getting zone info

### ISSUE THREAD

**Issue by poxin13** [opendns/autotask-php#133]
Getting a few errors with the initial code setup. Looking at other issues, made sure I'm running an up-to-date version of OpenSSL: OpenSSL 1.1.0h. Have also tried other solutions mentioned in issues here with no luck.

`( ! ) Warning: SoapClient::SoapClient(): SSL operation failed with code 1. OpenSSL Error messages: error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed in /var/www/html/autotask/public/vendor/opendns/autotask-php/src/Client.php on line 173`

`( ! ) Warning: SoapClient::SoapClient(): Failed to enable crypto in /var/www/html/autotask/public/vendor/opendns/autotask-php/src/Client.php on line 173`

`( ! ) Warning: SoapClient::SoapClient(https://webservices.autotask.net/atservices/1.5/atws.wsdl): failed to open stream: operation failed in /var/www/html/autotask/public/vendor/opendns/autotask-php/src/Client.php on line 173`

`( ! ) Warning: SoapClient::SoapClient(): I/O warning : failed to load external entity &quot;https://webservices.autotask.net/atservices/1.5/atws.wsdl&quot; in /var/www/html/autotask/public/vendor/opendns/autotask-php/src/Client.php on line 173`

`( ! ) Fatal error: SOAP-ERROR: Parsing WSDL: Couldn't load from 'https://webservices.autotask.net/atservices/1.5/atws.wsdl' : failed to load external entity "https://webservices.autotask.net/atservices/1.5/atws.wsdl" in /var/www/html/autotask/public/vendor/opendns/autotask-php/src/Client.php on line 173`

**Comment by reynolek** [comment]
There are many reasons why this error can come up. The primary ones are typically system side and not actually client related.

Some googling for the error code has pointed me to ideas such as
1. System clock is off
2. host file modifications

**Comment by poxin13** [comment]
Not the best option, but adding
```
  'verify_peer' => false,
  'verify_peer_name' => false,
```
to stream_context_create worked for now
