### ISSUE TITLE
1.6 Development

### ISSUE THREAD

**Issue by JoshNW** [opendns/autotask-php#134]
Is there currently a development effort to incorporate the 1.6 API?

**Comment by SirPoot-** [comment]
From what I read in the docs. The current client should support v1.6. I've been a little busy recently and have not had a change to use 1.6, yet and been meaning to ask Ryan how he wants to handle that. I should be able to look into 1.6 a couple of days.

@reynolek How would you like to handle 1.6. As a tagged version or something else?

**Comment by reynolek** [comment]
Fully depends on the changes needed. If we can avoid managing extra branches of code, that'd be preferred. I havent been following anything API related for Autotask recently, ill have to read up on it. Is it backward compatible for example?

**Comment by SirPoot-** [comment]
@reynolek I submitted a PR with more information. It is backwards compatible; however, the newer entities will not be available in the older versions.

**Comment by reynolek** [comment]
[v0.3.0](https://github.com/opendns/autotask-php/releases/tag/v0.3.0) has been released with v1.6 API support. Thanks @SirPoot-

**Comment by JoshNW** [comment]
I apologize for the lack of response, I have been caught up with other tasks for the last week. It looks like you guys knocked this out in 7?! 

That is unbelievable! Thank you!

**Comment by SirPoot-** [comment]
@JoshNW No worries and you got it. Reach out if you have any questions.

**Comment by reynolek** [comment]
It was mostly @SirPoot- -- I just reviewed, merged and released.
