### ISSUE TITLE
Query from 2 TicketNote and TimeEntry and displaying this

### ISSUE THREAD

**Issue by czkoudy** [opendns/autotask-php#139]
Hi all,

I am building a portal for our client and iam looking into showing the ticket info on the portal from Autotask.

So far i can fetch and display all info required. However, iam having issue with ticket details, such as Notes and time entries.

I have separate queries for each (TicketNote and TimeEntry) and then Iam merging them together.

In order to have these in order by date iam using krsort() function as well.

`$query2 = new ATWS\AutotaskObjects\Query('TicketNote');
$package2 = new ATWS\AutotaskObjects\QueryField('TicketID');
$package2->addExpression('Equals', $ticketID);

$query3 = new ATWS\AutotaskObjects\Query('TimeEntry');
$package3 = new ATWS\AutotaskObjects\QueryField('TicketID');
$package3->addExpression('Equals', $ticketID);

$query2->addField($package2);
$query3->addField($package3);

$condition_status = new ATWS\AutotaskObjects\QueryField('Publish');
$condition_status->addExpression('Equals', '1');

$condition_status2 = new ATWS\AutotaskObjects\QueryField('CreatorResourceID');
$condition_status2->addExpression('notequal', '4');

$query2->addField($condition_status);
$query2->addField($condition_status2);

$result2 = $client->query($query2);
$result3 = $client->query($query3);

$entities2 = array($result2->queryResult->EntityResults->Entity);
$entities3 = array($result3->queryResult->EntityResults->Entity);

$entities_merge = array_merge((array)$entities2, (array)$entities3);`

But this doesnt work as TicketNote is using Description entity and TimeEntry is using SummaryNotes.

I am sure iam doing this wrong and there is better way, but i do need a bit of guidance. I have spent last week to try to figure this one out but iam lost.

Any help would be very appreciate it

**Comment by SirPoot-** [comment]
A couple of options -

1. Have your templating engine detect the type of object and use the fields according to your needs.

2. Standardize the keys before sending the array to your templating engine.

3. Use ternary operators to the select the proper key.

I prefer option one as I would display the data differently based on the object type.

**Comment by czkoudy** [comment]
option 1 definitely looks like the best option. I have never worked with objects and classes in PHP, so this might take a while.

Could you give me a little hint as what to look for?

In the meantime iam off to google to see what he got to say to this :-)

Thank you

**Comment by SirPoot-** [comment]
@czkoudy You can use the [get_class method](http://php.net/manual/en/function.get-class.php). From here you will know the type of object and your application can process accordingly.

![image](https://user-images.githubusercontent.com/9685068/53347337-b6553780-38cd-11e9-918f-d2052635c76d.png)

Are you using a PHP framework? If so, which one?

**Comment by czkoudy** [comment]
Thank you. I have found the get_class as well and after some hurdles, its working as expected. Apart from sorting by date.

I am not using any framework. Just had a quick look at some and i think that is the next level up for me :-D

**Comment by czkoudy** [comment]
hey,

So i have managed to display both TimeEntry and TicketNote queries. However my issue is now with sorting it by date correctly. At the moment it first sorts one and then the other. Any ideas?

Thank you

**Comment by SirPoot-** [comment]
Unfortunately the AccountToDo and AccountNote do not have the same key for the last change date (assuming you want to sort by last changed date). AccountNote = LastActivityDate and AccountToDo = LastModifiedDate. You will need to change one or both of the keys to be the same, then you will be able to sort the array based on the key to set.

**Comment by czkoudy** [comment]
Hey @SirPoot- Apologies for the very very late reply on this. But i had to postpone this issue as i had other issues arise. Back on this now. Could you help me how to achieve sorting this by date for both fields? Is it just a loop through the query and changing the field in the array? Thank you

**Comment by SirPoot-** [comment]
@czkoudy I recommend setting the array key on the date key to be the same then you can sort the array.

**Setting the date field to be the same**
```
//php
foreach ($entities as $key => $value)
{
    if ($key === "LastActivityDate" || $LastModifiedDate === "LastModifiedDate")
    {
        $key = "datetime";
    }
}
```

**Sort array by date**
https://stackoverflow.com/questions/41894931/sort-associate-array-by-datetime-key
