### ISSUE TITLE
Create Account

### ISSUE THREAD

**Issue by rahulsparx** [opendns/autotask-php#14]
Hi,

I need to create Account in Autotask by using PHP. Then Users will be able to enter their AutoTask credentials to log into the AutoTask portal and access their HelpDesk page. 

Could you help me, how can i achive this?

Thanks & Regards,
Rahul Kumar

**Comment by reynolek** [comment]
If you look at the [Account class](https://github.com/opendns/autotask-php/blob/master/src/AutotaskObjects/Account.php#L6) you will find the required fields for creating an account. 

Simply instantiate [the client](https://github.com/opendns/autotask-php/blob/master/src/Client.php) in the same way as in the [README](https://github.com/opendns/autotask-php/blob/master/README.md#usage) and call [create](https://github.com/opendns/autotask-php/blob/master/src/Client.php#L139) while passing in the Account object that you wish to create.

**Comment by reynolek** [comment]
closing this as an old issue.
