### ISSUE TITLE
Create Contact Group giving FATAL error

### ISSUE THREAD

**Issue by ravisoni** [opendns/autotask-php#142]
Hello,

We were getting below error in "ContactGroupContact.php" file while using create contact group API. 
Fatal error:  Uncaught SoapFault exception: [Client] SOAP-ERROR: Encoding: object has no 'id' property
Please check a pull request also which I have push after handle this in class. Take necessary action if changes need to keep/remove/improvements

Thanks.

**Comment by SirPoot-** [comment]
Yes. The 'id' field is required on all Autotask Entity not just ContactGroupContact. I've created PR #143 to address this.

**Comment by SirPoot-** [comment]
#143 has been implemented. @ravisoni can you close this issue?

**Comment by ravisoni** [comment]
Reported issue has been fixed once upgrade files from GIT. Thanks for your support
