### ISSUE TITLE
Relation between "Project" and "Resource"

### ISSUE THREAD

**Issue by H4mmp3l** [opendns/autotask-php#145]
Hello,

how to get all employees that are assigned to an project?
I tried to fetch the department, but there I also get employees that are not assigned to the project.

Thanks in advance :)

**Comment by SirPoot-** [comment]
@H4mmp3l Resources are not assigned to projects. Resources are assigned to entities of the project; tasks, tickets, etc. Yes, there is a team section in the project UI and that is an aggregate of the entity assigned resource.
