### ISSUE TITLE
Problems creating new UserDefinedFieldDefinition 

### ISSUE THREAD

**Issue by thisleenoble** [opendns/autotask-php#146]
I'm having no luck creating a new UserDefinedFieldDefinition using the API. I can successfully populate pre-existing UDFields but in attempting to create new ones I'm getting errors
```php
$udfDefinition = new UserDefinedFieldDefinition();
$udfDefinition->Name = 'FooBar';
$udfDefinition->DataType = 1; // [string] got this by fishing with getFieldInfo eventually
$udfDefinition->UdfType = 7; // [ticket] ditto
$udfDefinition->IsVisibleToClientPortal = true;
$udfDefinition->IsActive = true;
$udfDefinition->DefaultValue = '';
var_export($udfDefinition);
var_export($client->create($udfDefinition));
```
The call to $client->create generates an exception:

```xml
System.Web.Services.Protocols.SoapException: Server was unable to read request. ---> System.InvalidOperationException: There is an error in XML document (2, 439). ---> System.FormatException: Input string was not in a correct format.
   at System.Number.StringToNumber(String str, NumberStyles options, NumberBuffer& number, NumberFormatInfo info, Boolean parseDecimal)
   at System.Number.ParseInt64(String value, NumberStyles options, NumberFormatInfo numfmt)
   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReader1.Read287_UserDefinedFieldDefinition(Boolean isNullable, Boolean checkType)
   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReader1.Read5_Entity(Boolean isNullable, Boolean checkType)
   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReader1.Read317_create()
   at Microsoft.Xml.Serialization.GeneratedAssembly.ArrayOfObjectSerializer40.Deserialize(XmlSerializationReader reader)
   at System.Xml.Serialization.XmlSerializer.Deserialize(XmlReader xmlReader, String encodingStyle, XmlDeserializationEvents events)
   --- End of inner exception stack trace ---
   at System.Xml.Serialization.XmlSerializer.Deserialize(XmlReader xmlReader, String encodingStyle, XmlDeserializationEvents events)
   at System.Web.Services.Protocols.SoapServerProtocol.ReadParameters()
   --- End of inner exception stack trace ---
   at System.Web.Services.Protocols.SoapServerProtocol.ReadParameters()
   at System.Web.Services.Protocols.WebServiceHandler.CoreProcessRequest()'
            
```
Is there any way to actually *see*? the XML to try and work out what it's complaining about?
The only other field I can see from using getFieldInfo that's required is ID, but I thought that was generated on creation and would have no idea what to put in there if it weren't. Clues appreciated. L

**Comment by SirPoot-** [comment]
You need to set the UserDefinedFieldDefinition in an array and then associate that array to ArrayOfUserDefinedField. Issue #12 has an example.

You can see the XML by executing $query->asXml()

**Comment by thisleenoble** [comment]
I'm happy to be corrected but I can't work out how to apply that to this scenario. I already have working code to add a value to a UDF on a ticket:

```php
                $fooField = new UserDefinedField();
                $fooField->Name = $udfFieldName;
                $fooField->Value = 'My value';

                $arrayofUDF = new ArrayOfUserDefinedField();
                $arrayofUDF->UserDefinedField = [$fooField];

                $ticket->UserDefinedFields = $arrayofUDF;
                foreach($ticket as $key=>$value){
                    if($value === '' || $value === null){
                        unset($ticket->$key);
                    }
                }
                $client->update($ticket);
```
What I'm attempting to do above is define a new UDF. You can't arbitrarily add a new UDF to a ticket using the above method (I've tried) since you have to use a UDF field name that the system will accept. This requires the user to create a new UDF first using the exact name used in the code. I'm trying to get around the issue of string mismatch caused by client error by creating a new UserDefinedField*Definition* which would replace the user having to create the field first.

If your solution is applicable and there's some aspect to which I have to employ arrays of other entity types then you may need to be a little more explicit.

**Comment by SirPoot-** [comment]
There are no Autotask admin functions from the API. Setting up an entity UDF is considered an admin function. Thus, you cannot create/update entity UDFs from the API. You can only set / update existing UDFs when creating or updating an entity. Did not mean you leave you in the dark - there is some assumed knowledge of Autotask behavior.

You can see the set UDF's for an entity by running $client->getUDFInfo($entity)

For example, if you query a ticket, you can see the UDFs and update them as needed. If you are creating a new ticket, you will need to create an array of the UDF's (that are already set in Autotask) and attach to your ticket object.

If you look at the readme in reference to the $query object, it is referencing a 'ATWS\AutotaskObjects\Query' object most likely your $ticket. You can 'print($ticket->asXml())' prior to sending it to Autotask or dump $ticket.

Back to your issue, it is hard to assist without seeing the full code. Are you creating a ticket or updating a ticket?

**Comment by thisleenoble** [comment]
Thanks very much for trying to help me with this problem. I'm afraid it's not always easy for me to just paste in code I'm working on (hence the delay). I've abstracted certain functionality out to other class methods so I had to de-abstract it, and change some variable names in case it betrays confidential information. 

I don't have any prior knowledge about Autotask. I don't use Autotask. My client doesn't use Autotask. My client's clients use Autotask and I've got access to an account for the purposes of developing an addition to my client's application to write data back to their clients' tickets. I'd already created the functionality to write back to a UDF that I had defined within Autotask, and I can see that information presented on the ticket details page. 

My client would have to convey to all of their clients the very complicated set of screens they have to go through to establish that state within their Autotask service desk before the writeback will work. They have informed me (and I've not found anything to contradict that in the Autotask documentation) that you can create these UserDefinedFieldDefinitions using the API. So here is the method that performs the writeback in as simple a form as I can make it.

```php
    const DATA_TYPE_STRING = 1;
    const DATA_TYPE_DATE = 2;
    const DATA_TYPE_LIST = 3;
    const DATA_TYPE_NUMERIC = 4;
    const ENTITY_TYPE_TICKET = 7;

    public static function autotask_update_ticket(\response $response = null){
        try {
            $authOpts = array(
                'login' => 'USERNAME',
                'password' => 'PASSWORD',
                'trace' => 1,   // Allows us to debug by getting the XML requests sent
            );
            $wsdl = str_replace('.asmx', '.wsdl', 'AUTOTASK_ZONE_URL');
            $client = new Client($wsdl, $authOpts, 'INTEGRATION_CODE');

            $query = new Query('Ticket');

            $ticketIDField = new QueryField('id');
            $ticketIDField->addExpression('Equals', 'TICKET_ID');
            $query->addField($ticketIDField);

            $ticket = false;
            $ticketQueryResult = $client->query($query);
            if($ticketQueryResult instanceof QueryResponse){
                if($ticketQueryResult->queryResult instanceof ATWSResponse){
                    if($ticketQueryResult->queryResult->EntityResults instanceof ArrayOfEntity){
                        if($ticketQueryResult->queryResult->EntityResults->Entity instanceof Ticket){
                            $ticket = $ticketQueryResult->queryResult->EntityResults->Entity;
                        }
                    }
                }
            }

            if($ticket instanceof Ticket) {
                $udfFieldName = 'foo';
                { // This is the bit that's not working
                    if(!self::ticketHasUDF($ticket, $udfFieldName)){
                        $udfDefinition = new UserDefinedFieldDefinition();
                        $udfDefinition->Name = $udfFieldName;
                        $udfDefinition->DataType = self::DATA_TYPE_STRING;
                        $udfDefinition->UdfType = self::ENTITY_TYPE_TICKET;
                        $udfDefinition->IsVisibleToClientPortal = true;
                        $udfDefinition->IsActive = true;
                        //$udfDefinition->DefaultValue = '';
                        var_export($udfDefinition);
                        echo 'Calling to create!';
                        var_export($client->create($udfDefinition));
                        //die('xxx');
                        if(!self::ticketHasUDF($ticket, $udfFieldName)) {
                            //die('still doesn\'t have ' . $udfFieldName);
                        }
                        //die('it does now!');
                        var_export($ticket);
                    }
                }

                { // this bit works if the UDF has been defined already within the Autotask UI
                    $myField = new UserDefinedField();
                    $myField->Name = $udfFieldName;
                    $myField->Value = $response->myAttribute;

                    $arrayofUDF = new ArrayOfUserDefinedField();
                    $arrayofUDF->UserDefinedField = [$myField];

                    $ticket->UserDefinedFields = $arrayofUDF;

                    foreach($ticket as $key=>$value){
                        if($value === '' || $value === null){
                            unset($ticket->$key);
                        }
                    }
                    var_export($client->update($ticket));
                } // bit that definitely works ends
            } else {

            }
        } catch (\Exception $e){
            var_export($e->getMessage());
            // log to events in cp and return
            return;
        }
}

private static function ticketHasUDF(ticket $ticket, $udName){
        $hasUDF = false;
        if($ticket->UserDefinedFields instanceof ArrayOfUserDefinedField){
            foreach($ticket->UserDefinedFields->UserDefinedField as $field){
                if($field instanceof UserDefinedField){
                    if($field->Name == $udfName){
                        $hasUDF = true;
                        break;
                    }
                }
            }
        }
        return $hasUDF;
}
```

**Comment by SirPoot-** [comment]
Thank you for the code. I understand the you goal and do stand corrected, it **DOES** look like you can create the UDFs for the API. (I have never had the need to do this). 

Can you add '$udfDefinition->id = 0;' and send off a create request? Let see if that works, if that does not work, can you share your $client->__getLastRequest(); This will display the SOAP call to Autotask and help troubleshooting.

**Comment by thisleenoble** [comment]
You know what, adding that 0 for the ID has worked! Unbelievable.
Thanks very much. Now, I wonder if there's a way to move it up the list in this interface via the API ;)
(needs to go above 6 in what would be position 5.2 - it's probably not possible but this is a massive help)

![Screen Shot 2019-08-22 at 18 34 49](https://user-images.githubusercontent.com/3305621/63536472-9369b000-c50b-11e9-89cc-a03b248dc675.jpg)

**Comment by SirPoot-** [comment]
You're welcome. Setting the id field to 0 is something I've learned while using this library. Side note, if you create the UDF, it will not be on your ticket object unless you re-query; however, it is safe to say you are good to go adding that field to the field to the Existing UserDefinedFields array

That does not look possible. That is a setting under the ticket category not present under the API.
