### ISSUE TITLE
Getting started is a problem with API 1.6

### ISSUE THREAD

**Issue by weha** [opendns/autotask-php#147]
The only thing I can get working is de zone information.
All the other examples result in "unauthorized" or "exception".

It seems that the readme is incomplete on how to use it properly for 1.6
Take the following code for example, multiple variables that are set, are not used:
`$authOpts = array(
    'login' => $username,
    'password' => $password,
    'trace' => 1,   // Allows us to debug by getting the XML requests sent
);`
Not used
`$integrationCode = '27-character ID';`
Used
`$wsdl = str_replace('.asmx', '.wsdl', $zoneInfo->getZoneInfoResult->URL);`
Not used
`$client = new ATWS\Client($authWsdl, $opts, $integrationCode);`
2 unknown variables.

This makes it very unclear on how to get it working.
Would it be possible to provide a working example for 1.6 please?

Thank you!

**Comment by SirPoot-** [comment]
The working example is in the readme. If you are connecting to version 1.6, you are required to provide an integration code.

If you do not want to provide / have an integration code, you cannot only use version 1.5.

**Comment by weha** [comment]
I know, I'm saying I can't get it working.
Even with the integration code I get unauthorized or an exception.
Since the examples seem to be using different variables on different lines it is very unclear to me how to get it working.
Can you please provide a fully working example?

Thank you.

**Comment by SirPoot-** [comment]
The readme example for 1.5 and 1.6 are working examples. 

For 1.6, I would make sure the user you are connecting as is the type ‘API User’. 

Provide your entire code if you would like assistance.
