### ISSUE TITLE
How to Authenticate contact using login form

### ISSUE THREAD

**Issue by harshek** [opendns/autotask-php#149]
Hello,

I setup a login form on website, how we can Authenticate user using Autotask 1.6?
Do we have API for this?

More Detailed Information:
We are able to authenticate our API connection but we want to Integrate further APIs for which we need Contacts to Authenticate and process accordingly, but we are unable to find option/API to authenticate contact so can we have one for same?

**Comment by SirPoot-** [comment]
That is not possible with version 1.6. Plus with 1.6, an integration code is required per user.
