### ISSUE TITLE
Unable to fetch attachments from autotask

### ISSUE THREAD

**Issue by adilk90** [opendns/autotask-php#15]
I have fetched contracts, contacts, resource and tickets from autotask succesfully. Now, I need to fetch the attachment for tickets, I have used the ticket id as parentId for fetching the AttachmentInfo but when I try to fetch the Attachment data using the AttachmentInfo id it gives me error in the response.

Unable to cast object of type 'autotask.web.services.API.Attachment' to type 'autotask.web.services.API.Entity

Can anyone help me in this ?

**Comment by reynolek** [comment]
Unfortunately I haven't worked with attachments -- there were some previous issues that people opened around attachments, so hopefully someone can assist!

**Comment by reynolek** [comment]
This is a super late comment, but I believe I added the ability to [create attachments a while back](https://github.com/opendns/autotask-php/blob/master/src/Client.php#L157) -- have you given that a shot? Did it work for you?

**Comment by reynolek** [comment]
closing, feel free to re-open if you are still having issues.

**Comment by Dunnestein** [comment]
For anyone landing on this thread searching on the error, like I did:

Don't use Entity Attachment for querying on AttachmentID, but use Entity AttachmentInfo instead. AttachmentInfo will return the attachment object. Feed the return object in the getAttachment function as the input parameter to actually receive the attachment (data and info).
