### ISSUE TITLE
Errors with examples

### ISSUE THREAD

**Issue by beo-code** [opendns/autotask-php#150]
Hi,
I am receiving the following errors when trying to run an example script (udf_query_example.php).

Any ideas?
php version 5.6.38

> stdClass Object ( [getZoneInfoResult] => ATWS\AutotaskObjects\ATWSZoneInfo Object ( [CI] => -1 [DataBaseType] => [ErrorCode] => -1 [URL] => [WebUrl] => ) )
> Notice: Undefined offset: 4 in C:\xampp\htdocs\src\Client.php on line 182
> 
> Fatal error: Uncaught SoapFault exception: [WSDL] SOAP-ERROR: Parsing WSDL: Couldn't load from 'C:\xampp\htdocs' : failed to load external entity "C:\xampp\htdocs" in C:\xampp\htdocs\src\Client.php:188 Stack trace: #0 C:\xampp\htdocs\src\Client.php(188): SoapClient->SoapClient('', Array) #1 C:\xampp\htdocs\udf_query_example.php(28): ATWS\Client->__construct('', Array) #2 {main} thrown in C:\xampp\htdocs\src\Client.php on line 188

```
require_once 'C:\xampp\htdocs\src\autoload.php';

// Edit these variables to get this example to work for you
$username = 'xxxxxxx';
$password = 'xxxxxxx';

// End Edit Region

$authWsdl = 'https://webservices4.autotask.net/atservices/1.5/atws.wsdl';
$opts = array('trace' => 1);
$client = new ATWS\Client($authWsdl, $opts);
$zoneInfo = $client->getZoneInfo($username);

print_r($zoneInfo);

$authOpts = array(
    'login' => $username,
    'password' => $password,
    'trace' => 1,   // Allows us to debug by getting the XML requests sent
);
$wsdl = str_replace('.asmx', '.wsdl', $zoneInfo->getZoneInfoResult->URL);
$client = new ATWS\Client($wsdl, $authOpts);

$query = new ATWS\AutotaskObjects\Query('InstalledProduct');

$package = new ATWS\AutotaskObjects\QueryField('Package', true);
$package->addExpression('Equals', 'Umbrella for MSPs');

$query->addField($package);

// If you want to debug the XML produced by the Query object
// print($query->asXml());

// Print the results of the query
print_r($client->query($query));
```

**Comment by SirPoot-** [comment]
Can you switch to version 1.6 of the API? 1.5 is End of Life and not being updated. I have not connect to version 1.5 in a year or so, but the code was working then.

If you are going to auto-fetch your zone - it is advised to use ‘ $authWsdl = 'https://webservices.autotask.net/atservices/1.5/atws.wsdl';’

Let me know how that goes. I can investigate further when I get in front of a computer, if needed.

**Comment by DaveBz** [comment]
Hi,
Thanks for the info - where can I download 1.6? I downloaded straight from GitHub which I presume has provided me with 1.5?

Thanks!

**Comment by SirPoot-** [comment]
Version 1.6 of Autotask’s API, not this client. 

Follow these steps to set it up. You will need an intervention code.
https://github.com/opendns/autotask-php/blob/master/README.md#version-16
