### ISSUE TITLE
Sending Ticket Reply as User and Not API

### ISSUE THREAD

**Issue by thekingster** [opendns/autotask-php#151]
Hi All

I can successfully create a ticket, but when the user (external) is sending a reply, I can only get it to show in Autotask as the API user account. Does anyone know the field to set to make this show as the user like email replies do? It is not possible to send an email from the user from my app due to fraud detection\DKIM etc.

Thanks

Dave

**Comment by SirPoot-** [comment]
I’m a little confused. Assuming you are using workflow rules to send the email, you have two options. 

1. change the workflow rule to send the email out at the generic email processing email address
2. Use user impersonation  to create the ticket as that user, then the workflow rule will trigger as that user.

If you are not sending the email via a workflow rule, I will need additional clarification.

**Comment by thekingster** [comment]
No, so when a person updates a ticket on our code, we want to insert an entry into the ticket reply table. But when we do it's just showing as the API user

[9] => ATWS\AutotaskObjects\TicketNote Object
        (
            [CreatorResourceID] => 
            [Description] => bflo1234

From: IT Services Support Desk 
Date: Friday, August 30, 2019 at 3:38 AM
            [LastActivityDate] => 2019-08-30T09:59:18.967
            [NoteType] => 1
            [Publish] => 1
            [TicketID] => 167323
            [Title] => Your Ticket Has Been Updated:  - Permissions for our shared calendar 
            [Fields] => 
            [UserDefinedFields] => ATWS\AutotaskObjects\ArrayOfUserDefinedField Object
                (
                    [UserDefinedField] => 
                )

            [id] => 30321364
        )

**Comment by thekingster** [comment]
CreatorresourceID we do not know what to put so reply is from the client rather than API

**Comment by SirPoot-** [comment]
Thank you for the clarification. It is not possible at this time to create a ticket note on behalf of an account contact. I so happened to talk to the API manager about this exact scenario earlier this year and he liked the idea and see how that can be useful. However, no promises or timeline.

I would recommend emailing ‘support@autotask.net’ with the ‘API’ in the subject (to get routed properly) with the ticket note on contact behalf request. 

I have not built out a custom client portal yet because of this as it was a requirement.

**Comment by thekingster** [comment]
Thanks

The only way I can think of doing it is adding the web server into the SPF record and sending from the clients email address, but then DKIM enabled it will fail.

**Comment by SirPoot-** [comment]
Yes. The only way to send an email out as the account contact would be sending it yourself. Depending on how you send it, it would be signed and make DKIM work if not, you could at least setup DMARC. No perfect scenario.

**Comment by SirPoot-** [comment]
> Hello sir,
> 
> i am the developer for @thekingster and developed a custom client portal . but when user add ticket reply to his ticket then it shows that the reply is from API USER Not from that user himself.
> 
> please give me solution for it

https://github.com/opendns/autotask-php/issues/151#issuecomment-538678965
