### ISSUE TITLE
Example contains typo

### ISSUE THREAD

**Issue by rtenklooster** [opendns/autotask-php#153]
`$wsdl = str_replace('.asmx', '.wsdl', $zoneInfo->getZoneInfoResult->URL);
$client = new ATWS\Client($authWsdl, $opts, $integrationCode);
$client->setResourceImpersonation(87654321);`

The client should connect to $wsdl and not to $authWsdl. so:
`$wsdl = str_replace('.asmx', '.wsdl', $zoneInfo->getZoneInfoResult->URL);
$client = new ATWS\Client($wsdl, $opts, $integrationCode);
$client->setResourceImpersonation(87654321);`

**Comment by SirPoot-** [comment]
Yes, you are correct. Keen eye. Want to submit a PR?

**Comment by shadow-42** [comment]
fixed in PR https://github.com/opendns/autotask-php/pull/157
