### ISSUE TITLE
Version 1.6 : Request is blank output

### ISSUE THREAD

**Issue by Rikgeffen** [opendns/autotask-php#154]
Hello there,

The 21 of December I was working on a test that made thousends of requests. This worked without a problem. Two days later I wanted to make an other test but came to the declusion there wasnt any output. I tested al my projects I already made, not one gave a result or error.

I came to the conclusion I can get my zoneInfo but can't request a query?

This is my code for a simple search Contacts

```
//Autotask Credentials
require 'autotask-php-master/src/autoload.php';

$username = 'Username';
$password = 'Password';

$integrationCode = 'Code';


//Create Query
$query = new ATWSAutotaskObjectsQuery('Contact');
$address = new ATWSAutotaskObjectsQueryField('firstName');
$address->addExpression('Equals', 'test');
$query->addField($address);


//Connect
$authWsdl = 'https://webservices.autotask.net/atservices/1.6/atws.wsdl';
$opts = array('trace' => 1);
$client = new ATWSClient($authWsdl, $opts);
$zoneInfo = $client->getZoneInfo($username);

$authOpts = array(
'login' => $username,
'password' => $password,
'trace' => 1, // Allows us to debug by getting the XML requests sent
);
$wsdl = str_replace('.asmx', '.wsdl', $zoneInfo->getZoneInfoResult->URL);
$client = new ATWSClient($wsdl, $authOpts);
$client->setIntegrationCode($integrationCode);


//Print Result
print_r($client->query($query));
```

The output of this script is a blank page result with the correct url. Even if I set an echo on the end of the page, it set itself to blank.

What is causing this and how do I fixed this?

**Comment by SirPoot-** [comment]
ATWSAutotaskObjectsQueryField should be ‘FirstName’ not ‘firstName’. The field name needs to be exactly how it is on the API docs.
