### ISSUE TITLE
How to get count of tickets?

### ISSUE THREAD

**Issue by aditya-did** [opendns/autotask-php#155]
Hello,
I just want to get information regarding the number of ticket, accounts, etc. Only the count not all information.
Do we have a specific function or can use the query() to get the info.

Thanks

**Comment by Dillonsmart** [comment]
This would be useful, as ordering tickets isn't available, knowing the amount of tickets can help.

**Comment by SirPoot-** [comment]
This is not possible. You will need to make multiple queries until a response is less than 500 objects and perform calculations yourself.
