### ISSUE TITLE
Find out if a ticket is assigned to TaskFire

### ISSUE THREAD

**Issue by BristolITDave** [opendns/autotask-php#156]
Firstly, I wanted to say "Thank you" for making this API!

Secondly, I was wondering if anyone had found a way to find out if a ticket is allocated to [TaskFire] rather than the main company.

I did a diff on a ticket before and after assigning it to TaskFire and saw no discernable difference in any of the fields. Is there a different method I should use?
![image](https://user-images.githubusercontent.com/8375536/72529294-e77f8300-3864-11ea-939a-6f573ec0578c.png)
[ticketinfo-assigned-autotask-psa.txt](https://github.com/opendns/autotask-php/files/4071476/ticketinfo-assigned-autotask-psa.txt)
[ticketinfo-assigned-taskfire.txt](https://github.com/opendns/autotask-php/files/4071477/ticketinfo-assigned-taskfire.txt)

Thank you in advance,
Dave

**Comment by BristolITDave** [comment]
I've found a temporary workaround, as after studying the API documentation provided by Autotask there is barely a mention of TaskFire. Under the Ticket object there's absolutely no information about it.
I'll still leave the issue open in case someone does know how to read this information.

For any future visitors to this issue, my workaround:
Create two workflow rules:
**Rule 1**
[TaskFire] From TaskFire to Service Provider
When a ticket is: Created by [Anyone] Edited By [Anyone]
Conditions:
"Is Transferred from Taskfire to Service Provider" Equal To "True"
Updates
Change Queue to Helpdesk [A primary queue]

**Rule 2**
[TaskFire] From Service Provider to TaskFire
When a ticket is: Created by [Anyone] Edited By [Anyone]
Conditions:
"Is Transferred from Service Provider to TaskFire" Equal To "True"
Updates
Change Queue to Client Portal [A different queue]

You can then detect the Queue that a ticket is in as usual using the API.

**Comment by JoshNW** [comment]
We did a good bit of work with taskfire mid 2019 and ran into some roadblocks while using the API.

There are a few things that you want to keep in mind when working with taskfire tickets: 

     -TaskFire Tickets and AutotaskTickets are not the same entity and that creates some headaches
     -The TaskFire Ticket entity and associated items (queues, statuses, ect) does not exist in the API
     -Tickets created in TaskFIre will only be visible in the AutoTask if they are Transferred, then returned (Until a ticket is transferred then returned to the client, the Taskfire Ticket number will not be searchable in Autotask) 
    -Feilds set by the Client in Taskfire, such as Queue and Status, can NOT be accessed via API

We did get our system running well, but only after a lot of stumbling into roadblocks and limitations. If you have a choice, I would strongly recommend reaching out to your account manager to see if giving your customers direct access to a limited view in Autotask (not taskfire) better fits your needs.

**Comment by BristolITDave** [comment]
Thanks Josh, did give Kudos previously, but open coming back to this today, also added a comment. Taskfire should be such a good product it's a shame it hasn't had the investment it needs considering it's licensing cost.

**Comment by BristolITDave** [comment]
I will close this issue for now, as "not possible"
