### ISSUE TITLE
Working with Billing items

### ISSUE THREAD

**Issue by JoshNW** [opendns/autotask-php#158]
I am currently looking to automate the approval and post processes, but do not see a means to do so via API. 

The Billing Item Entity only has one field that allows updates and does not appear to have an "Approved" flag. 

Is there another entity that could be used for this function. 

Example logic -> Query all Billing Items that are not approved, between these dates, and linked to this customer. For each item, change the status to approved, post on the first day of the next month.

**Comment by SirPoot-** [comment]
I've looked into it and have not been successful outside of browser automation which did not work out to well.

**Comment by JoshNW** [comment]
@SirPoot- thank you sir, I was afraid of that. 

I may submit a request for pricing. I am using workfusion for browser automation and RPA and have mixed results in Autotask. What application/methods have you attempted? (If you don't mind sharing of course)

**Comment by JoshNW** [comment]
I am closing this issue, as it is not a problem or limitation in the PHP wrapper, but a limitation of the API itself.

I will post an update if Autotask provides a method to approve billing item approval via API. 

Thank you.
