### ISSUE TITLE
Uncaught SoapFault exception

### ISSUE THREAD

**Issue by MarenLa** [opendns/autotask-php#159]
**My Code**
$authWsdl = 'https://webservices.autotask.net/atservices/1.6/atws.wsdl';
$opts = array('trace' => 1);
$client = new ATWS\Client($authWsdl, $opts, $integrationCode);
$zoneInfo = $client->getZoneInfo($autotask_username);

print_r($zoneInfo);

$authOpts = array(
    'login' => $autotask_username,
    'password' => $autotask_password,
    'trace' => 1,  );

$wsdl = str_replace('.asmx', '.wsdl', $zoneInfo->getZoneInfoResult->URL);
$client = new ATWS\Client($wsdl, $authOpts);

$query = new ATWS\AutotaskObjects\Query('Contact');

$firstnameField = new ATWS\AutotaskObjects\QueryField('firstname');
$firstnameField->addExpression('Equals', 'Steve');

$query->addField($firstnameField);

// If you want to debug the XML produced by the Query object
// print($query->asXml());

// Print the results of the query
//print_r($client->query($query));

**Error Message:**
Fatal error: Uncaught SoapFault exception: [WSDL] SOAP-ERROR: Parsing WSDL: Couldn't load from 'https://webservices18.autotask.net/ATServices/1.6/atws.wsdl' : failed to load external entity "https://webservices18.autotask.net/ATServices/1.6/atws.wsdl" in C:\xampp\htdocs\Autotask_Auswertung_Regelbetrieb\autotask_auswertung_regelbetrieb.git\_autotaskServices\client.php:187 Stack trace: #0 C:\xampp\htdocs\Autotask_Auswertung_Regelbetrieb\autotask_auswertung_regelbetrieb.git\_autotaskServices\client.php(187): SoapClient->SoapClient('https://webserv...', Array) #1 C:\xampp\htdocs\Autotask_Auswertung_Regelbetrieb\autotask_auswertung_regelbetrieb.git\auth_autotask.php(72): ATWS\Client->__construct('https://webserv...', Array) #2 C:\xampp\htdocs\Autotask_Auswertung_Regelbetrieb\autotask_auswertung_regelbetrieb.git\index.php(47): autotask_log() #3 {main} thrown in C:\xampp\htdocs\Autotask_Auswertung_Regelbetrieb\autotask_auswertung_regelbetrieb.git\_autotaskServices\client.php on line 187

**Comment by SirPoot-** [comment]
For your Autotask account, are you using a user with the security level of 'API User'?

**Comment by MarenLa** [comment]
> For your Autotask account, are you using a user with the security level of 'API User'?

Yes I use an Sandbox API User

**Comment by SirPoot-** [comment]
Wonderful. Does the API User have the security level / permissions to view contacts?

**Comment by MarenLa** [comment]
Yes, we already use it for another application.

**Comment by MarenLa** [comment]
I forgot to  use \ATWS\AutotaskObjects;
