### ISSUE TITLE
How to view in PHP application

### ISSUE THREAD

**Issue by Capmouda** [opendns/autotask-php#16]
Hello,
I am new to PHP, and I usually list things from MySQL database using while statements and echo from a mysqli_fetch_array.
How can I have the returned data from Autotask into an array that I can work with in the same manner.

Thank you.

**Comment by reynolek** [comment]
Because of the way that Autotask returns the data, and how SOAP works, there's no real way to get the data in an array.

Since you are new to PHP, I fully recommend looking into Object Oriented Programming (OOP for short). The way you are working with Autotask data is in an object oriented way. There are a multitude of online tutorials and explanations for PHP and OOP. [Here's one of the ones I found](http://code.tutsplus.com/tutorials/object-oriented-php-for-beginners--net-12762).

Once you master the basic concepts, you should have no problem working with the Autotask client, and its API.

Good luck!

**Comment by Capmouda** [comment]
@reynolek 
Thanks. Do I have to have the Composer installed? what is its role. I was able to pull the data without it.
Also, what is the format returned from the query samples on the project page? XML?

**Comment by reynolek** [comment]
Composer is a package manager for PHP. It helps you download and maintain dependencies in your application. It is by no means required, just an easy way to install the autotask-php code and use it.

If you use `print_r` you will be able to see the full format -- on the main project page I have some XML that shows you what is generated for the push, but you don't have to worry about it. The data you get back from calling the methods in the autotask-php library will return a PHP class ([all of which should be available to be seen here](https://github.com/opendns/autotask-php/tree/master/src/AutotaskObjects))

**Comment by Capmouda** [comment]
@reynolek 
Thank you for your help earlier. 
So here is my final code (so i can output the required fields in a table for instance)

Working on Accounts:
		$result = $client->query($query);
                 
foreach ($result as $account) {
			    print($account->AccountName . "\n");
			}

Running the code above returns:
Notice: Undefined property: ATWS\AutotaskObjects\ATWSResponse::$AccountName ....

What am i doing wrong here?

**Comment by reynolek** [comment]
The result you get back from autotask isn't immediately an account. It's actually a queryResponse object. If you print_r the result you will see there is a detailed path to get to Entity inside the queryResult. You want to loop over that.

**Comment by Capmouda** [comment]
Thanks. thats what i am following.

here is my result: partial
ATWS\AutotaskObjects\QueryResponse Object ( [queryResult] =>
ATWS\AutotaskObjects\ATWSResponse Object ( [EntityResults] =>
ATWS\AutotaskObjects\ArrayOfEntity Object ( [Entity] =>
ATWS\AutotaskObjects\Account Object ( [AccountName] => NYClient1
[AccountType] => 1 [OwnerResourceID] => 29682e25

So if i want to reference Account name:
$final = $result->queryResult->EntityResults->Entity;

foreach ($final as $account) {
   print_r($account->AccountName . "\n");
}


This above, gets *Notice*: Trying to get property of non-object

Sorry to keep bothering you.

**Comment by reynolek** [comment]
No problem.

What happens if you just `print_r($account)` and what happens if you `print_r($result->queryResult->entityResults)`?

In all the code that we use at OpenDNS, the following is how we loop over results (spoiler, it looks almost exactly like yours, minus some variables):
```php
foreach ($queryResponse->queryResult->EntityResults->Entity as $worktype) {
    // do stuff
}
```

**Comment by Capmouda** [comment]
for  print_r($result->queryResult->EntityResults)

ATWS\AutotaskObjects\ArrayOfEntity Object ( [Entity] =>
ATWS\AutotaskObjects\Account Object ( [AccountName] => NYClient1 [AccountType]
=> 1 [OwnerResourceID] =>....

for print_r($account)
NYClient1129682885(211) 704-03191224 east .....

**Comment by reynolek** [comment]
Ohh I see whats happening -- Your query request is only returning 1 result. When this happens, your loop actually goes over each value in the account instead of over an array of accounts. I hate this part of Autotask's API.

Try this: `var_dump($final->AccountName)`

**Comment by Capmouda** [comment]
OK great, Vardump returns string(21) "NYClient1" and Echo returns NYClient1
- which is good.
Now my last question. can this be treated as an array in a while loop?
does the API support POST?

Thank you so much for your help.

**Comment by reynolek** [comment]
There isn't a way to treat an object as an array. Simply just grab the info you want (i.e. `$final->AccountName`) and assign it to whatever variables you want -- and honestly with this request you dont even need a loop since its only returning 1 value.

The API supports everything, you can get an idea of what you can do by looking in the source code: https://github.com/opendns/autotask-php/blob/master/src/Client.php#L145

**Comment by Capmouda** [comment]
Thanks.
I am not sure if i am hitting walls here. but if i want to list accounts -
(about 15) .
used Expression (addExpression('isnotnull','');

The results are in an array:

Array ( [0] => ATWS\AutotaskObjects\Account Object ( [AccountName] => ......

how do you reference AccountName for instance.

**Comment by reynolek** [comment]
In the event that it is an array, then you can just loop over it with a foreach loop, and get access to the data like you were before.

```php
foreach ($accounts as $account) {
    var_dump($account->AccountName);
}
```
