### ISSUE TITLE
How do I get the XML call that I am sending to AT?

### ISSUE THREAD

**Issue by whatTool** [opendns/autotask-php#161]
Hello,

I am currently in contact with AT Support about the Contracts I am creating using this wrapper for their API.

A month after the contract creation date, all services gets 100% discount and I can't remove the discount.

So the AT Support is asking for the XML calls I am sending to their end.

The calls I am sending is creating a contract on a account and then giving that account a service.

Here is my code for making the contract:
```php
$accountQuery = new ATWS\AutotaskObjects\Query('Account');

$accountQueryField = new ATWS\AutotaskObjects\QueryField('id');
$accountQueryField->addExpression('Equals', $id);
$accountQuery->addField($accountQueryField);

$accountQueryResponse = $client->query($accountQuery);
$account = $accountQueryResponse->queryResult->EntityResults->Entity;

$endDate = new DateTime();
$endDate->modify("+1 year");
$startDate = new DateTime();

// Create it
$createContractQuery = new ATWS\AutotaskObjects\Contract();

// Required fields
$createContractQuery->AccountID = $account->id;
$createContractQuery->BillingPreference = 2;
$createContractQuery->ContractName = $account->AccountName . " Hosted Services";
$createContractQuery->ContractType = 7;
$createContractQuery->EndDate = $endDate->format("Y-12-31 23:59:59");
$createContractQuery->id = 0;
$createContractQuery->StartDate = $startDate->format("Y-m-d H:i:s");
$createContractQuery->Status = 1;
$createContractQuery->TimeReportingRequiresStartAndStopTimes = 1;
$createContractQuery->ContractPeriodType = "m";
$createContractQuery->SetupFee = 0.00;

// Optional fields
$createContractQuery->ContractCategory = 6;

$client->create($createContractQuery);
```

However when I add the `->asXml()` to either
`$createContractQuery`
`$client->create($createContractQuery)`

I get this error:
`Fatal error:  Uncaught Error: Call to undefined method ATWS\AutotaskObjects\Contract::asXml()`
`Fatal error:  Uncaught Error: Call to undefined method ATWS\AutotaskObjects\CreateResponse::asXml()`

The same happens when I make a Contract Service Adjustment.

P.S. I am using their 1.5 version (Have been told to upgrade to 1.6, but don't have the time atm, so the help I need is for 1.5)

Thank you for your help :)

**Comment by whatTool** [comment]
Thanks for the quick response.

Does the `$client` get my last request from AT or what?

Otherwise I would end up with 2 contracts with the name, if I have to both create the contract and use `$client->__getlastRequest()` in one go.

**Comment by SirPoot-** [comment]
@whatTool Negative. The client class extends the native soap class within PHP thus you are in fact see what was the last request from your PHP soap class. It is not possible to see the last requests from Autotask.

True about the duplicate contracts, but you can delete the one you do not want from the UI.

Save the newly created contract information from Autotask.
`
$result = $client->create($createContractQuery);
`

See the last soap request your client sent.
`
print_r($client->__getlastRequest());
`

**Comment by whatTool** [comment]
Thank you for the help, @SirPoot- 

Would you mind checking first if this is the correct output?
I know next to nothing about XML.

```xml
<!--?xml version="1.0" encoding="UTF-8"?-->
<soap-env:envelope xmlns:soap-env="http://schemas.xmlsoap.org/soap/envelope/" xmlns:ns1="http://autotask.net/ATWS/v1_5/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	<soap-env:body>
		<ns1:create>
			<ns1:entities>
				<ns1:entity xsi:type="ns1:Contract">
					<ns1:id>0</ns1:id>
					<ns1:accountid>1234</ns1:accountid>
					<ns1:billingpreference>2</ns1:billingpreference>
					<ns1:contractcategory>6</ns1:contractcategory>
					<ns1:contractname>Hosted Services - Test</ns1:contractname>
					<ns1:contractperiodtype>m</ns1:contractperiodtype>
					<ns1:contracttype>7</ns1:contracttype>
					<ns1:enddate>2021-12-31 23:59:59</ns1:enddate>
					<ns1:setupfee>0</ns1:setupfee>
					<ns1:startdate>2020-04-17 07:53:12</ns1:startdate>
					<ns1:status>1</ns1:status>
			                <ns1:timereportingrequiresstartandstoptimes>1</ns1:timereportingrequiresstartandstoptimes>
				</ns1:entity>
			</ns1:entities>
		</ns1:create>
	</soap-env:body>
</soap-env:envelope>
```
