### ISSUE TITLE
Edit a ticket - type conversion error

### ISSUE THREAD

**Issue by networkmotioncw** [opendns/autotask-php#162]
I'm hitting an error which I cannot figure out. Hoping somebody can point me in the right direction.

I successfully create a ticket. The dump of the object is in the image attachment "created ticket dump".

I then have a method which takes the ticket object using a query. It changes the status field of that object to 19 (Customer Note Added in our implentation). It then passes that object back using the update() method. This method is in the image attachment "code dump".

When this method is run, it fails. I took a dump of the object just before passing it to the update() method to show exactly what is being passed. This can be seen in the image attachment "edit ticket dump".

The result, showing the error, can be seen in the image attachment "result dump". It's also pasted below:
+Errors: ATWS\AutotaskObjects\ArrayOfATWSError {#627 ▼
      +ATWSError: array:2 [▼
        0 => ATWS\AutotaskObjects\ATWSError {#624 ▼
          +Message: "Conversion from type 'Object' to type 'String' is not valid."
        }
        1 => ATWS\AutotaskObjects\ATWSError {#632 ▼
          +Message: "Error updating entity for record number [1]."
        }

The only difference that I can see are the last two (edit ticket dump), also pasted below:
  +UserDefinedFields: ATWS\AutotaskObjects\ArrayOfUserDefinedField {#628 ▶}
  +"LastTrackedModificationDateTime": "2020-05-06T10:37:28.04"

Can anybody explain what error this is and what I may be able to do to resolve it please?

Thanks,
Chris.

**RESULT DUMP**
![result dump](https://user-images.githubusercontent.com/38970486/81191156-9c72b280-8fb0-11ea-9236-05d6c88a2054.png)

**CODE DUMP**
![code dump](https://user-images.githubusercontent.com/38970486/81191165-9f6da300-8fb0-11ea-8a2b-abc9eed28963.png)

**CREATED TICKET DUMP**
![created ticket dump](https://user-images.githubusercontent.com/38970486/81191166-a0063980-8fb0-11ea-801f-35160d9ae036.png)

**EDIT TICKET DUMP**
![edit ticket dump](https://user-images.githubusercontent.com/38970486/81191168-a09ed000-8fb0-11ea-8b4f-293b462311e9.png)

**Comment by SirPoot-** [comment]
@chrisnetworkmotion Autotask does require the entire object to be sent for the update. It is probably the UserDefinedFields. The same error will be thrown if there is a field with a blank space in any other field.

I pass the Entity through the following function 'unsetEmptyEntityValues' to clean the object prior to sending to Autotask.

```php
    /**
     * Clears empty fields on the Autotask Entity.
     * Resolves Autotask Create/Update Issue - Conversion from type 'Object' to type 'String' is not valid
     *
     * @param Entity $entity
     * @return Entity
     */
    private function unsetEmptyEntityValues(Entity $entity): Entity
    {
        foreach ($entity as $key => $value) {
            $value = trim($value);

            if ($value === '' || $value === ' ' || $value === null) {
                unset($entity->$key);
            }
        }

        if (isset($entity->UserDefinedFields)) {
            if (isset($entity->UserDefinedFields) &&
                is_null($entity->UserDefinedFields)) {
                unset($entity->UserDefinedFields);
            }

            if (isset($entity->UserDefinedFields->UserDefinedField) &&
                is_null($entity->UserDefinedFields->UserDefinedField)) {
                unset($entity->UserDefinedFields);
            }
        }

        return $entity;
    }


```

Also keep in mind of the native SOAP client functions '__getLastRequest()' and '__getLastResponse()' for troubleshooting.

`
$this->client->__getLastRequest();
`
`
$this->client->__getLastResponse();
`

Let me know the results.

**Comment by chrisnetworkmotion** [comment]
@SirPoot- Thanks for the reply there - it's much appreciated.  

I'm getting an error which after spending some time troubleshooting, still cannot figure out. I know it's simply a lack of understanding. The error message & a couple of screenshots are below. 

As far as I'm aware, I was taking the entire Ticket object via a query, changing the status, and then passing that entire Ticket object back into the update() method. I'm now pushing that entire Ticket object through your function before passing it through to update(). I've set the script to break at the dd($update) line


![entity error](https://user-images.githubusercontent.com/38970486/81269779-bc9e8200-9041-11ea-9f60-d133d7a60d66.png)


![entity message](https://user-images.githubusercontent.com/38970486/81269777-bc05eb80-9041-11ea-8567-a212026941f9.png)

**Comment by SirPoot-** [comment]
The TypeHint for Entity needs to Reference \ATWS\AutotaskObjects\Entity which you can import via a use statement or update the function to the following.

```
    /**
     * Clears empty fields on the Autotask Entity.
     * Resolves Autotask Create/Update Issue - Conversion from type 'Object' to type 'String' is not valid
     *
     * @param Entity $entity
     * @return Entity
     */
    private function unsetEmptyEntityValues(\ATWS\AutotaskObjects\Entity $entity): Entity
    {
        foreach ($entity as $key => $value) {
            $value = trim($value);

            if ($value === '' || $value === ' ' || $value === null) {
                unset($entity->$key);
            }
        }

        if (isset($entity->UserDefinedFields)) {
            if (isset($entity->UserDefinedFields) &&
                is_null($entity->UserDefinedFields)) {
                unset($entity->UserDefinedFields);
            }

            if (isset($entity->UserDefinedFields->UserDefinedField) &&
                is_null($entity->UserDefinedFields->UserDefinedField)) {
                unset($entity->UserDefinedFields);
            }
        }

        return $entity;
    }
```

**Comment by chrisnetworkmotion** [comment]
Apologies for not replying, I missed the email notification when this issue was updated. I'll check this out tomorrow, but the code update is really appreciated - thanks.
