### ISSUE TITLE
Simple way to 'get all'

### ISSUE THREAD

**Issue by davehamer** [opendns/autotask-php#164]
Afternoon,

When I started using this wrapper a few months ago, I received an error if I didn't try to set any query parameters - so since then I've always queried SOMETHING in order to get a result.

Example: To get all Services - I use QueryField(id) and addExpression(notequal, 0). Just in case there is a service with an id of 0 it'd be nice to not use this to 'Get all' results. 

Officially in SQL this would be 'where 1' but the whole XML querying is a bit confusing!

Is there a better way to do this that I'm missing?

TIA, Dave

**Comment by SirPoot-** [comment]
You are not missing anything. 

This is why I made my own wrapper for this to implement higher order functions.

**Comment by aidan-casey** [comment]
Part of the problem with a Get All type of request is simply that it is not supported by Autotask. To your concern above, I think you could just add the exist expression to the ID field.
