### ISSUE TITLE
Unable to Query with Multiple UDF Fields

### ISSUE THREAD

**Issue by JoshNW** [opendns/autotask-php#165]
I am currently attempting to look for tickets with Multiple Query fields. 

As soon as I perform a query with multiple UDF fields included, I get no results, despite there being multiple tickets that meet that criteria, and the filters working independently. 

```
//Ticket Details
	//Start ticket Query
 		$query = new ATWS\AutotaskObjects\Query('ticket');
			$Field = new ATWS\AutotaskObjects\QueryField('Install Outcome', True);
			$Field->addExpression('Equals', "Successful");
			$query->addField($Field);    
  			$Field = new ATWS\AutotaskObjects\QueryField('Actual Install Date', True);
			$Field->addExpression('isnotnull','');
			$query->addField($Field); 
 			$Field = new ATWS\AutotaskObjects\QueryField('Service Number', True);
			$Field->addExpression('isnotnull','');
			$query->addField($Field);  
	//End Autotask Query


	//Defines Output Variable 
	$TicketEntity = $client->query($query)->queryResult->EntityResults->Entity;
	
	Print_r($TicketEntity);
```

I have tested all fields independently and they do work. I have also tested them in combination with non-UDF fields, and I can add as many non-UDFs as I want without a problem, however, as soon as the second UDF is added, my results go away. 

Here are the important bits from one response from a live ticket that meets all the criteria above, but does not show up when any two of those filters are used together: 

```
[35] => ATWS\AutotaskObjects\UserDefinedField Object
  | (
  | [Name] => Actual Install Date
  | [Value] => 05/12/2020
  | )

[50] => ATWS\AutotaskObjects\UserDefinedField Object
  | (
  | [Name] => Install Outcome
  | [Value] => Successful
  | )

[55] => ATWS\AutotaskObjects\UserDefinedField Object
  | (
  | [Name] => Service Number
  | [Value] => applesauce
  | )
```

Edit: Fixed Formatting

**Comment by JoshNW** [comment]
changed the code to print errors and got this one: 


```
[ATWSError] => ATWS\AutotaskObjects\ATWSError Object

  | (
  | [Message] => QueryXML contains more than 1 UDF Field.
  | )

```

Is this a stated limitation that I missed?

**Comment by JoshNW** [comment]
I am going to close this one, I found the answer on page 902 of [Autotask's API documentation](https://ww14.autotask.net/help/Content/LinkedDOCUMENTS/WSAPI/T_WebServicesAPIv1_6.pdf). 

"To specify that a field is a UDF, you must add udf="true" within the field tag. You can only specify one UDF field per query."

ba humbug.

**Comment by SirPoot-** [comment]
@JoshNW very ba humbug.

If you create an idea on the Autotask help site or fond one, please post it here and i will up vote it.

I would really enjoy this feature.

**Comment by JoshNW** [comment]
@SirPoot- Here you go. [Autotask Ideas Post](https://success.autotask.net/t5/Professional-Services-Automation/API-Query-with-Multiple-UDF-Fields/idi-p/65833#M29211)

**Comment by RileyCarney** [comment]
The Reddit Post as well, thanks guys!: 
https://www.reddit.com/r/Autotask/comments/gk18ir/api_query_multi_user_defined_fields_kudos_request/

**Comment by SirPoot-** [comment]
@RileyCarney Thanks for linking the reddit post. Trying to spread the word and get this implemented.
