### ISSUE TITLE
PHP Soap Error start today

### ISSUE THREAD

**Issue by mayokingcomics** [opendns/autotask-php#17]
PHP Fatal error:  SOAP-ERROR: Parsing Schema: unexpected <text> in sequence in /var/www/xxxxx/autotask/Client.php on line 128
PHP Fatal error:  Uncaught SoapFault exception: [WSDL] SOAP-ERROR: Parsing Schema: unexpected <text> in sequence in /var/www/xxxxx/autotask/Client.php:128
Stack trace:
#0 /var/www/xxxx/autotask/Client.php(128): SoapClient->SoapClient('https://webserv...', Array)
#1 /var/www/xxxxx/autotask/verify.php(21): ATWS\Client->__construct('https://webserv...', Array)
#2 {main}
  thrown in /var/www/xxxxx/autotask/Client.php on line 128

**Comment by mayokingcomics** [comment]
![image](https://cloud.githubusercontent.com/assets/8822666/11596307/58e9724c-9a82-11e5-9d5b-6418e332a50c.png)

**Comment by sulfurcode** [comment]
I'm also seeing this issue. Autotask did update their API yesterday with a few changes that shouldn't impact this, obviously it has

**Comment by mayokingcomics** [comment]
Glad I am not alone, wondering how to fix it.

**Comment by sulfurcode** [comment]
@mayokingcomics what are you using as the wsdl address? the error seems to be when using https://webservices.autotask.net/atservices/1.5/atws.wsdl. Using another address such as https://webservices4.autotask.net/atservices/1.5/atws.wsdl works fine

**Comment by reynolek** [comment]
Weird. I haven't had a chance to look at this as I am in training this week. I don't think we have seen any issues, or at least not that I have seen in our monitoring. 

Will look into it when I can.

**Comment by sulfurcode** [comment]
I'm pretty certain it's an API bug on Autotasks end. I've submitted a support call with them

**Comment by mayokingcomics** [comment]
great fix for webservices4, changing all my stuff now

**Comment by reynolek** [comment]
@sulfurcode any response from autotask?

**Comment by sulfurcode** [comment]
@reynolek no, but it appears that it's fixed now.

**Comment by reynolek** [comment]
Alright -- closing. If it starts happening again, feel free to reopen.
