### ISSUE TITLE
Slow quries

### ISSUE THREAD

**Issue by Capmouda** [opendns/autotask-php#18]
Is there a reason the queries are running so slow. it takes about a minute for the results to load.

**Comment by reynolek** [comment]
Query speed is due to autotask, not the client. Perhaps they are having some performance issues.

**Comment by reynolek** [comment]
Oh I should also mention, you may be requesting a lot of data, and could improve load times by doing pagination -- but since autotask does pagination automatically (capped at 500 per query), the likelihood of it being an autotask issue is higher.

**Comment by sulfurcode** [comment]
We've not seen a performance drop in the API queries. Bare in mind that there is a threshold on API calls and anything over a certain threshold will result in an overhead benign added, usually approx 1 second per call.

**Comment by Capmouda** [comment]
All the queries we run are less than 500.

One page we run multiple queries to get a single account's related
information. Like contacts, notes and tickets.

I though it would be an issue. But after excluding the tickets and
contacts. The speed is still the same.

**Comment by Capmouda** [comment]
Anyone experiencing the same issue?

**Comment by Capmouda** [comment]
My page is now up to 4 minute of load time. :(
Loading 1 account information that contains:
40 tickets, 2 notes, 6 contacts.

Is this normal?

**Comment by mayokingcomics** [comment]
try some pings to their server.

my request are also slow but its like 20-30 seconds each query

**Comment by sulfurcode** [comment]
That's definitely not normal. Just queried 60 accounts, 90 contacts, 30 resources and 15 tickets, all came back in less than 20 seconds

**Comment by reynolek** [comment]
Yeah that query time seems way too long. 

One idea off the top of my head:

Are you using 1 client instance or multiple client instances?

You should aim for using 1 so that you just have to auth once.

**Comment by Capmouda** [comment]
I am calling multiple clients on each function. I created a start.php function as follows: - same issue.
```
 function start(){

$username = 'username';

password = 'password';

$authWsdl = 'https://webservices4.autotask.net/atservices/1.5/atws.wsdl';

$opts = array('trace' => 1);

$client = new ATWS\Client($authWsdl, $opts);

$zoneInfo = $client->getZoneInfo($username);



		$authOpts = array(
		    'login' => $username,
		    'password' => $password,
		    'trace' => 1,   
		);
		$wsdl = str_replace('.asmx', '.wsdl', $zoneInfo->getZoneInfoResult->URL);
		$client = new ATWS\Client($wsdl, $authOpts);
}
```
and in the function to list Accounts for example:
```
function list_accounts(){
$client = start();
		$query = new ATWS\AutotaskObjects\Query('Account');
....
}
```
function to list contacts
```
function list_contacts(){
$client = start();
		$query = new ATWS\AutotaskObjects\Query('Contacts');
....
}
```

**Comment by reynolek** [comment]
@Capmouda you are going to not want to instantiate multiple clients. The reason being is that you have to Auth *every* time, which doubles your requests to the API.

You should make the `$client` a global variable, and only auth once.

**Comment by reynolek** [comment]
has reducing the number of times you auth a client decreased your load time @Capmouda?

**Comment by Capmouda** [comment]
@reynolek  Thanks for checking in. It definitely decreased the load time but not the best. it still takes about 40 seconds now. even with multiple filters in place (only open tickets)..

**Comment by SirPoot-** [comment]
@reynolek close request

**Comment by CSUM-SANTHOSH** [comment]
can u share the sample here how u got it fixed so it will be easy for us to understand it better
