### ISSUE TITLE
Advanced queries

### ISSUE THREAD

**Issue by rimsky82** [opendns/autotask-php#19]
Maybe this is a limitation of the AutoTask API, but is there no way to pull data from multiple entities with one query such as by joining tables?  I want to pull invoices complete with customer information and billing items, but I'm guessing I'll have to find a creative way to get all the information within a few calls instead of only one.

**Comment by sulfurcode** [comment]
Sadly you can't. If you want to do this regularly id suggest that you cache the information and just query the changes

**Comment by reynolek** [comment]
Yup, API limitation as @sulfurcode mentioned.
