### ISSUE TITLE
Showing selected columns only

### ISSUE THREAD

**Issue by timo0060** [opendns/autotask-php#27]
So I've stumbled upon this on my quest to get all the phone numbers from clients from autotask for a new internal phone system.  So I've included the autoload.php file, I've run the tested code and it does print out all the contacts who's first name is Steve. Now how would I pull just the First name, Last name, and Phone number from all this information? Any help would be great, even just a reference to a resource would be loved. 

P.S. Love this little library you made, so simple and easier to get up and running.

**Comment by reynolek** [comment]
I'm assuming since you closed this that you figured it out. Feel free to open another one if you get stuck.

**Comment by timo0060** [comment]
Found fix in a different issue (Issue #16), but now if I try to run the statement without the $firstnameField portion (doing the query without any added field), I get no records back when I print_r() the query.

**Comment by reynolek** [comment]
I am not at a place where I can easily test code out, but as a hack, you can try doing a `QueryField` of `AccountID` > 0 -- This will return all contacts *except* those assigned to your AutoTask account (if you want yours as well, do `AccountID` >= 0)

**Comment by timo0060** [comment]
So I'm not sure how the syntax is supposed to go for the argument, here is what I have, which doesn't work.

    $accountId = new ATWS\AutotaskObjects\QueryField('accountId');
    $accountId->addExpression('>=', 0);

    $query->addField($accountId);

**Comment by reynolek** [comment]
Right sorry I wasn't specific on that -- you will have to do `$accountId->addExpression('GreaterThanorEquals', 0);`

**Comment by timo0060** [comment]
Ok, so I found the file that lists all of the conditions for the expressions, which is what I was looking form. So, my problem is fixed.

**Comment by timo0060** [comment]
I just have one more question before I close this. Is there a sort alphabetically expression? So then I can sort all the contacts by first name in descending order?

**Comment by reynolek** [comment]
I have never seen a way to do it unfortunately.

Also a reminder that autotask limits all results to 500 max, so if you have more than 500 contacts you will have to make multiple queries.

**Comment by timo0060** [comment]
Ok, thank you for letting me know. How would I divide the query up? So in the event I do have more then 500 clients, would that just be as simple as taking the last accountID and doing another query for user accounts greater than the last accountID?

**Comment by reynolek** [comment]
I dont have the code in front of me, but I remember doing limits and offsets, i'd have to get back to you on how to do that (unless someone else knows exactly how to do it).

**Comment by timo0060** [comment]
Well in that case I'll wait till you are available to post the code for limits and offsets. I'm not in a huge rush, so I'll just style the data I have now and put it into a pretty bootstrap table while I wait.

**Comment by reynolek** [comment]
So it looks like I solved our problem a different way, and I didn't use another query. From the [Autotask API Docs](https://support.netserve365.com/help/Content/Userguides/T_WebServicesAPIv1_5.pdf) I found this rather lame requirement for you to get the next 500 results

> NOTE: query() will return a maximum of 500 records at once, sorted by their id value.
> To query records over the 500 maximum for a given set of search criteria, repeat the query
> and filter by id value > the previous maximum id value retrieved.

**Comment by timo0060** [comment]
So it's just as simple as getting the last id returned, and then running the query again with a filter on the id value. Sounds simple. Thanks for your help! I will now close this issue.
