### ISSUE TITLE
Searching Accounts by Phone

### ISSUE THREAD

**Issue by timo0060** [opendns/autotask-php#28]
Hello again!

I'm encountering a problem that when I enter a phone number into a form and submit it, the query doesn't return anything, no results will be found, as my foreach loop just errors. Although, if I enter just the area code "123", I get all the accounts that have a phone number that contain "123". If I try this format "123-456", I still get results back. I also get results back for the following phone formats; "123-456-7" and "123-456-78". However, if I enter a number that's "123-456-789" or "123-456-7890", I'll get the following error when I do my foreach loop, "Trying to get property of non-object in C:\wamp\www\Autotask\myFile.php on line 39".

Below is the code:

    $query = new ATWS\AutotaskObjects\Query('Account');
    $phone = new ATWS\AutotaskObjects\QueryField('phone');
    $phone->addExpression('contains', $phoneNum);

    $query->addField($phone);
   

    $results = $client->query($query);
    
    foreach($results->queryResult->EntityResults->Entity as $account){
        echo $account->AccountName."<br>";
    }

$phoneNum gets it's value from a $_GET[''] request at the top of the page.

But here's the real kicker, while I can't get results back from "123-456-7890", I get results back from "123-654-9870". It seems to be the only one that works, no other numbers out of my list that I have tried, worked.

I need to be able to search through phone numbers to get account ID's so I can get tickets related to that account ID.

Thanks for your help, again.

**Comment by reynolek** [comment]
If you `print_r` the entire response, there's usually an error code at the end, or at the very least you can see the true result instead of just the account name.

**Comment by timo0060** [comment]
So, upon doing a `print_r($results)`, I see that it does indeed return an object. So looks like my main problem has been fixed. Is there a way to count how many objects are returned? So if there are multiple I can handle it differently form a single return?

**Comment by reynolek** [comment]
yeah that was what I was thinking was happening on the result. You should be able to do a `count($results->queryResult->EntityResults)` I believe.

**Comment by timo0060** [comment]
Yes, that's perfect! You sir are most helpful. I will now close this issue.
