### ISSUE TITLE
Can't find relation between Accounts and Tickets

### ISSUE THREAD

**Issue by timo0060** [opendns/autotask-php#29]
Hello, really sorry to bug you guys again, but I can't seem to find the relationship between an Account and a Ticket. I thought it was a `ParentAccountID = AccountID`, where `ParentAccountID` was in the Account object and `AccountID` was in the Ticket object. It worked at first, but then I found out that not all Account objects have a `ParentAccountID` field. So is there a better link between an Account and it's ticket? Or is there just a more efficient way of getting all the tickets related to an Account without doing another query?

**Comment by reynolek** [comment]
Use the `ID` field on the Account object, and the `AccountID` ffield on the Ticket object.

**Comment by timo0060** [comment]
Thank you very much.
