### ISSUE TITLE
Missing CreateAttachment

### ISSUE THREAD

**Issue by mikebranham** [opendns/autotask-php#3]
The API for CreateAttachment (as well as the other attachment calls) seems to be missing in the client.

**Comment by kleijnweb** [comment]
I'm having the exact same issue.

```xml
<?xml version="1.0" encoding="UTF-8"?>
<SOAP-ENV:Envelope xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/" xmlns:ns1="http://autotask.net/ATWS/v1_5/">
   <SOAP-ENV:Body>
      <ns1:CreateAttachment>
         <ns1:attachment>
            <ns1:Data>ZGdmaGprbA==</ns1:Data>
            <ns1:Info>
               <ns1:id>0</ns1:id>
               <ns1:ParentID>45078</ns1:ParentID>
               <ns1:ParentType>Ticket</ns1:ParentType>
               <ns1:Type>1</ns1:Type>
               <ns1:Title>SoapMapper\Client\AttachmentTest::canCreateAttachmentOnTicket</ns1:Title>
               <ns1:FullPath>/foo/bar</ns1:FullPath>
               <ns1:Publish>1</ns1:Publish>
            </ns1:Info>
         </ns1:attachment>
      </ns1:CreateAttachment>
   </SOAP-ENV:Body>
</SOAP-ENV:Envelope>
```
Result:

     SoapFault: System.Web.Services.Protocols.SoapException: Conversion from type 'XmlNode()' to type 'String' is not valid.
        at autotask.web.services.API.ATWSProcessor.CreateAttachment(Attachment attachment)
        at autotask.web.services.API.v1_5.ATWS.CreateAttachment(Attachment attachment)

**Comment by reynolek** [comment]
Unfortunately I dont have a good answer for you @kleijnweb. @mikebranham got his working, perhaps he can share his experience to get you moving forward.

**Comment by mikebranham** [comment]
Hi Eric,

I got this from our internal team, who did the implementation.  Note that because of namespace issues, we had to modify the client a bit (attached).  Probably not the best way to have done it, but we are in a time crunch (aren’t we all).

Hope this helps

-Mike

Upload File :
<?
require_once 'src/autoload.php';

use \ATWS;
use \ATWS\AutotaskObjects;
$username           = **************';
$password           = '************';
$postAuthOpts = array(
   'login' => $username,
    'password' => $password,
    'trace' => 1,   // Allows us to debug by getting the XML requests sent
);
$opts = array('trace' => 1);
$authWsdl = 'https://webservices1.autotask.net/atservices/1.5/atws.wsdl';
$c = new ATWS\Client($authWsdl, $opts);
$zoneInfo = $c->getZoneInfo($username);
$wsdl = str_replace('.asmx', '.wsdl', $zoneInfo->getZoneInfoResult->URL);
$c = new ATWS\Client($wsdl, $postAuthOpts);
$attachment = new AutotaskObjects\Attachment();
$attachmentInfo = new AutotaskObjects\AttachmentInfo();
$attachmentInfo->FullPath = 'my.txt';
$attachmentInfo->ParentID = xxxx;                     <---------------------------------------------------  Parent Id ticket or note
$attachmentInfo->Publish = 1;       // to all users
$attachmentInfo->ParentType = 4;    // This is a ticket
$attachmentInfo->Type = 'FILE_ATTACHMENT';          // A file
$attachmentInfo->Title = "Test Attachment";
$attachmentInfo->id = 0;
$attachmentInfo->AttachDate = date("m/d/Y", mktime(0, 0, 0, date("m"), date("d"), date("Y"))); // today
$attachment->Data = file_get_contents('blah.txt');
$attachment->Info = $attachmentInfo;
$c->CreateAttachment($attachment);
print_r($c);        // All information include the new ID file
?>


Download File :
<?
require_once 'src/autoload.php';

use \ATWS;
use \ATWS\AutotaskObjects;
$username           = **************';
$password           = '************';
$postAuthOpts = array(
   'login' => $username,
    'password' => $password,
    'trace' => 1,   // Allows us to debug by getting the XML requests sent
);
$opts = array('trace' => 1);
$authWsdl = 'https://webservices1.autotask.net/atservices/1.5/atws.wsdl';
$c = new ATWS\Client($authWsdl, $opts);
$zoneInfo = $c->getZoneInfo($username);
$wsdl = str_replace('.asmx', '.wsdl', $zoneInfo->getZoneInfoResult->URL);
$c = new ATWS\Client($wsdl, $postAuthOpts);
$attachment = new AutotaskObjects\Attachment();
$attachmentInfo = new AutotaskObjects\AttachmentInfo();
$attachmentInfo->ID =xxxx ;                                     <---------------------------------------------------    file id you need to download
$attachment->Data = ‘’;
$attachment->Info = $attachmentInfo;
$c->GetAttachment ($attachment);
$entity = $ary->GetAttachmentResult;
print_r($entity);  // All information that you need to update Header Page
?>

**Comment by mikebranham** [comment]
And the client code.

<?php
namespace ATWS;
use \ATWS\AutotaskObjects;

class AutotaskClient extends \SoapClient
{
    protected $attachparams;
    protected $params;

    public static $classMap = array(
        'Account'                           => 'ATWS\AutotaskObjects\Account',
        'AccountLocation'                   => 'ATWS\AutotaskObjects\AccountLocation',
        'AccountNote'                       => 'ATWS\AutotaskObjects\AccountNote',
        'AccountTeam'                       => 'ATWS\AutotaskObjects\AccountTeam',
        'AccountToDo'                       => 'ATWS\AutotaskObjects\AccountToDo',
        'ActionType'                        => 'ATWS\AutotaskObjects\ActionType',
        'AdditionalInvoiceFieldValue'       => 'ATWS\AutotaskObjects\AdditionalInvoiceFieldValue',
        'AllocationCode'                    => 'ATWS\AutotaskObjects\AllocationCode',
        'Appointment'                       => 'ATWS\AutotaskObjects\Appointment',
        'ArrayOfATWSError'                  => 'ATWS\AutotaskObjects\ArrayOfATWSError',
        'ArrayOfEntity'                     => 'ATWS\AutotaskObjects\ArrayOfEntity',
        'ArrayOfEntityInfo'                 => 'ATWS\AutotaskObjects\ArrayOfEntityInfo',
        'ArrayOfEntityReturnInfo'           => 'ATWS\AutotaskObjects\ArrayOfEntityReturnInfo',
        'ArrayOfField'                      => 'ATWS\AutotaskObjects\ArrayOfField',
        'ArrayOfPickListValue'              => 'ATWS\AutotaskObjects\ArrayOfPickListValue',
        'ArrayOfUserDefinedField'           => 'ATWS\AutotaskObjects\ArrayOfUserDefinedField',
        'Attachment'                        => 'ATWS\AutotaskObjects\Attachment',
        'AttachmentInfo'                    => 'ATWS\AutotaskObjects\AttachmentInfo',
        'ATWSError'                         => 'ATWS\AutotaskObjects\ATWSError',
        'ATWSResponse'                      => 'ATWS\AutotaskObjects\ATWSResponse',
        'ATWSZoneInfo'                      => 'ATWS\AutotaskObjects\ATWSZoneInfo',
        'AutotaskIntegrations'              => 'ATWS\AutotaskObjects\AutotaskIntegrations',
        'BillingItem'                       => 'ATWS\AutotaskObjects\BillingItem',
        'BillingItemApprovalLevel'          => 'ATWS\AutotaskObjects\BillingItemApprovalLevel',
        'ChangeRequestLink'                 => 'ATWS\AutotaskObjects\ChangeRequestLink',
        'ClientPortalUser'                  => 'ATWS\AutotaskObjects\ClientPortalUser',
        'Contact'                           => 'ATWS\AutotaskObjects\Contact',
        'Contract'                          => 'ATWS\AutotaskObjects\Contract',
       'ContractBlock'                     => 'ATWS\AutotaskObjects\ContractBlock',
        'ContractCost'                      => 'ATWS\AutotaskObjects\ContractCost',
        'ContractFactor'                    => 'ATWS\AutotaskObjects\ContractFactor',
        'ContractMilestone'                 => 'ATWS\AutotaskObjects\ContractMilestone',
        'ContractNote'                      => 'ATWS\AutotaskObjects\ContractNote',
        'ContractRate'                      => 'ATWS\AutotaskObjects\ContractRate',
       'ContractRetainer'                  => 'ATWS\AutotaskObjects\ContractRetainer',
        'ContractService'                   => 'ATWS\AutotaskObjects\ContractService',
        'ContractServiceAdjustment'         => 'ATWS\AutotaskObjects\ContractServiceAdjustment',
        'ContractServiceBundle'             => 'ATWS\AutotaskObjects\ContractServiceBundle',
        'ContractServiceBundleAdjustment'   => 'ATWS\AutotaskObjects\ContractServiceBundleAdjustment',
        'ContractServiceBundleUnit'         => 'ATWS\AutotaskObjects\ContractServiceBundleUnit',
        'ContractServiceUnit'               => 'ATWS\AutotaskObjects\ContractServiceUnit',
        'ContractTicketPurchase'            => 'ATWS\AutotaskObjects\ContractTicketPurchase',
        'Country'                           => 'ATWS\AutotaskObjects\Country',
        'CreateAttachment'                  => 'ATWS\AutotaskObjects\CreateAttachment',
        'CreateAttachmentResponse'          => 'ATWS\AutotaskObjects\CreateAttachmentResponse',
        'createResponse'                    => 'ATWS\AutotaskObjects\CreateResponse',
        'deleteResponse'                    => 'ATWS\AutotaskObjects\DeleteResponse',
        'Department'                        => 'ATWS\AutotaskObjects\Department',
        'Entity'                            => 'ATWS\AutotaskObjects\Entity',
        'EntityDuplicateStatus'             => 'ATWS\AutotaskObjects\EntityDuplicateStatus',
        'EntityInfo'                        => 'ATWS\AutotaskObjects\EntityInfo',
        'EntityReturnInfo'                  => 'ATWS\AutotaskObjects\EntityReturnInfo',
        'EntityReturnInfoDatabaseAction'    => 'ATWS\AutotaskObjects\EntityReturnInfoDatabaseAction',
        'ExpenseItem'                       => 'ATWS\AutotaskObjects\ExpenseItem',
        'ExpenseReport'                     => 'ATWS\AutotaskObjects\ExpenseReport',
        'GetAttachment'                     => 'ATWS\AutotaskObjects\GetAttachment',
        'GetAttachmentResult'               => 'ATWS\AutotaskObjects\GetAttachmentResult',
        'Field'                             => 'ATWS\AutotaskObjects\Field',
        'getUDFInfo'                        => 'ATWS\AutotaskObjects\UDFParam',
        'getUDFInfoResponse'                => 'ATWS\AutotaskObjects\UDFInfoResponse',
        'InstalledProduct'                  => 'ATWS\AutotaskObjects\InstalledProduct',
        'InternalLocation'                  => 'ATWS\AutotaskObjects\InternalLocation',
        'InventoryItem'                     => 'ATWS\AutotaskObjects\InventoryItem',
        'InventoryItemSerialNumber'         => 'ATWS\AutotaskObjects\InventoryItemSerialNumber',
        'InventoryLocation'                 => 'ATWS\AutotaskObjects\InventoryLocation',
        'InventoryTransfer'                 => 'ATWS\AutotaskObjects\InventoryTransfer',
        'Invoice'                           => 'ATWS\AutotaskObjects\Invoice',
        'InvoiceTemplate'                   => 'ATWS\AutotaskObjects\InvoiceTemplate',
        'Opportunity'                       => 'ATWS\AutotaskObjects\Opportunity',
        'PaymentTerm'                       => 'ATWS\AutotaskObjects\PaymentTerm',
        'Phase'                             => 'ATWS\AutotaskObjects\Phase',
        'PickListValue'                     => 'ATWS\AutotaskObjects\PickListValue',
        'Product'                           => 'ATWS\AutotaskObjects\Product',
        'ProductVendor'                     => 'ATWS\AutotaskObjects\ProductVendor',
        'Project'                           => 'ATWS\AutotaskObjects\Project',
        'ProjectCost'                       => 'ATWS\AutotaskObjects\ProjectCost',
        'ProjectNote'                       => 'ATWS\AutotaskObjects\ProjectNote',
        'PurchaseOrder'                     => 'ATWS\AutotaskObjects\PurchaseOrder',
        'PurchaseOrderItem'                 => 'ATWS\AutotaskObjects\PurchaseOrderItem',
        'PurchaseOrderReceive'              => 'ATWS\AutotaskObjects\PurchaseOrderReceive',
        'queryResponse'                     => 'ATWS\AutotaskObjects\QueryResponse',
        'Quote'                             => 'ATWS\AutotaskObjects\Quote',
        'QuoteItem'                         => 'ATWS\AutotaskObjects\QuoteItem',
        'QuoteLocation'                     => 'ATWS\AutotaskObjects\QuoteLocation',
        'Resource'                          => 'ATWS\AutotaskObjects\Resource',
        'ResourceRole'                      => 'ATWS\AutotaskObjects\ResourceRole',
        'Role'                              => 'ATWS\AutotaskObjects\Role',
        'SalesOrder'                        => 'ATWS\AutotaskObjects\SalesOrder',
        'Service'                           => 'ATWS\AutotaskObjects\Service',
        'ServiceBundle'                     => 'ATWS\AutotaskObjects\ServiceBundle',
        'ServiceBundleService'              => 'ATWS\AutotaskObjects\ServiceBundleService',
        'ServiceCall'                       => 'ATWS\AutotaskObjects\ServiceCall',
        'ServiceCallTask'                   => 'ATWS\AutotaskObjects\ServiceCallTask',
        'ServiceCallTaskResource'           => 'ATWS\AutotaskObjects\ServiceCallTaskResource',
        'ServiceCallTicket'                 => 'ATWS\AutotaskObjects\ServiceCallTicket',
        'ServiceCallTicketResource'         => 'ATWS\AutotaskObjects\ServiceCallTicketResource',
        'ShippingType'                      => 'ATWS\AutotaskObjects\ShippingType',
        'Task'                              => 'ATWS\AutotaskObjects\Task',
        'TaskNote'                          => 'ATWS\AutotaskObjects\TaskNote',
        'TaskPredecessor'                   => 'ATWS\AutotaskObjects\TaskPredecessor',
        'TaskSecondaryResource'             => 'ATWS\AutotaskObjects\TaskSecondaryResource',
        'Tax'                               => 'ATWS\AutotaskObjects\Tax',
        'TaxCategory'                       => 'ATWS\AutotaskObjects\TaxCategory',
        'TaxRegion'                         => 'ATWS\AutotaskObjects\TaxRegion',
        'Ticket'                            => 'ATWS\AutotaskObjects\Ticket',
        'TicketChangeRequestApproval'       => 'ATWS\AutotaskObjects\TicketChangeRequestApproval',
        'TicketCost'                        => 'ATWS\AutotaskObjects\TicketCost',
        'TicketNote'                        => 'ATWS\AutotaskObjects\TicketNote',
        'TicketSecondaryResource'           => 'ATWS\AutotaskObjects\TicketSecondaryResource',
        'TimeEntry'                         => 'ATWS\AutotaskObjects\TimeEntry',
        'UserDefinedField'                  => 'ATWS\AutotaskObjects\UserDefinedField',
        'UserDefinedFieldDefinition'        => 'ATWS\AutotaskObjects\UserDefinedFieldDefinition',
        'UserDefinedFieldListItem'          => 'ATWS\AutotaskObjects\UserDefinedFieldListItem',
    );

   // @codeCoverageIgnoreStart
    public function __construct($wsdl, $soapOpts = array())
    {
        foreach (static::$classMap as $external => $internal) {
            if (!isset($soapOpts['classmap'][$external])) {
                $soapOpts['classmap'][$external] = $internal;
            }
        }

        parent::__construct($wsdl, $soapOpts);
    }

    public function getZoneInfo($username)
    {
        $zoneInfoObject = new AutotaskObjects\ZoneInfo($username);
        return $this->_call('getZoneInfo', array($zoneInfoObject));
    }

    public function create(AutotaskObjects\Entity $obj)
    {
        $params = new AutotaskObjects\CreateParam($obj);
        return $this->_call('create', array($params));
    }

    public function update(AutotaskObjects\Entity $obj)
    {
        $params = new AutotaskObjects\UpdateParam($obj);
        return $this->_call('update', array($params));
    }

    public function delete(AutotaskObjects\Entity $obj)
    {
        $params = new AutotaskObjects\DeleteParam($obj);
        return $this->_call('delete', array($params));
    }


    public function CreateAttachment(AutotaskObjects\Entity $obj)
    {
        $params = new AutotaskObjects\CreateAttachment($obj);
        return $this->_call('CreateAttachment', array($params));
    }
    public function GetAttachment(AutotaskObjects\Entity $obj)
    {
        $params = new AutotaskObjects\GetAttachment($obj);
        return $this->_call('GetAttachment', array($params));
    }


    public function query(AutotaskObjects\Query $obj)
    {
        $obj->asXml();
        return $this->_call('query', array($obj));
    }

    public function getUDFInfo($type)
    {
        $param = new AutotaskObjects\UDFParam($type);
        return $this->_call('getUDFInfo', array($param));
    }

    public function getFieldInfo($type)
    {
        $fieldInfo = new AutotaskObjects\FieldInfo($type);
        return $this->_call('getFieldInfo', array($fieldInfo));
    }

    public function getEntityInfo()
    {
        return $this->_call('getEntityInfo');
    }

    public function getThresholdAndUsageInfo()
    {
        return $this->_call('getThresholdAndUsageInfo');
    }

    public function __doRequest($request, $location, $action, $version, $one_way = 1)
    {
        if ( strrpos($action,"CreateAttachment") ) $request = $this->UpdateCreateAttachmentXML($request);
        if ( strrpos($action,"GetAttachment") ) $request = $this->UpdateDownloadAttachmentXML($request);

        return parent::__doRequest($request, $location, $action, $version, $one_way);
    }

    private function _call($method, $params = array())
    {
        $results=array();

        if ( in_array($method,array("CreateAttachment","GetAttachment") ) ) $this->attachparams=$params;
        else $this->params=$params;

        try {
               $results=$this->__soapCall($method, $params);
         } catch ( \Exception $e) {
              $this->ErrorSoapServer($e);
         }

        return  $results;
    }



    private function UpdateCreateAttachmentXML($request) {
        $attachinfo=$this->attachparams[0]->attachment;
        $newrequest='<?xml version="1.0" encoding="utf-8"?>
        <soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
          <soap:Body>
            <CreateAttachment xmlns="http://autotask.net/ATWS/v1_5/">
              <attachment>
                <Data>#Data#</Data>
                <Info>
                  <id xsi:type="xsd:string">#id#</id>
                  <AttachDate xsi:type="xsd:string">#AttachDate#</AttachDate>
                  <AttachedByContactID xsi:type="xsd:string">#AttachedByContactID#</AttachedByContactID>
                  <ParentID xsi:type="xsd:string">#ParentID#</ParentID>
                  <FileSize xsi:type="xsd:string">#FileSize#</FileSize>
                  <ParentType xsi:type="xsd:string">#ParentType#</ParentType>
                  <Type xsi:type="xsd:string">#Type#</Type>
                  <Title xsi:type="xsd:string">#Title#</Title>
                  <FullPath xsi:type="xsd:string">#FullPath#</FullPath>
                  <Publish xsi:type="xsd:string">#Publish#</Publish>
                </Info>
              </attachment>
            </CreateAttachment>
          </soap:Body>
        </soap:Envelope>';

        foreach ((array)$attachinfo->Info as $key => $val) $newrequest=str_replace("#".$key."#" ,$val,$newrequest);

        $newrequest=str_replace("#Data#" ,  base64_encode($attachinfo->Data),$newrequest);

    return $newrequest;
    }


    private function UpdateDownloadAttachmentXML($request) {

        $attachinfo=$this->attachparams[0]->attachmentId;
        $newrequest='<?xml version="1.0" encoding="utf-8"?>
           <soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
            <soap:Body>
                <GetAttachment xmlns="http://autotask.net/ATWS/v1_5/">
                    <attachmentId xsi:type="xsd:string">#id#</attachmentId>
                </GetAttachment>
            </soap:Body>
           </soap:Envelope>';
        foreach ((array)$attachinfo->Info as $key => $val)
            $newrequest=str_replace("#".$key."#" ,$val,$newrequest);

      return $newrequest;
    }

}




P Respectons ensemble l'environnement. N'imprimez ce message que si nécessaire. Let's respect the environment together. Only print this message if necessary.

**Comment by sharkker** [comment]
I was also having this problem and managed to make it work through experimentation and the ideas from this post at the AutoTask community forum:

https://community.Autotask.com/forums/p/25383/57004.aspx

For whatever reason, the WSDL schema for the AttachmentInfo object specifies the members but not their datatypes. The API documentation, thankfully, does specify the datatypes, so the way to make CreateAttachment work is to explicitly cast each of the members of the AttachmentInfo object using SoapVar. The Data member, which takes the content of the file, does not need to be pre-encoded because the wsdl does define its datatype as base64encode, so the SOAP call will do that conversion for you. Here is an example that works:

$attachmentInfo	= new ATWS\AutotaskObjects\AttachmentInfo;
$attachmentInfo->id	= new SoapVar( 0, XSD_LONG, "long", "http://www.w3.org/2001/XMLSchema" ); // must be 0 to create new Ticket
$attachmentInfo->FullPath	= new SoapVar( substr( $fileName, 0, 255 ), XSD_STRING, "string", "http://www.w3.org/2001/XMLSchema" );
$attachmentInfo->ParentID	= new SoapVar( intval( $ticketId ), XSD_LONG, "long", "http://www.w3.org/2001/XMLSchema" );
$attachmentInfo->ParentType	= new SoapVar( 4, XSD_LONG, "long", "http://www.w3.org/2001/XMLSchema" ); // Ticket
$attachmentInfo->Publish	= new SoapVar( 1, XSD_LONG, "long", "http://www.w3.org/2001/XMLSchema" ); // All Autotask Users
$attachmentInfo->Title	= new SoapVar( substr( $summary, 0, 255 ), XSD_STRING, "string", "http://www.w3.org/2001/XMLSchema" );
$attachmentInfo->Type	= new SoapVar( "FILE_ATTACHMENT", XSD_STRING, "string", "http://www.w3.org/2001/XMLSchema" ); // Attachment

$attachment	= new ATWS\AutotaskObjects\Attachment;
$attachment->Info	= $attachmentInfo;
$attachment->Data	= $htmlBody; // this is an un-base64-encoded string containing some HTML

$client	= $this->getClient(); // this gets the ATWS\Client using the wsdl and credentials 
$result = $client->CreateAttachment( $attachment );

I hope this helps.

**Comment by reynolek** [comment]
Looks like we got some good examples that will help people out in the future that run into this issue.

Going to close this issue.

**Comment by williams1989** [comment]
anyone can  help me for these above issues in attachment php. Please give me the solution.

**Comment by natchu** [comment]
Hi,
I am currently working using Python, but face the same error as mentioned in the thread. 
`suds.WebFault: Server raised fault: 'System.Web.Services.Protocols.SoapException: Conversion from type 'XmlNode()' to type 'String' is not valid.
                         at autotask.web.services.API.v1_6.ATWS.CreateAttachment(Attachment attachment)
                         at AutotaskApiApplication.API.V1_6.AutotaskApiService_1_6.CreateAttachment(Attachment attachment)'
`
Is there any help or guidelines that can be provided?

**Comment by iw-rylee** [comment]
@sharkker this solution worked perfectly for me - thanks!

Also note that you may not need to encode in base64 - I tried sending an encoded and raw image - only the raw image worked
