### ISSUE TITLE
Alternatives to connecting directly to Autotask?

### ISSUE THREAD

**Issue by timo0060** [opendns/autotask-php#30]
This isn't so much an issue with your library, but rather a question on how to help lower the time spent accessing the autotask API, as it's very slow. My thought was getting all the data from autotask, using this library to help scrap the API, and store a store the data locally as JSON files. Then doing API checks would be a lot quicker in theory, correct? Then at the end of every month/week/day, run the scripts again, and get the updated info. Would this be a possibility? I've noticed that if one entry gets returned from an API call, it can easily be formatted into JSON using the `json_encode()` function in PHP, but multiple entries don't seem to return as nicely. So any idea how I could do that? or any other alternatives to help speed up the data calls?

**Comment by reynolek** [comment]
I'd heavily advise against trying to maintain consistency across 2 data stores (what autotask has vs what you have) -- this can lead to so many issues.

On top of that, Autotask only allows so many queries before you get rate limited pretty heavily.

When you are talking to the API, are you constantly instantiating a new client for every request? That will slow you down massively. There isn't really a way around dealing with their API -- its the most consistent way to get data.

**Comment by timo0060** [comment]
I only have one client being used for most of the requests.

So there's no other way to access the data more efficiently then and we're stuck using AutoTask's slow API?

**Comment by reynolek** [comment]
The unfortunate answer is yes, for any reliable set of data, you are stuck with the API.

**Comment by timo0060** [comment]
Darn you AutoTask! Well thanks for the information, closing issue now.

**Comment by reynolek** [comment]
You could consider using a caching solution with a TTL that is reasonable to your application.

Something like Riak, Redis, or Memcache -- Then if you have a cached result, use that instead of fetching from the API. The only dangerous thing here is that if someone gets out of sync you run the risk of looking at stale data.
