### ISSUE TITLE
Filtering with a Does Not Contain

### ISSUE THREAD

**Issue by timo0060** [opendns/autotask-php#31]
So I know there is no expression for a `doesNotContain` expression, but I can't find something similar. I'm trying to sort through tickets, and I want to seperate tickets that contain or begin with "Alert". I need a list of non-alert tickets, and a list of alert tickets. Which expression would I use? I can easily us the `BeginsWith` or `Contains` for getting the alert ticket, but I'm not sure the inverts of those to get the non-alert tickets.

**Comment by sulfurcode** [comment]
I would use NotLike, here's the XML

<field>Title<expression op="NotLike">%Alert%</expression></field>

**Comment by timo0060** [comment]
Using NotLike will still return tickets with "Alert" in the title. I have written the query as such.

    $ticketAlerts = new ATWS\AutotaskObjects\QueryField('Title');
    $ticketAlerts->addExpression('NotLike', 'Alert');
    $query->addField($ticketAlerts);

**Comment by sulfurcode** [comment]
Try again

    <field>Title<expression op="NotLike">%Alert%</expression></field>

**Comment by sulfurcode** [comment]
Don't forget the wildcard %

**Comment by timo0060** [comment]
Ahhh, thank you. I forgot about those `%` signs. Problem is fixed. Thank you very much
