### ISSUE TITLE
Getting all tickets from multiple Accounts

### ISSUE THREAD

**Issue by timo0060** [opendns/autotask-php#32]
So I need to get all the tickets from multiple accounts. I store all the id's of the accounts I need in a variable called `$accountResults` which is an array. I create the query, then have a for loop to add the queryField for each account id, as well as add an OR condition. But it doesn't seem to work. Below you'll find my code, as well as the XML output.

PHP Code:
    for($i = 0; $i< count($accountResults); $i++){
        $ticket = new ATWS\AutotaskObjects\QueryField('accountid');
        $ticket->addExpression('equals', $accountResults[$i]);

        $query->addField($ticket);
    
        if($i < count($accountResults)){
            $orCondition = new ATWS\AutotaskObjects\QueryCondition('OR');
            $query->addCondition($orCondition);
        }
    }

XML Output:

    ATWS\AutotaskObjects\QueryResponse Object
    (
        [queryResult] => ATWS\AutotaskObjects\ATWSResponse Object
            (
                [EntityResults] => ATWS\AutotaskObjects\ArrayOfEntity Object
                    (
                        [Entity] => 
                    )

                [EntityResultType] => ticket
                [EntityReturnInfoResults] => ATWS\AutotaskObjects\ArrayOfEntityReturnInfo Object
                    (
                        [EntityReturnInfo] => 
                        [Fields] => 
                        [UserDefinedFields] => 
                    )

                [Errors] => ATWS\AutotaskObjects\ArrayOfATWSError Object
                    (
                        [ATWSError] => 
                        [Fields] => 
                        [UserDefinedFields] => 
                    )

                [ReturnCode] => 1
            )

    )

Is there an easier way to do this?

**Comment by reynolek** [comment]
If I remember all of my query logic properly, the following should work:

*NOTE* - There may be some capitalization issues with regard to how autotask does their capitalization of fields. I do not remember exactly how they do various ones (i.e. Id vs ID)

```php
$query = new ATWS\AutotaskObjects\Query('Ticket');
$condition = new ATWS\AutotaskObjects\QueryCondition('OR');

foreach ($accountResults as $account) {
    $field = new ATWS\AutotaskObjects\QueryField('accountid');
    $field->addExpression('Equals', $account->Id);
    $condition->addField($field);
}

$query->addCondition($condition);
print_r($client->query($query));
```

**Comment by timo0060** [comment]
That doesn't seem to work. I modified it a bit as `accountResults` is an array to just store the found Account Id's. So it's values are 1, 2, 123, 456, 765, etc. It still doesn't run, and the `print_r()` still shows a `[ReturnCode]` of 1

**Comment by reynolek** [comment]
Are you certain that `accountid` shouldn't be `AccountID` for the query field? There are so many different annoying capitalization options from autotask that it can be frustrating to figure it out.

Have you tried just querying for 1, then modifying that to query for 2 accounts, before doing this loop?

**Comment by timo0060** [comment]
It would seem that even trying to two breaks it. One works. Also, I've found that the QueryField doesn't seem to be case sensitive. you could write it as acCOuntId and it will still run. 

So the following doesn't work:

````PHP
$query = new ATWS\AutotaskObjects\Query('Ticket');
$condition = new ATWS\AutotaskObjects\QueryCondition('OR');

$ticketOne = new ATWS\AutotaskObjects\QueryField('accountid');
$ticketOne->addExpression('equals', $accountResults[0]);
$ticketTwo = new ATWS\AutotaskObjects\QueryField('accountid');
$ticketTwo->addExpression('equals', $accountResults[1]);

$condition->addField($ticketOne);
$condition->addField($ticketTwo);

$query->addCondition($condition);
````

**Comment by reynolek** [comment]
Can you do a `print($client->__getLastRequest())` after you make the above request? It will print out the XML that was sent to autotask. I would like to see that for debugging.

**Comment by timo0060** [comment]
Here you go:

````XML
<?xml version="1.0" encoding="UTF-8"?>
<SOAP-ENV:Envelope xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/" xmlns:ns1="http://autotask.net/ATWS/v1_5/"><SOAP-ENV:Body><ns1:query><ns1:sXML>&lt;queryxml&gt;&lt;entity&gt;Ticket&lt;/entity&gt;&lt;query&gt;&lt;condition operator="or"&gt;&lt;field&gt;accountid&lt;expression op='equals'&gt;0&lt;/expression&gt;&lt;/field&gt;&lt;field&gt;accountid&lt;expression op='equals'&gt;29684139&lt;/expression&gt;&lt;/field&gt;&lt;/condition&gt;&lt;field&gt;Status&lt;expression op='notequal'&gt;5&lt;/expression&gt;&lt;/field&gt;&lt;field&gt;Status&lt;expression op='notequal'&gt;18&lt;/expression&gt;&lt;/field&gt;&lt;field&gt;Title&lt;expression op='NotLike'&gt;%Alert:%&lt;/expression&gt;&lt;/field&gt;&lt;/query&gt;&lt;/queryxml&gt;</ns1:sXML></ns1:query></SOAP-ENV:Body></SOAP-ENV:Envelope>
````

**Comment by reynolek** [comment]
So fully formatted XML is below -- Can we simplify the query and do just the conditional ORs to see if we can get that working?
```
<SOAP-ENV:Envelope xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/" xmlns:ns1="http://autotask.net/ATWS/v1_5/">
	<SOAP-ENV:Body>
		<ns1:query>
			<ns1:sXML>
				<queryxml>
					<entity>Ticket</entity>
					<query>
						<condition operator="or">
							<field>accountid
								<expression op='equals'>0</expression>
							</field>
							<field>accountid
								<expression op='equals'>29684139</expression>
							</field>
						</condition>
						<field>Status
							<expression op='notequal'>5</expression>
						</field>
						<field>Status
							<expression op='notequal'>18</expression>
						</field>
						<field>Title
							<expression op='NotLike'>%Alert:%</expression>
						</field>
					</query>
				</queryxml>
			</ns1:sXML>
		</ns1:query>
	</SOAP-ENV:Body>
</SOAP-ENV:Envelope>
```

**Comment by timo0060** [comment]
To simplify it, we could remove everything but the condition statements. Even by commenting out the Status and Title field sections, it doesn't pull up any results for tickets.

**Comment by reynolek** [comment]
I am not sure -- the only work I ever did with ORs and ANDs in autotask are detailed in the readme: https://github.com/opendns/autotask-php#really-detailed-queries

**Comment by timo0060** [comment]
I've made a bit of progress. Below will work for calling 2 accounts.

````PHP
$query = new ATWS\AutotaskObjects\Query('Ticket');
$condition = new ATWS\AutotaskObjects\QueryCondition('OR');



$ticketOne = new ATWS\AutotaskObjects\QueryField('accountid');
$ticketOne->addExpression('equals', $accountResults[0]);
$ticketTwo = new ATWS\AutotaskObjects\QueryField('accountid');
$ticketTwo->addExpression('equals', $accountResults[1]);

$query->addField($ticketOne);

$condition->addField($ticketTwo);
$query->addCondition($condition);
````

I added the first account to the query, then added the second to the condition, and then added it. But if I was to put this in the above foreach loop that you provided, and modify it with a bit of logic, it still doesn't work. This is puzzling.

**Comment by timo0060** [comment]
Any other ideas? This is one of the last pieces of the puzzle I need to complete. This and submitting a new ticket, but using your example, it seems pretty straight forward. Below is my current XML for my query, which looks fine to me.

````XML
<queryxml>
    <entity>Ticket</entity>
    <query>
        <condition operator="or">
            <field>accountid
                <expression op='Equals'>0</expression>
            </field>
            <field>accountid
                <expression op='Equals'>29684139</expression>
            </field>
            <field>accountid
                <expression op='Equals'>29692003</expression>
            </field>
            <field>accountid
                <expression op='Equals'>29750814</expression>
            </field>
            <field>accountid
                <expression op='Equals'>29750896</expression>
            </field>
            <field>accountid
                <expression op='Equals'>29750897</expression>
            </field>
            <field>accountid
                <expression op='Equals'>29750909</expression>
            </field>
            <field>accountid
                <expression op='Equals'>29750934</expression>
            </field>
        </condition>
    </query>
</queryxml>
````

**Comment by reynolek** [comment]
To me, that query looks perfectly fine.

**Comment by timo0060** [comment]
I get a return of 0 tickets, but I know that I should get some at least for accoundID = 0, as that on it's own produces tickets.

**Comment by sander271** [comment]
This is the xml query I would use to make a query with OR operators on the account id.

````xml
<queryxml>
  <entity>ticket</entity>
  <query>
    <field>accountid<expression op="equals">0</expression></field>
    <condition operator="OR">
      <field>accountid<expression op="equals">29684139</expression></field>
    </condition>
    <condition operator="OR">
      <field>accountid<expression op="equals">29692003</expression></field>
    </condition>
    <condition operator="OR">
      <field>accountid<expression op="equals">29750814</expression></field>
    </condition>
    <condition operator="OR">
      <field>accountid<expression op="equals">29750896</expression></field>
    </condition>
    <condition operator="OR">
      <field>accountid<expression op="equals">29750897</expression></field>
    </condition>
    <condition operator="OR">
      <field>accountid<expression op="equals">29750909</expression></field>
    </condition>
    <condition operator="OR">
      <field>accountid<expression op="equals">29750934</expression></field>
    </condition>
  </query>
</queryxml>
````

The other thing you will need to keep in mind is if the entity results length is 500 which is the max an API call will return. If this happens you will have to loop the calls and add a greaterthan operator on the ticket id for the last ticket id that was returned (The entity results are in order by id).

for example

````XML
<queryxml>
  <entity>ticket</entity>
  <query>
    <field>accountid<expression op="equals">0</expression></field>
    <condition operator="OR">
      <field>accountid<expression op="equals">29684139</expression></field>
    </condition>
    <condition operator="OR">
      <field>accountid<expression op="equals">29692003</expression></field>
    </condition>
    <condition operator="OR">
      <field>accountid<expression op="equals">29750814</expression></field>
    </condition>
    <condition operator="OR">
      <field>accountid<expression op="equals">29750896</expression></field>
    </condition>
    <condition operator="OR">
      <field>accountid<expression op="equals">29750897</expression></field>
    </condition>
    <condition operator="OR">
      <field>accountid<expression op="equals">29750909</expression></field>
    </condition>
    <condition operator="OR">
      <field>accountid<expression op="equals">29750934</expression></field>
    </condition>
    <field>id<expression op="greaterthan">11142</expression></field>
  </query>
</queryxml>
````

**Comment by timo0060** [comment]
So you'd us a new condition for each Account? Also, I don't think the amount of tickets will reach 500 as I will have other conditions attached, such as last 30 days since Last Activity

**Comment by timo0060** [comment]
Success. Thank you very much. Below is the code I used. Please keep in mind that `$accountResults` was an array that just had Account ID's in it.

````PHP
$query = new ATWS\AutotaskObjects\Query('Ticket');

$loopCount = 1;

foreach($accountResults as $acc){
    
    ${"condition$loopCount"} = new ATWS\AutotaskObjects\QueryCondition('OR');
    $field = new ATWS\AutotaskObjects\QueryField('accountid');
    $field->addExpression('Equals', $acc);
    ${"condition$loopCount"}->addField($field);
    $query->addCondition(${"condition$loopCount"});
    $loopCount++;
    
}
````
