### ISSUE TITLE
Need to fetch subscriptions for a configuration Item

### ISSUE THREAD

**Issue by adilk90** [opendns/autotask-php#34]
I need a way to fetch the subscriptions for a particular Configuration Item using this API.
I have fetched the Configuration Item details to which this subscription belongs using "InstalledProduct" but it only returns me the details of the general tab of Configuration Item. 
Can anyone let me know how to fetch the subscription details as well. Thanks.

**Comment by SirPoot-** [comment]
@adilk90 still need assistance?
