### ISSUE TITLE
Increase Execution time?

### ISSUE THREAD

**Issue by timo0060** [opendns/autotask-php#36]
By default, the Execution time limit is 30 seconds. I however have some queries that loop, and all that looping adds up. Most of the time it takes longer than 30 seconds, so the query times out. Can I crease the time out value to say, 60?

**Comment by reynolek** [comment]
This sounds like a PHP execution time limit, not a query limit -- To test this, try adding [set_time_limit](http://php.net/manual/en/function.set-time-limit.php) with `0` as the seconds to the top of your script and see what happens.

If this solves the issue, you can take a look at your php.ini to increase time limits

**Comment by timo0060** [comment]
That seems to have fixed it, thanks.
