### ISSUE TITLE
Is it possible to make a SQL-join-like with an ATWS\AutotaskObjects\Query ?

### ISSUE THREAD

**Issue by sebsago** [opendns/autotask-php#42]
Hello, first of all, thanks a lot for this client, it really helped me to understand the API AT.

Now here's my issue. For exemple, if i have only the InternalProductID (the id my inc gave it to it) of a product and i need its name and its manufacturerProductName (the id that the manufacturer gave it to it), i just need to make a query in the Product objects.

But i need the InvenritoryLocationID too which is in the InventoryItem Object and this object just contains the ProductId

So my question is do i have to make 2 query, one to get the name/manufacturerProductName/Product ID, then one to get the InventoryItem when i have the Product ID
OR can i make a SQL-join-like in 1 query to get the inventoryLocationId and if i can, how do i do ?

Thanks a lot and sorry if I made any english mistakes, it's not my mother tongue and i have a lot to learn.

**Comment by reynolek** [comment]
From my understanding of the API, there is no way to request joins. You will have to make 2 requests.

**Comment by sebsago** [comment]
okay, that's what I did finally.

thank you ! :)
