### ISSUE TITLE
Adding Contract Service

### ISSUE THREAD

**Issue by B3030095** [opendns/autotask-php#43]
Hey,

I am trying to add a service to a contract, although I cannot find figure out how to get a valid serviceID?

Currently I am getting the error message " Value does not exist for the required field ServiceID. ; on record number [1]." 

Ideally I want to be able to create a contract followed by a service that is assigned to the contract that was just created. Is this possible?

Any help would be amazing, thanks!

**Comment by reynolek** [comment]
Sorry its taken so long to get back to you.

You should be able to create a service and then create a contract utilizing that service id. I honestly have never worked with either of those 2 endpoints so my experience is very limited.

Have you verified that you are sending up the correct types? i.e. string vs int

**Comment by B3030095** [comment]
Thanks for the reply Eric,

How would I retrieve the service or contract ID once it has been created?

Thanks!

**Comment by reynolek** [comment]
It will be part of the object that is returned from your create call, I sugguest doing a print_r($result) and looking -- The field you are looking for will fall under Entity I believe, but its pretty deep in the nested tree and I dont know the nesting off the top of my head.

**Comment by reynolek** [comment]
Oh nevermind I do know it.

It should be `$result->createResult->EntityResults->Entity->id` I believe, i'd still verify with `print_r` though

**Comment by B3030095** [comment]
Thanks a lot Eric that's the perfect solution to the problem!

**Comment by reynolek** [comment]
Happy to help -- Good luck with the API!
