### ISSUE TITLE
added bulkCreate

### ISSUE THREAD

**Issue by Egahras** [opendns/autotask-php#46]
Hey there, still didnt got time to test the bulkUpdate thing... but today evening or tomorrow ill get there.
I just wondered why no bulk Create exists.
I added a function in the Client.php

```
public function bulkCreate(array $objs)
    {
        //$createObjs = array();
        $createObjs;
        foreach ($objs as $obj) {
           if (!$createObjs) $createObjs = new AutotaskObjects\CreateParam($obj);
           else $createObjs->Entities[] = $obj;
        }

        return $this->_call('create', array($createObjs));
    }
```

**Comment by reynolek** [comment]
I've never actually tried to do a bulk create. When we released this it wasn't designed as a feature complete library so I am not surprised there are things that people wish exist but do not.

Feel free to make a pull request and ill review and make comments before merging.
