### ISSUE TITLE
Adding Units to ContractService

### ISSUE THREAD

**Issue by B3030095** [opendns/autotask-php#47]
Hey,

I can successfully add a Service to a Contract using the ContractService class, however there seems to be no way to add units/unit to the Service through the API.

Is this possible?

Thanks!

**Comment by reynolek** [comment]
I have never used contracts or contract service objects (via the API or via the web interface) -- looking over the [Autotask API docs](https://support.netserve365.com/help/Content/Userguides/T_WebServicesAPIv1_5.pdf), I see a ContractServiceUnit which might be what you are looking for?
