### ISSUE TITLE
Updating Service Unit Price (List)

### ISSUE THREAD

**Issue by B3030095** [opendns/autotask-php#50]
Hi,

I am currently using the ContractServiceAdjustment class to update Services with new Units and prices.

Although when I update the unit price and unit cost the Unit Price (List) does not change.

Does anyone know how I can update the Unit Price and Unit Price (List) simultaneously? 

Any help would be great, thanks!

**Comment by aneeshcv** [comment]
@B3030095 Could you please let me know whether you were able to update the prices of a ContractService by any other method? The API docs clear says that **" Changes made to the Contract using the Con- tractServiceAdjustment entity affect only the quantity of units and not price/adjusted price of the Service."**
