### ISSUE TITLE
Date conversion into local time

### ISSUE THREAD

**Issue by christophercygnet** [opendns/autotask-php#51]
I am converting datetimes pulled out of the tickets into my local time (London), using the script below

$TimeZoneNameFrom="EST";
$TimeZoneNameTo="Europe/London";
$DateConverted=date_create($TimeStr, new DateTimeZone($TimeZoneNameFrom))->setTimezone(new DateTimeZone($TimeZoneNameTo))->format("Y-m-d H:i:s"); 

However, the time returned is one hour ahead of the actual time and what it is displayed within the AutoTask Dashboard. Am I wrong in assuming that the datetime is EST?
What I am also finding strange is that when I write back a due date on a ticket, the datetime displayed via the API is correct, but the datetime displayed within the Dashboard is one hour behind. 

I would be grateful for any help...

**Comment by reynolek** [comment]
EST is correct. My guess would be php isn't accounting for British summer time correctly, and is defaulting the London time zone to UTC
