### ISSUE TITLE
LastModifiedDate & LastActivityDate

### ISSUE THREAD

**Issue by christophercygnet** [opendns/autotask-php#53]
Within the API Best Practices, it says to "...formulate queries to return only records that have changed since the last query. You can do this for selected entities using the LastModifiedDate or LastActivityDate fields." 

As it is not possible to return selective fields when querying, is it possible to obtain the LastModifiedDate or LastActivityDate values by any other means without having to return all the fields in an entity?

**Comment by SirPoot-** [comment]
@christophercygnet No. The query returns all the data and you and select/filter what you need.
