### ISSUE TITLE
Querying TimeEntry for a Ticket

### ISSUE THREAD

**Issue by christophercygnet** [opendns/autotask-php#55]
I am trying to extract the various time entries for a ticket. However, nothing is returned, but no errors are returned and the ReturnCode is 1
There are definitely TimeEntries associated with the ticket. 
Am I missing something in the code below? 

`$authOpts = array(
    'login' => $username,
    'password' => $password,
    'trace' => 1, 
);
$wsdl = str_replace('.asmx', '.wsdl', $zoneInfo->getZoneInfoResult->URL);
$client = new ATWS\Client($wsdl, $authOpts);
$query = new ATWS\AutotaskObjects\Query('TimeEntry');
	$queryexpression = new ATWS\AutotaskObjects\QueryField('TicketID');
	$queryexpression->addExpression('Equals', '7946');
	$query->addField($queryexpression);

print_r($query);
$results = $client->query($query);
print_r($results);
$notesArray = $results->queryResult->EntityResults->Entity;
print_r($notesArray);`

If I change the Query to "TicketNote", all the ticket notes for the ticket are shown.
Can anyone please help?

**Comment by jslay88** [comment]
```
$query = new ATWS\AutotaskObjects\Query('TimeEntry');

$timeEntryField = new ATWS\AutotaskObjects\QueryField('TicketID');
$timeEntryField->addExpression('Equals', $ticket->queryResult->EntityResults->Entity->id);
$query->addField($timeEntryField);

$timeEntries = $client->query($query);
```

This works for me.

**Comment by christophercygnet** [comment]
Hi 
Thanks for your code. 
I am assuming that the Entity->id is the id of the ticket, so I add the code to my code which pulls in the info a particular ticket.
Now I know there is Time Entry note to that ticket, as I can see it within AutoTask, unfortunately, when I print out $timeEntires, I get:

`ATWS\AutotaskObjects\QueryResponse Object ( [queryResult] => ATWS\AutotaskObjects\ATWSResponse Object ( [EntityResults] => ATWS\AutotaskObjects\ArrayOfEntity Object ( [Entity] => ) [EntityResultType] => timeentry [EntityReturnInfoResults] => ATWS\AutotaskObjects\ArrayOfEntityReturnInfo Object ( [EntityReturnInfo] => [Fields] => [UserDefinedFields] => ) [Errors] => ATWS\AutotaskObjects\ArrayOfATWSError Object ( [ATWSError] => [Fields] => [UserDefinedFields] => ) [ReturnCode] => 1 ) )`

This is the same for any ticketid I select.

**Comment by jslay88** [comment]
```
$query = new ATWS\AutotaskObjects\Query('Ticket');

$ticketNumberField = new ATWS\AutotaskObjects\QueryField('ticketnumber');
$ticketNumberField->addExpression('Equals', $ticket_number);
$query->addField($ticketNumberField);

$ticket = $client->query($query);
```

Where $ticket_number is
http://puu.sh/rFW4R/f3a5d8c412.png

**Comment by christophercygnet** [comment]
Using your code (similar enough to my one but just in case I've done something stupid in mine), I am still get not getting any Time Entry notes. I know it is finding the correct Ticket as I am able to display this. but the output for $timeEntries is still "empty" (or at least it is returning the same as my above post). 
Any ideas? (thanks for giving us a hand)

**Comment by jslay88** [comment]
Nope. I am out of ideas.

Only thing to keep in mind is notes are separate from time entries. 

Other than that, you should be getting your results just fine. From your previous paste, it shows it is querying and returning without failing ([ReturnCode] => 1)

**Comment by christophercygnet** [comment]
Just wondering, is it possible that the user account that is being used, does not have the correct permissions to access the TimeEntries? 
Do you know if there a way to check what permissions have been given to the account?

**Comment by SirPoot-** [comment]
@christophercygnet is confirmed @jslay88 codes works for me.

You may be on something with the permission. What account are you using to connect to the AT API? Whatever user account that is, log into AT and open a ticket. I just reviewed the security levels for service desk and there was nothing that grants or denies a user access to the time entries. Also, AT will give you a 'free' api user account and dashboard user for that matter (if you do not have them already!)

You can try to connect to the API with an admin account and see if that work. Another debugging tip is to run `print($client->__getLastRequest())` to see what you sent AT.

The Ticket ID is also in the url 'https://ww5.autotask.net/autotask/views/ServiceDesk/ServiceDeskTicket/service_ticket.aspx?ticketID=7946&mode=0' -< Another way to check you have the right ticket.

Hope that helps

**Comment by jslay88** [comment]
You can also call up Autotask and get their feedback. They are pretty helpful.

**Comment by christophercygnet** [comment]
As it turns out, it is actually to do with permissions. If the user account being used to view the Time Entries via the API is anything less than System Admin, that account will not be able to return any information, even though, when the account is used to log in to the dashboard, it is able to.

**Comment by christophercygnet** [comment]
Just to say, Autotask Support have said that they "recommend that any user which is utilising functionality via the Autotask API has the Security Level System Administrator to prevent any errors from occurring due to insufficient security permissions".

**Comment by reynolek** [comment]
As someone who works at a security company, that response from Autotask makes me cringe.

When adding new integrations, whether internal or external, you should look at what permissions they require and only provide those access levels.

Remember that with Autotask, this isn't an "API Only" user account. The account you are using for these integrations is an account that someone could log into your Autotask Dashboard with, and mess around. This leaves a gaping security hole if you purely provide system admin rights.

Be sure to do your best to avoid just blindly giving system admin rights to other people.

**Comment by jslay88** [comment]
Ill say this, my ticketing tool that I built uses the users permission levels, and it can pull time entries just fine. They are definitely not administrators.
