### ISSUE TITLE
Question about internal storage of the hierarchization between Autotask objects / conversation objects

### ISSUE THREAD

**Issue by arminfraude** [opendns/autotask-php#56]
Hi,

I'm working with the Autotask API to read Autotask-Tickets (via PHP) with all assigned objects like TimeEntries or Notes.

My problem is the structure / hierarchization / parent-child relation between the different objects among themselves:

There is the option in Autotask to add a note under another note and not directly "on top level" of the ticket.
Or another example is to add a note to a worklog or a worklog has another worklog as a so called child node.

This hierarchization can be visualized in Autotask's Ticket Detail view via: VIEW --> CONVERSATION.

But how / where are those dependencies saved and especially how can I retrieve them? 
I figured out, that so called "conversation objects" are involved.

So, what am I supposed to do if I for example want to retrieve all "sub notes" of a "main note" or all "sub worklogs" to their "parent worklog" ?

Best Regards

**Comment by sulfurcode** [comment]
Currently that's not possible. There's no field in the API to show a parent ticket note. There's nothing confirmed on the roadmap for now but may come in the future.

**Comment by arminfraude** [comment]
Thank you for the fast reply.

Ok, I understand. 

But are there any other possibilities to retrieve the correct order / hierarchization?
I.e. to read those "conversation objects" which seemingly hold the necessary informations?

**Comment by SirPoot-** [comment]
No - Not at this time.

**Comment by SirPoot-** [comment]
@reynolek close request
