### ISSUE TITLE
FIle attachement in auto task

### ISSUE THREAD

**Issue by BUHARIMOHAMEDISMAIL** [opendns/autotask-php#59]
I need to sent file to auto task account while i'm generating ticket. The file should be in audio, video or image file.
I'm using the below code to create an attachement but it's not working.
$newAttachment = new ATWS\AutotaskObjects\Attachment();
$fileContents = file_get_contents('http://sicsglobal.com/HybridApp/ComicApp/admin/upload/images/timthumb.jpg');
$newAttachment->Data = base64_encode($fileContents);
$aInfo = new ATWS\AutotaskObjects\AttachmentInfo();
$aInfo->ParentID = 29683400;
$aInfo->ParentType = 'Account';
$aInfo->Title = 'error_log';
$aInfo->id = 0;
$newAttachment->Info = $aInfo;  

//alternative

$attachment = new ATWS\AutotaskObjects\CreateAttachment();  //$newAttachment
$attachment->attachment = $newAttachment;
$result = $at->client->CreateAttachment($attachment);

print_r($result);

**Comment by SirPoot-** [comment]
Still an ongoing issue?

**Comment by BUHARIMOHAMEDISMAIL** [comment]
No

**Comment by aditya-did** [comment]
Hello,
Anyone got this working?
Please post the working solution, if any.

Thanks

**Comment by Pinto2019** [comment]
Do you have the working solution?

**Comment by caspahouzer** [comment]
https://github.com/opendns/autotask-php/issues/3#issuecomment-83645705
