### ISSUE TITLE
Function getFieldInfo

### ISSUE THREAD

**Issue by Jorge-TCSP** [opendns/autotask-php#6]
I'm trying to use the function getFieldInfo, but I don't know what to pass as the parameter ($type). I tried sending the field's name, but then I got an "Uncaught SoapFault exception". Are there any examples?

PS:
The examples under "More Detailed Queries" and "Really Detailed Queries" are using `$firstnameField->addExpression('StartsWith', 'S');` but 'StartsWith' doesn't exist, we have to use 'BeginsWith'. 

Thank you

**Comment by tholken** [comment]
How can you do the same thing but grab the Pick-list values say for the Status Types?

**Comment by bigredstick** [comment]
tholken:

$ticketFieldArray = new ATWS\AutotaskObjects\ArrayOfField;
$ticketFieldArray = $client->getFieldInfo('Ticket');
foreach ($ticketFieldArray->GetFieldInfoResult->Field as $ticketFieldInfo) {
        if ($ticketFieldInfo->{"Name"} == "Status") {
                print_r("hi!");
        }
}
