### ISSUE TITLE
How would i get the Task History of a Ticket

### ISSUE THREAD

**Issue by abon22** [opendns/autotask-php#61]
Hi,
Can you help me on how to retrieve the Task History of a Ticket?
Is there a way for example, i would get the TaskID=123 and will retrieve Ticket History?

Sample Image below.
![2017-01-13_8-08-42](https://cloud.githubusercontent.com/assets/17940369/21913568/0b816368-d968-11e6-8d58-6208ba20f2cc.jpg)

I Just want to get the Date for Every Action Taken. 
Hope you can help me with this. Thank you.

**Comment by SirPoot-** [comment]
Unfortunately, that is not possible via the API. Autotask dynamically generates that's data as the page it loaded. This is something I've wanted for a few years and even talked to the Autotask developers about it.

Your best bet is to scrap the webpage. I thought about building that out, but have not pulled the trigger.

**Comment by abon22** [comment]
Really? Are there any way to do it?
