### ISSUE TITLE
Requesting a specific timezone

### ISSUE THREAD

**Issue by sokulski** [opendns/autotask-php#62]
I am querying for tickets based on date to perform reporting.

However, I am noticing that information is returned in the Eastern time zone. The user account that I'm using to make the requests is in Pacific, and I'd like the information to return in that zone.

**Comment by sulfurcode** [comment]
All times are returned in Eastern, you'll need to convert to local with your own code

**Comment by reynolek** [comment]
Exactly what @sulfurcode said -- any conversions need to happen on your end.

**Comment by sokulski** [comment]
Thanks! That's kind of what I figured, but I wanted to be sure there wasn't a flag I was missing.
