### ISSUE TITLE
Having an issue marking an invoice as paid

### ISSUE THREAD

**Issue by domkirby** [opendns/autotask-php#68]
So I've written a function based on things I found in other issues. This is for my billing integration. 

I'm trying to mark an invoice as paid but I keep getting an issue. Here is my function ($AT_Client is the same as $client in the examples, and is defined in an include):

```
    public function MarkATInvoicePaid($invoiceID, $time)
    {
        global $AT_Client;
        $date = date("Y-m-d", $time);
        $query = new \ATWS\AutotaskObjects\Query('Invoice');
        $idField = new \ATWS\AutotaskObjects\QueryField('id');
        $idField->addExpression('Equals', $invoiceID);
        $query->addField($idField);

        $invoiceResponseObject = $AT_Client->query($query);
        $invoiceEntity = $invoiceResponseObject->queryResult->EntityResults->Entity;

        $invoiceEntity->PaidDate = $date;
        $updatedInvoice = $AT_Client->update($invoiceEntity);

        return $updatedInvoice;
    }
```

And this is the response I'm getting:

```
object(stdClass)#48 (1) {
  ["updateResult"]=>
  object(ATWS\AutotaskObjects\ATWSResponse)#49 (5) {
    ["EntityResults"]=>
    object(ATWS\AutotaskObjects\ArrayOfEntity)#50 (1) {
      ["Entity"]=>
      NULL
    }
    ["EntityResultType"]=>
    string(7) "invoice"
    ["EntityReturnInfoResults"]=>
    object(ATWS\AutotaskObjects\ArrayOfEntityReturnInfo)#54 (3) {
      ["EntityReturnInfo"]=>
      NULL
      ["Fields"]=>
      NULL
      ["UserDefinedFields"]=>
      NULL
    }
    ["Errors"]=>
    object(ATWS\AutotaskObjects\ArrayOfATWSError)#51 (3) {
      ["ATWSError"]=>
      array(2) {
        [0]=>
        object(ATWS\AutotaskObjects\ATWSError)#52 (1) {
          ["Message"]=>
          string(53) "Object reference not set to an instance of an object."
        }
        [1]=>
        object(ATWS\AutotaskObjects\ATWSError)#53 (1) {
          ["Message"]=>
          string(44) "Error updating entity for record number [1]."
        }
      }
      ["Fields"]=>
      NULL
      ["UserDefinedFields"]=>
      NULL
    }
    ["ReturnCode"]=>
    int(-1)
  }
}
```

**Comment by reynolek** [comment]
Generally when I see this error, its not because of what you modified, its because of what was returned from autotask.

I vaguely remember dealing with this issue by using `unset` on parts of the object that weren't set.

I recommend doing a `print_r` on the `$invoiceEntity` and look at what each variable is set to. Something might jump out. If it doesn't, feel free to redact any info and post that version here and I can take a look as well.

**Comment by domkirby** [comment]
This is a test invoice so I'm not so worried about redaction. Just want to clarify that you think I should unset the blank entities in this object before pushing update() ?

```
ATWS\AutotaskObjects\Invoice Object ( [AccountID] => 179 [BatchID] => 156 [Comments] => [CreateDateTime] => 2017-05-05T16:16:59 [CreatorResourceID] => 29682885 [DueDate] => 2017-05-20T00:00:00 [FromDate] => 2017-05-05T00:00:00 [InvoiceDateTime] => 2017-05-05T00:00:00 [InvoiceEditorTemplateID] => 103 [InvoiceNumber] => 2351 [InvoiceTotal] => 180.0000 [IsVoided] => [OrderNumber] => [PaidDate] => [PaymentTerm] => 6 [TaxGroup] => [TaxRegionName] => CO [ToDate] => 2017-05-05T00:00:00 [TotalTaxValue] => 0.0000 [VoidedByResourceID] => [VoidedDate] => [WebServiceDate] => [Fields] => [UserDefinedFields] => ATWS\AutotaskObjects\ArrayOfUserDefinedField Object ( [UserDefinedField] => ) [id] => 437 )

```

It's also unclear what sort of date format AT wants and the documentation hasn't been all that helpful. It didn't like epoch, so I tried passing Y-m-d so perhaps that's the issue?

**Comment by reynolek** [comment]
Yeah I would unset the blank entities and see what happens.

I will look at our code for dates as we do something there for ticket creation I think and see what we do.

**Comment by SirPoot-** [comment]
@domkirby Here is the code @reynolek is talking about. I added the additional OR check for a space ( ' ' ) after spending a few hours trying out why I was getting an error on an update. $Response is your $invoiceEntity. This will unset all empty fields and UDF's.

```
foreach($Response as $key => $value) {
  if ($value === '' || $value === null || $value === ' ') {
     unset($Response->$key);
  }
}
```
Your time format should be fine and I am going to assume to read the Invoice page on the Autotask Web Service API documentation. They have a few gotchas regarding the DueDate, TaxGroup and PaidDate (ignores time stamp information and stores the date only ).

Don't forget about the bulkUpdate command in the $client. It is limited to 200 objects in the array so you may need to slice if larger.

**Comment by domkirby** [comment]
ok thanks, I'll try that.

**Comment by domkirby** [comment]
Thanks for the unset code @SirPoot- ! I tried it and I still got the same error. However, I tried just passing time() and got ``Can not convert data to date in field: PaidDate``

Thinking I need to figure out the right format. The documentation doesn't specify one so I'll try using getFieldInfo to get it

**Comment by SirPoot-** [comment]
I have not queried Invoices before. 

It looks like you have the entity now, how about you process the Invoice in the UI and then requery the Invoice to see the PaidDate format? It will probably need to be in the '2017-05-05T00:00:00' format.

**Comment by domkirby** [comment]
Yeah, I went back and queried a paid invoice. That was the format so I just got done trying this code and passing $dateTimeString:

```
        $dateString = date("Y-m-d", $time);
        $timeString = date("H:i:s", 0);
        $dateTimeString = "{$dateString}T{$timeString}";
```
The string looked right when I echoed it but not i'm back to ``Object reference not set to an instance of an object.``

I'm wondering if it doesn't expect the datetime to be an object?

**Comment by SirPoot-** [comment]
According to the AT Web Service Documentation, the PaidDate field has a datatype of datetime.

Now comes the not so fun part, troubleshooting... I would recommend leveraging the PHP SoapClient, __getLastRequest() and __getLastResponse(). I would start with the __getLastRequest() as you will be able to see what you send over to Autotask. There is also $query->asXml() - If you want to debug the XML produced by the Query object.

Hopefully this gets you in the right direction.

**Comment by domkirby** [comment]
Thanks, I'll start chugging through it!

**Comment by domkirby** [comment]
OK, so here is what I've got for lastRequest (after trying update):
```
<?xml version="1.0" encoding="UTF-8"?>
<SOAP-ENV:Envelope xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/" xmlns:ns1="http://autotask.net/ATWS/v1_5/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"><SOAP-ENV:Body><ns1:update><ns1:Entities><ns1:Entity xsi:type="ns1:Invoice"><ns1:id>437</ns1:id><ns1:UserDefinedFields><ns1:UserDefinedField xsi:nil="true"/></ns1:UserDefinedFields><ns1:AccountID>179</ns1:AccountID><ns1:CreatorResourceID>29682885</ns1:CreatorResourceID><ns1:InvoiceDateTime>2017-05-05T00:00:00</ns1:InvoiceDateTime><ns1:CreateDateTime>2017-05-05T16:16:59</ns1:CreateDateTime><ns1:InvoiceNumber>2351</ns1:InvoiceNumber><ns1:InvoiceTotal>180.0000</ns1:InvoiceTotal><ns1:TotalTaxValue>0.0000</ns1:TotalTaxValue><ns1:FromDate>2017-05-05T00:00:00</ns1:FromDate><ns1:ToDate>2017-05-05T00:00:00</ns1:ToDate><ns1:PaymentTerm>6</ns1:PaymentTerm><ns1:IsVoided>false</ns1:IsVoided><ns1:PaidDate>2017-05-09T00:00:00</ns1:PaidDate><ns1:TaxRegionName>CO</ns1:TaxRegionName><ns1:DueDate>2017-05-20T00:00:00</ns1:DueDate><ns1:BatchID>156</ns1:BatchID><ns1:InvoiceEditorTemplateID>103</ns1:InvoiceEditorTemplateID></ns1:Entity></ns1:Entities></ns1:update></SOAP-ENV:Body></SOAP-ENV:Envelope>
```

Unfortunately, I'm not great at reading this but just based off of looking at the string in PaidDate it looks to be the appropriate format. Could it perhaps be because the SOAP envelope contains all of these fields and AT thinks that I'm trying to update them all (many of which are read only)?

**Comment by SirPoot-** [comment]
I always format these to make them easier to read.

```
<?xml version="1.0" encoding="UTF-8"?>
<SOAP-ENV:Envelope xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/" xmlns:ns1="http://autotask.net/ATWS/v1_5/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	<SOAP-ENV:Body>
		<ns1:update>
			<ns1:Entities>
				<ns1:Entity xsi:type="ns1:Invoice">
					<ns1:id>437</ns1:id>
					<ns1:UserDefinedFields>
						<ns1:UserDefinedField xsi:nil="true"/>
					</ns1:UserDefinedFields>
					<ns1:AccountID>179</ns1:AccountID>
					<ns1:CreatorResourceID>29682885</ns1:CreatorResourceID>
					<ns1:InvoiceDateTime>2017-05-05T00:00:00</ns1:InvoiceDateTime>
					<ns1:CreateDateTime>2017-05-05T16:16:59</ns1:CreateDateTime>
					<ns1:InvoiceNumber>2351</ns1:InvoiceNumber>
					<ns1:InvoiceTotal>180.0000</ns1:InvoiceTotal>
					<ns1:TotalTaxValue>0.0000</ns1:TotalTaxValue>
					<ns1:FromDate>2017-05-05T00:00:00</ns1:FromDate>
					<ns1:ToDate>2017-05-05T00:00:00</ns1:ToDate>
					<ns1:PaymentTerm>6</ns1:PaymentTerm>
					<ns1:IsVoided>false</ns1:IsVoided>
					<ns1:PaidDate>2017-05-09T00:00:00</ns1:PaidDate>
					<ns1:TaxRegionName>CO</ns1:TaxRegionName>
					<ns1:DueDate>2017-05-20T00:00:00</ns1:DueDate>
					<ns1:BatchID>156</ns1:BatchID>
					<ns1:InvoiceEditorTemplateID>103</ns1:InvoiceEditorTemplateID>
				</ns1:Entity>
			</ns1:Entities>
		</ns1:update>
	</SOAP-ENV:Body>
</SOAP-ENV:Envelope>
```
Everything looks good expect, no random spaces. The UDF looks a little funny and was the source of a large amount of frustration. For testing, can you set the UserDefinedFields to null, run the unset and process an update?

```
$Response->UserDefinedFields = null;
foreach($Response as $key => $value) {
if ($value === '' || $value === null || $value === ' ' || $value === '          ') {
	unset($Response->$key);
	}
}
```
If you look in the AT documentation, almost every field mentions it is read-only.

**Comment by domkirby** [comment]
AHA, that did the trick! Thanks!

**Comment by SirPoot-** [comment]
@domkirby Great. If you ever have anything weird, check the UDFs!

You can thank @reynolek for all of his prior help with me. I am giving back.

**Comment by reynolek** [comment]
Awesome. Yeah UDFs can be a real PITA.

Glad you got it up and running.
