### ISSUE TITLE
SoapClient not found in autoload.php

### ISSUE THREAD

**Issue by Rikgeffen** [opendns/autotask-php#70]
_**Warning: require_once(C:\xampp\htdocs\CM\AT//SoapClient.php): failed to open stream: No such file or directory in C:\xampp\htdocs\CM\AT\autoload.php on line 8**_

why doest it say this?

**Comment by reynolek** [comment]
Without seeing more code or knowing your directory structure its hard to say.

How did you install the code? If you did it through composer, i'd expect you to be using the `autoload.php` file. If you simply downloaded it and extracted it, you wouldnt have an autoload file.

**Comment by reynolek** [comment]
@Rikgeffen I have released a new version [0.1.10|https://github.com/opendns/autotask-php/releases/tag/0.1.10] that should work for you.

**Comment by Rikgeffen** [comment]
no i am sorry doesnt work for me.

I just install you package and drag it in mij AT folder.
But the pads are wrong so i delete the first word like if:

> require_once __DIR__ . '/autoload.php';
> require_once __DIR__ . '/src/autoload.php';

i didt this to the udf_query_example.php and Autoload.php but if i do it whit the client.php than comes the error : ```
Warning: require_once(C:\xampp\htdocs\CM\AT\SoapClient.php): failed to open stream: No such file or directory in C:\xampp\htdocs\CM\AT\autoload.php on line 9

Fatal error: require_once(): Failed opening required 'C:\xampp\htdocs\CM\AT\SoapClient.php' (include_path='C:\xampp\php\PEAR') in C:\xampp\htdocs\CM\AT\autoload.php on line 9

```
I dint change mach in the file I only taked my Username Password and URL placed in the file and changed the pads in the files i just sad.

**Comment by Rikgeffen** [comment]
ooow and i changed the path of the composer i dindt install composer bescause my other program use composer to. here are some screen shot:
![knipsel](https://cloud.githubusercontent.com/assets/28808368/26752188/8ad41178-484a-11e7-9fd0-909063f6a862.PNG)
![knipsel1](https://cloud.githubusercontent.com/assets/28808368/26752187/8ad39b1c-484a-11e7-9189-b28db9a4e48d.PNG)
![knipsel2](https://cloud.githubusercontent.com/assets/28808368/26752189/8ae4450c-484a-11e7-82a6-01a7eba9629b.PNG)

**Comment by Rikgeffen** [comment]
i am getting closer to the problem  in the client.php you ask `class Client extends \soapClient`
but that doesnt exist.

**Comment by Rikgeffen** [comment]
i fixed it!!! but there are more ERRORS.

You dont have or dindt turn on you soapClient.


here is the sulotion.

**WINDOWS:**
1: Find extension=php_soap.dll in php.ini and remove the semicolon(;)
2: Restart your Server

**LUNIX:**
In ubuntu to install php_soap on PHP7

sudo apt-get install php7.0-soap
sudo systemctl restart apache2.service

For older version of php use below command and restart apache.

apt-get install php-soap

**Comment by reynolek** [comment]
SoapClient is a built in -- never actually seen a php install that didnt have SoapClient enabled.

Glad you got it working, and good luck!
