### ISSUE TITLE
missing separator in autoload.php

### ISSUE THREAD

**Issue by s2894596** [opendns/autotask-php#72]
Line 9 missing $dirSep between implode() and classname.

was:
require_once __DIR__ . $dirSep . implode($dirSep, $namespaceParts) . "{$className}.php";
should be:
require_once __DIR__ . $dirSep . implode($dirSep, $namespaceParts) . $dirSep . "{$className}.php";

Causing error like: "Warning: require_once(/home/ubuntu/workspace/autotask-php/src/AutotaskObjectsTicket.php): failed to open stream: No such file or directory in /home/ubuntu/workspace/autotask-php/src/autoload.php on line 9"

**Comment by reynolek** [comment]
Sorry about that -- I have released 0.1.11 that contains the fix.
