### ISSUE TITLE
Problem updating ticket

### ISSUE THREAD

**Issue by grahambewley** [opendns/autotask-php#73]
Hello, I've seen a few Issues that brush on this, but I was wondering if I could get a definitive answer on how to update a ticket. I am building a Slack app that posts New tickets into a certain channel, with an "Accept" button. When a person clicks that button the ticket is queried again to make sure it hasn't been assigned already, then updates the ticket if it is still New (or if Primary Resource is still blank more specifically). 

I am able to do everything up until the actual ticket update. 

Since I have already done the authorization with my username and password in the first query, I do not have that included in this second query:

    $updatedTicket = $ticket -> queryResult -> EntityResults -> Entity;
    $updatedTicket->id = $ticketID;
    $updatedTicket->AccountID = $ticketAccountID;
    $updatedTicket->DueDateTime = $ticketDueDateTime;
    $updatedTicket->Title = "Updated Ticket Name!";
    $updatedTicket->Status = 3;
    $updatedTicket->Priority = $ticketPriority;
    $updatedTicket->AssignedResourceID = $autotaskID;
    $updatedTicket->UserDefinedFields = null;

		foreach($updatedTicket as $key => $value) {
		    if ($value === '' || $value === null) {
		        unset($updatedTicket->$key);
		    }
		}

     $updateTicketResp = $client->update($updatedTicket);
    print_r($updateTicketResp);
    print($client->__getLastRequest());

Many of the fields are set from the original ticket query. The only reason I have included these is because I believe they are required, even when updating, otherwise I would just leave these lines out. You can see in this example I'm just trying to change the Status and Title for testing purposes. 

Any ideas?

**Comment by SirPoot-** [comment]
Hello @grahambewley,

You are spot on that you need to send the entity back with the update request. I recommend not "resetting" (I do not know that technical term) the fields. Those fields are already set within the entity and you can technically re-setting them. 

Below is code I use to query all the ToDos assigned to account, see if it is not assigned to an active employee, re-assign a ToDo, add the ToDo entity to an array and then I process a bulk update (I did not include the bulk update code). You can use the same structure for your set.

```
$toDoQuery = new ATWS\AutotaskObjects\Query('AccountToDo');
$toDoAcct = new ATWS\AutotaskObjects\QueryField('AccountID');
$toDoAcct ->addExpression('equals', $AccountID);
$toDoQuery->addField($toDoAcct );
$toDoResults = $client->query($toDoQuery)->queryResult->EntityResults->Entity;

foreach ($toDoResults as $toDo) {
	if (!in_array($toDo->AssignedToResourceID, $activeEmployees)) {
		$toDo->AssignedToResourceID = $newResourceID;
		foreach($toDo as $key => $value) {
			if ($value === '' || $value === null || $value === ' ') {
				unset($toDo->$key);
			}
		}
		unset($toDo->UserDefinedFields);
		$toDosReassigned++;
		$toDosToUpdate[] = $todo;	
	}
}
```
I hope this helps out.

**Comment by SirPoot-** [comment]
@grahambewley any update?

**Comment by SirPoot-** [comment]
@reynolek close request
