### ISSUE TITLE
ticket_create_example.php ERROR

### ISSUE THREAD

**Issue by Rikgeffen** [opendns/autotask-php#75]
Hey,

i get this ERROR of the ticket_create_example.php.
where can i find the QueueID?

`ATWS\AutotaskObjects\CreateResponse Object ( [createResult] => ATWS\AutotaskObjects\ATWSResponse Object ( [EntityResults] => ATWS\AutotaskObjects\ArrayOfEntity Object ( [Entity] => ) [EntityResultType] => ticket [EntityReturnInfoResults] => ATWS\AutotaskObjects\ArrayOfEntityReturnInfo Object ( [EntityReturnInfo] => [Fields] => [UserDefinedFields] => ) [Errors] => ATWS\AutotaskObjects\ArrayOfATWSError Object ( [ATWSError] => ATWS\AutotaskObjects\ATWSError Object ( [Message] => Data violation: AssignedResourceID, AssignedResourceRoleID, and QueueID cannot all be empty. Supply a QueueID or both a AssignedResourceID and AssignedResourceRoleID.. ) [Fields] => [UserDefinedFields] => ) [ReturnCode] => -1 ) ) `

**Comment by Rikgeffen** [comment]
Autotask Menu > Admin > Features & Settings > Service Desk (Tickets) > Queues
Click the pencil icon next to one of the Queues to open the Queue Summary window. Copy the URL at the top of the window. It will look something like the URL below. The objectId is the Queue ID.
2017/07/21 08:08:31 Anaz: https://www.autotask.net/autotask/popups/administration/QueueDetails.aspx?objectId=202&type=queue

**Comment by SirPoot-** [comment]
@Rikgeffen Most of the ID's you can see in the URL. If you want to see all values, open an element and look at the page source code. All of the values are there.

**Comment by Rikgeffen** [comment]
@SirPoot- thank you for this tip!
