### ISSUE TITLE
Trying to update Alerts

### ISSUE THREAD

**Issue by jbalter** [opendns/autotask-php#77]
I want to look for a word in the alerts and update it.
I have not worked much with php in a few years.  Could really use some help.

I have the query written to look for "test" and return the results.  I just forgot how to do the update.

thanks.

$authWsdl = 'https://webservices.autotask.net/atservices/1.5/atws.wsdl';
$opts = array('trace' => 1);
$client = new ATWS\Client($authWsdl, $opts);
$zoneInfo = $client->getZoneInfo($username);

//print_r($zoneInfo);

$authOpts = array(
    'login' => $username,
    'password' => $password,
    'trace' => 1,   // Allows us to debug by getting the XML requests sent
);
$wsdl = str_replace('.asmx', '.wsdl', $zoneInfo->getZoneInfoResult->URL);
$client = new ATWS\Client($wsdl, $authOpts);

$query = new ATWS\AutotaskObjects\Query('AccountAlert');

$Alerttextreplace = new ATWS\AutotaskObjects\QueryField('AlertText');
$Alerttextreplace->addExpression('contains', 'test');

$query->addField($Alerttextreplace);
//Stuck here....
//$AccountID->$query($AccountID)
//print_r($AccountID)
//$updatequery = $query->update($query)

// If you want to debug the XML produced by the Query object
// print($query->asXml());

// Print the results of the query
print_r($client->query($query));

**Comment by SirPoot-** [comment]
@jbalter You are on the right track, you need to get the entity, make changes and the push (update) the changes.

I did not test...

```
$ID = 0;
$textToSearch = "Test";
$textReplaceWith = "YAY! IT WORKS";


$accountAlertQuery = new ATWS\AutotaskObjects\Query('AccountAlert');
$accountIDField = new ATWS\AutotaskObjects\QueryField('AccountID');
$accountIDField->addExpression('equals', $ID);
$accountAlertQuery->addField($accountIDField);
$accountAlertTextField = new ATWS\AutotaskObjects\QueryField('AlertText');
$accountAlertTextField->addExpression('contains', $textToSearch);
$accountAlertQuery->addField($accountAlertTextField);

$AccountAlert = $client->query($accountAlertQuery)->queryResult->EntityResults->Entity;
$AccountAlert->AlertText = $textReplaceWith;
$updateResult = $client->update($AccountAlert);		
var_dump($updateResult);
```
Keep in mind, this will SWAP out the alert text with the text you set. They may not be the behavior you are looking for. If not, you will need to save the alerttext and then replace the verbiage. 

Let me know the outcome.

**Comment by jbalter** [comment]
It dies at this line
$updateResult = $client->update($AccountAlert);

Why?

Jon Balter
Chief Operating Officer
Seamless Solutions
Cell (832) 876-3617 Direct (713) 800-6444
www.seamlesssolutions.com<http://www.seamlesssolutions.com/>

**Comment by jbalter** [comment]
Here is my new code.  It works at replacing the text but will not update. WHy?

```
<?php
// This is an example script for querying for a User Defined Field
// on a Configuration Item (otherwise known as an Installed Product)
// This example should work for you if you are an OpenDNS customer
// after you enter your username and password below

require_once __DIR__ . '/src/autoload.php';

// Edit these variables to get this example to work for you
$username = 'username';
$password = 'password';

// End Edit Region

//Login to system
$authWsdl = 'https://webservices.autotask.net/atservices/1.5/atws.wsdl';
$opts = array('trace' => 1);
$client = new ATWS\Client($authWsdl, $opts);
$zoneInfo = $client->getZoneInfo($username);

$authOpts = array(
    'login' => $username,
    'password' => $password,
    'trace' => 1,   // Allows us to debug by getting the XML requests sent
);
$wsdl = str_replace('.asmx', '.wsdl', $zoneInfo->getZoneInfoResult->URL);
$client = new ATWS\Client($wsdl, $authOpts);


//Query the system for accountAlerts
//look for this value
$lookvalue = 'test';
//Replace with this value
$replacevalue = 'YES';
//this is the query
$query = new ATWS\AutotaskObjects\Query('AccountAlert');

$Alerttexttoreplace = new ATWS\AutotaskObjects\QueryField('AlertText');

$Alerttexttoreplace->addExpression('contains', $lookvalue);

$query->addField($Alerttexttoreplace);

//set limited aray
$result = $client->query($query);


$final = $result->queryResult->EntityResults->Entity;

//Replace value in array

foreach ($final as $entity) {
    $entity->queryResult->EntityResults->Entity->AlertText = str_replace("test", "yes", $entity->AlertText);
};

//print_r ($client);


//Update 
$updateResult = $client->update($result);	
var_dump($updateResult);

echo "\r\n";
die(end);
```

**Comment by jbalter** [comment]
it dies at the update line

**Comment by jbalter** [comment]
I am getting this error

Catchable fatal error: Argument 1 passed to ATWS\Client::update() must be an instance of ATWS\AutotaskObjects\Entity, instance of ATWS\AutotaskObjects\QueryResponse given, called in C:\php\Projects\Autotask\PHPfromopenDNS\autotask-php-master\Login_Query2.php on line 61 and defined in C:\php\Projects\Autotask\PHPfromopenDNS\autotask-php-master\src\Client.php on line 162

**Comment by SirPoot-** [comment]
@jbalter $client->update is for a SINGLE entity. There is a bulk update feature $client->bulkUpdate and that has a limit of 200 objects/entity per update.

**Comment by jbalter** [comment]
Bulk update does not work either.

**Comment by SirPoot-** [comment]
@jbalter work with a single entity and then work up to a bulk. You will need to figure out why you are not able to update the alert. For example, I had a bulk update issue on object 198 in my array that had a blank space in a UDF which caused my entire update to fail.

**Comment by jbalter** [comment]
my array is only four and I still can't find an issue.
How would I do just one?

**Comment by SirPoot-** [comment]
Each entity will have its own arrays instead of them. You have two options, single update or bulk update, both are different commands.

**update**
If you are not going to use the bulkupdate, inside your foreach final loop, add an update.
```
foreach ($final as $entity) {
    $entity->AlertText = str_replace("test", "yes", $entity->AlertText);
    $client->update($entity);
};
```

**bulkUpdate**
As long as your bulk update command contains less than 200 objects. If larger, you will need to make the array smaller.

`$client->bulkUpdate($final) ;`

I recommend sticking with the update command. Once you understand how that works, move to the bulkUpdate command.

**Comment by jbalter** [comment]
I get this error. Why?

Fatal error: Uncaught SoapFault exception: [soap:Client] System.Web.Services.Protocols.SoapException: Server was unable to read request. ---> System.InvalidOperationException: There is an error in XML document (2, 218). ---> System.InvalidOperationException: The specified type is abstract: name='Entity', namespace='http://autotask.net/ATWS/v1_5/', at <Entity xmlns='http://autotask.net/ATWS/v1_5/'>.
   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReader1.Read2_Entity(Boolean isNullable, Boolean checkType)
   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReader1.Read183_update()
   at Microsoft.Xml.Serialization.GeneratedAssembly.ArrayOfObjectSerializer32.Deserialize(XmlSerializationReader reader)
   at System.Xml.Serialization.XmlSerializer.Deserialize(XmlReader xmlReader, String encodingStyle, XmlDeserializationEvents events)
   --- End of inner exception stack trace ---
   at System.Xml.Serialization.XmlSerializer.Deserialize(XmlReader xmlReader, String encodingStyle, XmlDeserializa in C:\php\Projects\Autotask\PHPfromopenDNS\autotask-php-master\src\Client.php on line 257

Here is the array

(
    [0] => ATWS\AutotaskObjects\Entity Object
        (
            [Fields] =>
            [UserDefinedFields] => ATWS\AutotaskObjects\ArrayOfUserDefinedField Object
                (
                    [UserDefinedField] =>
                )

            [id] => 35
            [AccountID] => 218
            [AlertTypeID] => 1
            [AlertText] => yes
        )

    [1] => ATWS\AutotaskObjects\Entity Object
        (
            [Fields] =>
            [UserDefinedFields] => ATWS\AutotaskObjects\ArrayOfUserDefinedField Object
                (
                    [UserDefinedField] =>
                )

            [id] => 36
            [AccountID] => 218
            [AlertTypeID] => 2
            [AlertText] => yes2
        )

    [2] => ATWS\AutotaskObjects\Entity Object
        (
            [Fields] =>
            [UserDefinedFields] => ATWS\AutotaskObjects\ArrayOfUserDefinedField Object
                (
                    [UserDefinedField] =>
                )

            [id] => 37
            [AccountID] => 218
            [AlertTypeID] => 3
            [AlertText] => yes3
        )

    [3] => ATWS\AutotaskObjects\Entity Object
        (
            [Fields] =>
            [UserDefinedFields] => ATWS\AutotaskObjects\ArrayOfUserDefinedField Object
                (
                    [UserDefinedField] =>
                )

            [id] => 63
            [AccountID] => 345
            [AlertTypeID] => 1
            [AlertText] => yes
        )

)

Jon Balter
Chief Operating Officer
Seamless Solutions
Cell (832) 876-3617 Direct (713) 800-6444
www.seamlesssolutions.com<http://www.seamlesssolutions.com/>
