### ISSUE TITLE
Zone lookup issues

### ISSUE THREAD

**Issue by tekoyaki** [opendns/autotask-php#78]
I've been having problems with the zone lookup to webservices.autotask.net (500 error).

`Warning (2): SoapClient::SoapClient(https://webservices.autotask.net/atservices/1.5/atws.wsdl) [soapclient.soapclient]: failed to open stream: HTTP request failed! HTTP/1.1 500 Internal Server Error
 [APP/vendors/opendns/autotask-php/src/Client.php, line 131]
Warning (2): SoapClient::SoapClient() [soapclient.soapclient]: I/O warning : failed to load external entity "https://webservices.autotask.net/atservices/1.5/atws.wsdl" [APP/vendors-composer/opendns/autotask-php/src/Client.php, line 131]
SOAP-ERROR: Parsing WSDL: Couldn't load from 'https://webservices.autotask.net/atservices/1.5/atws.wsdl' : failed to load external entity "https://webservices.autotask.net/atservices/1.5/atws.wsdl"`

It seems to work only if I try to access my zone's WSDL first. After the first successful request, I can request any zone WSDL strangely.

My current solution is to store the WSDL locally to get the first zoneinfo.

**Comment by SirPoot-** [comment]
@tekoyaki still having this problem?
