### ISSUE TITLE
Trying to Delete a Ticket

### ISSUE THREAD

**Issue by jessephillipsatws** [opendns/autotask-php#79]
So, I'm trying to delete a ticket from the API.

I'm getting a "This entity does not support the delete action." Which wither means I can;t delete a ticket from the API, or i'm doing something wrong. Probably the latter.

Here is the sample code.

`
    $authOpts = array(
    'login' => $username,
    'password' => $password,
    'trace' => 1,   // Allows us to debug by getting the XML requests sent
	);

	$wsdl = str_replace('.asmx', '.wsdl', $zoneInfo->getZoneInfoResult->URL);
	$client = new ATWS\Client($wsdl, $authOpts);
	
	$query = new ATWS\AutotaskObjects\Query('Ticket');

	$ticketID = new ATWS\AutotaskObjects\QueryField('ticketnumber');
	$ticketID->addExpression('Equals', $obj->TicketNumber);
	
	$query->addField($ticketID);
	$queryResult = $client->query($query);
	
	return $client->delete($queryResult->queryResult->EntityResults->Entity);`

**Comment by SirPoot-** [comment]
@jessephillipsatws You are correct. You cannot delete a ticket via the API. You can read the web services API documentation for more information - https://ww5.autotask.net/help/Content/LinkedDOCUMENTS/WSAPI/T_WebServicesAPIv1_5.pdf

@reynolek close request
