### ISSUE TITLE
Extracting fields from query result

### ISSUE THREAD

**Issue by peterkowalski** [opendns/autotask-php#8]
Hi!

I'm writing a simple PHP code, which will allow me to show some data about particular ticket. I've created a query but I've got no idea how to extract only fields that I want (for example only the field: "Description"). Is there any option to save the query results to an array?

Here is a fragment of my code:
```PHP
require_once('src\autoload.php');

if (isset($_POST['ticket_number'])):
 
$username = 'peter@networkbridge.co.uk';
$password = 'MYPASSWORD';
$authWsdl = 'https://webservices.autotask.net/atservices/1.5/atws.wsdl';
$opts = array('trace' => 1);
$client = new ATWS\Client($authWsdl, $opts);
$zoneInfo = $client->getZoneInfo($username);

$authOpts = array
(
                'login' => $username,
		'password' => $password,
		'trace' => 1,   // Allows us to debug by getting the XML requests sent
);
$wsdl = str_replace('.asmx', '.wsdl', $zoneInfo->getZoneInfoResult->URL);
$client = new ATWS\Client($wsdl, $authOpts);

$query = new ATWS\AutotaskObjects\Query('Ticket');

$ticketNumberField = new ATWS\AutotaskObjects\QueryField('TicketNumber');
$ticketNumberField->addExpression('Equals', $_POST['ticket_number']);

$query->addField($ticketNumberField);

print_r($client->query($query)); // Here I'm printing the result of the query but it's a one big mess.
```

**Comment by reynolek** [comment]
So whats happening here is the `->query($query)` call returns an `ATWS\AutotaskObjects\QueryResponse` Object. Autotask returns a bunch of information in their response that is helpful for error handling, and general knowledge of what is happening on the Autotask side.

Therefore the following code will help get you going:
```php
$result = $client->query($query);

$entities = $result->queryRequest->EntityResults->Entity; // This is an Array of Objects. In your case, \ATWS\AutotaskObjects\Ticket
// I recommend print_r($entities) to see the array, and the objects that are inside it.
foreach ($entities as $entity) {
    print($entity->Description . "\n");
}
```

Since these are objects and not arrays, you have to access their attributes via the `->` operator.

Let me know if you have any more questions. Happy building!

Eric

**Comment by reynolek** [comment]
@peterkowalski did this help you move forward?

**Comment by peterkowalski** [comment]
That was exactly what I was looking for. Thank you very much for your help

 

Cheers!
Peter Kowalski

**Comment by reynolek** [comment]
Glad to help. Good luck!
