### ISSUE TITLE
Time Entry

### ISSUE THREAD

**Issue by jasondecola** [opendns/autotask-php#84]
Is there a way to use this client to create a Time Entry?

**Comment by SirPoot-** [comment]
@jasondecola Yes - Read Autotask's API documentation and you can do everything in there. Essentially, the API gives you (with some limitation) access to everything except the admin module.

**Comment by SirPoot-** [comment]
Close Request.

**Comment by SirPoot-** [comment]
Here is an example of creating a time entry that only contains the required fields.

There are three pages of conditions and requirements for Time Entries in Autotask API documentation. You will need to read  through those, add the additional fields needed, and enter your values for the fields to the sample below to create the timer.

```
$timer = new ATWS\AutotaskObjects\TimeEntry();
$timer->DateWorked = '';
$timer->ResourceID = '';
$timer->RoleID = '';
$timer->Type = '';
$client->create($timer);   
```

**Comment by SirPoot-** [comment]
Request close

**Comment by tuc0w** [comment]
> Here is an example of creating a time entry that only contains the required fields.
> 
> There are three pages of conditions and requirements for Time Entries in Autotask API documentation. You will need to read through those, add the additional fields needed, and enter your values for the fields to the sample below to create the timer.
> 
> ```
> $timer = new ATWS\AutotaskObjects\TimeEntry();
> $timer->DateWorked = '';
> $timer->ResourceID = '';
> $timer->RoleID = '';
> $timer->Type = '';
> $client->create($timer);   
> ```

@SirPoot- I am trying to create a General TimeEntry for Vacation/Sick Times, is there any documentation about where to get the needed types? I've read the official docs but it just tells me "you need a type".

**Comment by SirPoot-** [comment]
To get the fields of an entity the their respected values (if there is a pick-list) execute the getFieldInfo(). The details are under the API calls section, page 313 on version 1.5.15.

In the code below the SOAP client is assigned to $at.

`$at->getFieldInfo('TimeEntry')` yields the following

```
ATWS\AutotaskObjects\Field {#3341
           +DefaultValue: null,
           +Description: null,
           +IsPickList: true,
           +IsQueryable: true,
           +IsReadOnly: true,
           +IsReference: false,
           +IsRequired: false,
           +Label: "TaskTypeLink",
           +Length: 0,
           +Name: "Type",
           +PicklistParentValueField: "",
           +PicklistValues: ATWS\AutotaskObjects\ArrayOfPickListValue {#3340
             +PickListValue: [
               ATWS\AutotaskObjects\PickListValue {#3339
                 +IsActive: true,
                 +IsDefaultValue: false,
                 +IsSystem: true,
                 +Label: "TroubleTicket",
                 +SortOrder: 1,
                 +Value: "1",
                 +parentValue: "",
                 +Fields: null,
                 +UserDefinedFields: null,
               },
               ATWS\AutotaskObjects\PickListValue {#3338
                 +IsActive: true,
                 +IsDefaultValue: false,
                 +IsSystem: true,
                 +Label: "ITServiceRequest",
                 +SortOrder: 2,
                 +Value: "2",
                 +parentValue: "",
                 +Fields: null,
                 +UserDefinedFields: null,
               },
               ATWS\AutotaskObjects\PickListValue {#3337
                 +IsActive: true,
                 +IsDefaultValue: false,
                 +IsSystem: true,
                 +Label: "SalesLead",
                 +SortOrder: 3,
                 +Value: "3",
                 +parentValue: "",
                 +Fields: null,
                 +UserDefinedFields: null,
               },
...
```

**Comment by tuc0w** [comment]
Oh thats awesome, now everything seems to work thank you!

**Comment by SirPoot-** [comment]
@tuc0w Awesome. Glad you were able to get it working.
