### ISSUE TITLE
"Fatal error: Uncaught SoapFault exception" on a basic query

### ISSUE THREAD

**Issue by christophercygnet** [opendns/autotask-php#86]
Any assistance would be grateful...
At sometime over the last few days (everything was working on Friday), all of my API queries to Autotask has stopped working.

I have made sure I have the latest scripts from here and have tried to do a very basic query of Account
`require_once __DIR__ . '/src/autoload.php';
$contactdata = array();

$username = '****';
$password = '****';
$authWsdl = 'https://webservices.autotask.net/atservices/1.5/atws.wsdl';
$opts = array('trace' => 1);
$client = new ATWS\Client($authWsdl, $opts);
$zoneInfo = $client->getZoneInfo($username);

print_r($zoneInfo);

$authOpts = array(
    'login' => $username,
    'password' => $password,
    'trace' => 1,   // Allows us to debug by getting the XML requests sent
);
$wsdl = str_replace('.asmx', '.wsdl', $zoneInfo->getZoneInfoResult->URL);
$client = new ATWS\Client($wsdl, $authOpts);

$query = new ATWS\AutotaskObjects\Query('Account');

$query->addField($package);

// If you want to debug the XML produced by the Query object
 print($query->asXml());

// Print the results of the query
print_r($client->query($query));`

I am getting ZoneInfo returned: 
`stdClass Object ( [getZoneInfoResult] => ATWS\AutotaskObjects\ATWSZoneInfo Object ( [CI] => 805027 [DataBaseType] => [ErrorCode] => 0 [URL] => https://webservices4.autotask.net/ATServices/1.5/atws.asmx [WebUrl] => https://ww4.autotask.net/ ) ) `

but when I make a query, I get: 
`Fatal error: Uncaught SoapFault exception: [WSDL] SOAP-ERROR: Parsing WSDL: Couldn't load from 'https://webservices4.autotask.net/ATServices/1.5/atws.wsdl' : failed to load external entity "https://webservices4.autotask.net/ATServices/1.5/atws.wsdl" in E:\xampp\www\services\secured\autotask\src\Client.php:131 Stack trace: #0 E:\xampp\www\services\secured\autotask\src\Client.php(131): SoapClient->SoapClient('https://webserv...', Array) #1 E:\xampp\www\services\secured\autotask\test2.php(24): ATWS\Client->__construct('https://webserv...', Array) #2 {main} thrown in E:\xampp\www\services\secured\autotask\src\Client.php on line 131`

**Comment by SirPoot-** [comment]
@christophercygnet  you mentioned this was working the other day. This leads me to believe the code works and may be something on your local machine or with the account you are using to connect. Double check in Autotask to make sure the API account has web services enabled or even better, set it to the API user (free as of 2017.1).

Looking at your code, the stack shows an error on line 24. I copied your block of code and line 24 is empty. I do see you are trying to add to the query some values stored to the package variable which is not referenced in this code block.

Here is an example on how to query an account by id after the client is setup.

```
$account = new \ATWS\AutotaskObjects\Query('Account');
$accountidfield = new \ATWS\AutotaskObjects\QueryField('id');
$accountidfield->addExpression('equals',$id);
$account->addField($accountidfield);
$client->query($account);
```

I reviewed my code and it is the same client setup and believe it should work for you.

**Comment by christophercygnet** [comment]
Thanks for the pointer. 
I had assumed that the API account we use had the correct security role... it hadn't, and the password had expired. 
User role has now been changed to the correct one, and the password has been reset, and everything now works again.
Thanks once again.

**Comment by JoshNW** [comment]
Thank you for reporting this one, I spent 3 hours troubleshooting TSL configuration this morning, then found this tread and checked my API User account. It was locked.

**Comment by SirPoot-** [comment]
@JoshNW You are welcome. I **HIGHLY** recommend leveraging the new API User security level. Within  security levels, you can configure "Not required to change password(password does not expire)". As of 2017.1 all API users are free. YAY!

You cannot make this change within the default API User level. Copy the API User level and then you can set that setting (if you desire).

No more API user locked out due to a required password change. 👍
