### ISSUE TITLE
$Account.php how do I call AccountType?

### ISSUE THREAD

**Issue by Rikgeffen** [opendns/autotask-php#87]
I am trying to create a Account but I can't get AccounType to work.
I tryed these options,
$account->AccountType = 1;
$account->AccountType = een;
$account->AccountType = a;
$account->AccountType = Customer;
But al of them don't work... I don't get it.

<select onchange="AccTypeChange();" name="a_type" id="accout_type" style="width: 285px;">
		<option value="1" selected="">Customer</option>
		<option value="2">Lead</option>
		<option value="3">Prospect</option>
		<option value="4">Dead</option>
		<option value="6">Cancelation</option>
		<option value="7">Vendor</option>
		<option value="8">Partner</option>
		</select>

any help would be appreciated

**Comment by SirPoot-** [comment]
AccountType is a short datatype. This is a numeric value and can be found by viewing the page source or you can query the field via the API

![accttypevalues](https://user-images.githubusercontent.com/9685068/35829867-268bb698-0a79-11e8-9a0e-bd1499a160e2.PNG)
