### ISSUE TITLE
Getting an error with ContractRoleCost

### ISSUE THREAD

**Issue by spike5768** [opendns/autotask-php#88]
Hi, I can't make any query with this Entity, can't even show everything. I think it's not a problem with the user's permission because I am using an admin account so I don't know what is the problem.
I just get this 
ATWS\AutotaskObjects\QueryResponse Object ( [queryResult] => ATWS\AutotaskObjects\ATWSResponse Object ( [EntityResults] => ATWS\AutotaskObjects\ArrayOfEntity Object ( [Entity] => ) [EntityResultType] => contractrolecost [EntityReturnInfoResults] => ATWS\AutotaskObjects\ArrayOfEntityReturnInfo Object ( [EntityReturnInfo] => [Fields] => [UserDefinedFields] => ) [Errors] => ATWS\AutotaskObjects\ArrayOfATWSError Object ( [ATWSError] => [Fields] => [UserDefinedFields] => ) [ReturnCode] => 1 ) )

**Comment by SirPoot-** [comment]
Can you post your query code?
