### ISSUE TITLE
How can I update UDFs?

### ISSUE THREAD

**Issue by jmarsden** [opendns/autotask-php#89]
How can I use this API to update UDF fields a "configuration item", which the API apparently calls "InstalledProduct" ?  I wrote code to display and then update some of these fields and the code runs, displays the fields as expected, but the update call for each changed item completes, but does not seem to actually do anything.  No error message as far as I can see.

Is there example code somewhere for updating user defined fields?  Should I post my code here for others to find the bug(s) in?

[ Side note: in Issue #81 https://github.com/opendns/autotask-php/issues/81 , Sir Poot recommends running code that removes all UDFs.  Clearly he had some reason for doing that... but that does not help for actually updating UDFs! ]

Thanks,

Jonathan

**Comment by SirPoot-** [comment]
@jmarsden if you are querying and then updating, you will need to unset the blank and null fields. If you are creating an object or querying an object with no UDFs set, you will need to create an object for the userdefinedfields and then an object for each userdefinedfield.


**Create - Only use if there are no userdefinedfields on the entity**
```
$opps = $this->fetchOppsWithoutUDFSet($udf . ' ');
$AoUDF = new \ATWS\AutotaskObjects\ArrayOfUserDefinedField();
$udfs = [];
$oppTypeUDF = new \ATWS\AutotaskObjects\UserDefinedField();
$oppTypeUDF->Name = 'Opportunity Type';
if ($udf == "T&amp;M")
{
    $oppTypeUDF->Value = "T&M";
}
else
{
    $oppTypeUDF->Value = $udf;
}
$udfs[] = $oppTypeUDF;
$AoUDF->UserDefinedField = $udfs;
foreach($opps as $opp) {
            foreach ($opp as $key => $value)
            {
                if ($value === '' || $value === ' ' || $value === null) {
                    unset($opp->$key);
                }
            }

            $opp->UserDefinedFields = $AoUDF;
            $result = $this->client->update($opp);
}

```
If you are still having problems, post your code and I'll review.
