### ISSUE TITLE
no way to specify ordering

### ISSUE THREAD

**Issue by pauliak1** [opendns/autotask-php#9]
would be useful to be able to specify ordering for the query
e.g. <order direction='descending'>CreateDate</order>

**Comment by reynolek** [comment]
Sorry I thought I had replied to this a long time ago -- I believe this is a limitation of the query language from autotask. I dont see anything about sorting in their API documentation.

**Comment by sulfurcode** [comment]
You can't with the API. It's sorted by id in ascending order, this is mainly so you can get more than 500 objects as you query using the last id from the previous query.

**Comment by reynolek** [comment]
That was my impression as well -- and since this client is a simple wrapper to make the API easier to work with, this request is something that you can make to the API folks at AutoTask.

**Comment by sulfurcode** [comment]
I doubt this will be added to the API. It's simple enough to sort once you have the data and potentially faster to execute
