### ISSUE TITLE
foreign zip code is too long

### ISSUE THREAD

**Issue by Rikgeffen** [opendns/autotask-php#91]
Hello,

I got a problem,
I life in the Netherlands here postal code have 6 digits example "6574HK" but i need to write an account to Autotask that is 11 digits for example "548625 Praha 2" the error is : ( [ATWSError] => ATWS\AutotaskObjects\ATWSError Object ( [Message] => String value exceeds maximum length (field:PostalCode). ; on record number [1]. ) [Fields] => [UserDefinedFields] => ) [ReturnCode] => -1 ) )

How can I fixed this?

**Comment by reynolek** [comment]
That is going to be a question for autotask.

**Comment by Rikgeffen** [comment]
I have spook to Autotask and the said postalcode can't have more then 10 digits.
So I delete my blank spaces
