### ISSUE TITLE
Downloading Attachments / GetAttachment()

### ISSUE THREAD

**Issue by christophercygnet** [opendns/autotask-php#92]
Am I correct in thinking that it is not possible to download attachments associated with tickets?
I have been looking through src, but there is no mention of GetAttachment() but there is for CreateAttachment()

**Comment by SirPoot-** [comment]
@christophercygnet I was able to extent this project to include GetAttachment(). I created a PR. We will have to see if @reynolek merges it. 

It handles downloading (with an example) all attachments from a ticket. You could also modify to download from other objects.

You can add the PR code to your local repo, if you would like.

**Comment by christophercygnet** [comment]
Cheers for that. Extremely grateful for the help. 
Following your example, I am getting the error:

PHP Catchable fatal error:  Argument 1 passed to ATWS\Client::GetAttachment() must be an instance of ATWS\AutotaskObjects\Entity, instance of ATWS\AutotaskObjects\QueryResponse given, called in getattachment.php on line 85 and defined in Client.php on line 210

In my case, line 85 is:
             $result = $client->GetAttachment($attachment);

It is correctly getting the AttachmentInfo, and there is only one file associated with the ticket.
I feel I should be able to work this out...

**Comment by SirPoot-** [comment]
@christophercygnet My mistake. The code base I use has helper functions to format the request and I overlooked it.

In the example, please change line `$attachments = $client->query($attachmentInfo)` to `$attachments = $client->query($attachmentInfo)->queryResult->EntityResults->Entity`. I tested it on my machine it is works.

Below is the entire (fixed) example. I can you please confirm this is working so I can update the pull request?

```
 <?php
require_once __DIR__ . '/autoload.php';

use \ATWS;
use \ATWS\AutotaskObjects;

$username = 'INSERT USERNAME HERE';
$password = 'INSERT PASSWORD HERE';

$postAuthOpts = array(
    'login' => $username,
    'password' => $password,
    'trace' => 1,   // Allows us to debug by getting the XML requests sent
);

$opts = array('trace' => 1);
$authWsdl = 'https://webservices.autotask.net/atservices/1.5/atws.wsdl';
$client = new ATWS\Client($authWsdl, $opts);
$zoneInfo = $client->getZoneInfo($username);

$wsdl = str_replace('.asmx', '.wsdl', $zoneInfo->getZoneInfoResult->URL);
$client = new ATWS\Client($wsdl, $postAuthOpts);

$ticketId = 225975;
$attachmentInfo = new \ATWS\AutotaskObjects\Query('AttachmentInfo');
$parentidQueryfield = new \ATWS\AutotaskObjects\QueryField('parentid');
$parentidQueryfield->addExpression('equals',$ticketId);
$attachmentInfo->addField($parentidQueryfield);
$attachments = $client->query($attachmentInfo)->queryResult->EntityResults->Entity;
$attachments = (count($attachments) > 1 ? $attachments : [$attachments]);
foreach ($attachments as $attachment)
{
    $result = $client->GetAttachment($attachment);
    $save = file_put_contents($result->GetAttachmentResult->Info->FullPath, $result->GetAttachmentResult->Data);
}
```

**Comment by christophercygnet** [comment]
@SirPoot- I can confirm that I have got the updated example working. 
Again, thank you very much for your help
