### ISSUE TITLE
CreatorResourceID Integer Issue

### ISSUE THREAD

**Issue by thekingster** [opendns/autotask-php#94]
Hi Guys 

I am trying to return all tickets logged by a resource using CreatorResourceID. I can get this to work if I say equals 4, which I believe is logged by email, but if I use an actual resource ID it fails, even though if I remove said section of the query it is in the results.

For example:

$package7 = new ATWS\AutotaskObjects\QueryField('CreatorResourceID');
$package7->addExpression('equals', 29682915);

Nothing is returned. However if I rem out the above I get a list of all the tickets that day, one of them being:

2018-02-02T03:57:16.273 | Documentation for ongoing projects | 29682915

I can see this is an integer in the documentation and this number would be a long integer. Is this the issue?

Thanks

Dave

**Comment by thekingster** [comment]
Interestingly if I use NotEquals then it works as expected, it shows all except this one.
It is just when I use Equals

**Comment by SirPoot-** [comment]
@thekingster That's odd. I cannot see your entire query. You're queryfield looks correct.  I was able to return tickets created by the user with the code below. Which makes me think you may have another filter filtering out that data or there was not a ticket created by the resource you are querying.

```
$tickets = new \ATWS\AutotaskObjects\Query('Ticket');
$ticketqueryfield = new \ATWS\AutotaskObjects\QueryField('CreatorResourceID');
$ticketqueryfield->addExpression('equals',30845726);
$tickets->addField($ticketqueryfield);
$result = $this->client->query($tickets);
return($result);
```

**Comment by SirPoot-** [comment]
@thekingster Any update?
