### ISSUE TITLE
Querying AccountName with & character fails with the following error

### ISSUE THREAD

**Issue by Eurymachus** [opendns/autotask-php#96]
https://pastebin.com/9GUYL5Bu

Autotask appears to handle these natively but the API perhaps not?

Is there something I can do when pushing through a query to handle the & character?

Many Thanks,

**Comment by SirPoot-** [comment]
Anytime I reference an ampersand via Autotask's API, I use '&amp;'.

**Comment by Eurymachus** [comment]
Makes perfect sense.

Should be able to parse csv through html_entities for cleanup?

**Comment by SirPoot-** [comment]
@Eurymachus Yes, I tested to confirm. The correct function name is htmlentities. I wanted to save you a little headache / undefined function error message.

http://php.net/manual/en/function.htmlentities.php

**Comment by Eurymachus** [comment]
Using the function http://php.net/manual/en/function.htmlentities.php to parse text from CSV.

**Comment by JoshNW** [comment]
I know this is a closed issue with a known solution, but I wanted to add a note to clarify as this problem recently caused a few headaches. 

The htmlentities() function should only be used when Querying. If it is used when creating or updating entities, you will see &amp in the user interface. 

We have implemented the following logic to handle this problem:

`$QueryableCompanyName = $CompanyName;
if (strpos($CompanyName, '&') !== false) {$QueryableCompanyName = htmlentities($CompanyName);} Else {$QueryableCompanyName = $CompanyName;}`

This switch allows us to process many companies at once without having to modify the Company Search, Create, and Update Statements. 

There is no action needed here, I simply hope it helps someone down the line.
