### ISSUE TITLE
TLS 1.2 Support

### ISSUE THREAD

**Issue by empty-god** [opendns/autotask-php#98]
With the new changes in Autotask's protocols to TLS 1.2, is the library compliant?

**Comment by SirPoot-** [comment]
@empty-god Yes, you will need to make sure your host machine supports TLS 1.2 (If you are running on a Linux machine. Make sure your OpenSSL version is higher that 1.0.1.) If not, you will need to update OpenSSL / cipher suites.

**Comment by reynolek** [comment]
@SirPoot- is correct here -- This client doesn't specify anything in regards to what version is being used, it uses the version that is on the host machine. If you host machine is set up to handle TLS 1.2, then you are all set to go.
