### ISSUE TITLE
Checking Authentication is successful

### ISSUE THREAD

**Issue by MattTak** [opendns/autotask-php#99]
Hi,

Can you let me know how i check to see if the username/password is valid?

I'm currently checking the results of the ZoneInfo call to make sure I have a valid username (Zone @autotaskzone.whatever). This works fine.

However I would expect the first Query to fail with a friendly error if the password is invalid. It appears to just error the entire call and stop the page rendering.

Example code:

``<?php
	
	// Define $username and $password
	$username = USERNAME;
	$password = PASSWORD;

	require_once('at/autoload.php');

	$authWsdl = 'https://webservices.autotask.net/atservices/1.5/atws.wsdl';
	$opts = array('trace' => 1);
	$client = new ATWS\Client($authWsdl, $opts);
	$zoneInfo = $client->getZoneInfo($username);
	
	if($zoneInfo->getZoneInfoResult->ErrorCode == '-1')
	{
		echo "Unable to look up Autotask Zone. Looks like your domain name is wrong?<br>";
	}
	else
	{
		$authOpts = array(
			'login' => $username,
			'password' => $password,
			'trace' => 1,   // Allows us to debug by getting the XML requests sent
		);

		$wsdl = str_replace('.asmx', '.wsdl', $zoneInfo->getZoneInfoResult->URL);
		$client = new ATWS\Client($wsdl, $authOpts);
		
		$webURL = $zoneInfo->getZoneInfoResult->WebUrl;
						
		//Need to query by username to get the logged in resource details
		//First need to remove the domain name 
		$resoucreShortUsername = strstr($username, '@', true);
		
		$query = new ATWS\AutotaskObjects\Query('Resource');
		$aidField = new ATWS\AutotaskObjects\QueryField('UserName');
		$aidField->addExpression('Equals', $resoucreShortUsername);
		$query->addField($aidField);
		
		//this will stop the page rendering if we don't have valid credentials - but how do we check?
		$response = $client->query($query);

		$resourceFirstName = $response->queryResult->EntityResults->Entity->FirstName;
		$resourceLastName = $response->queryResult->EntityResults->Entity->LastName;

		$resourceFullName = $resourceFirstName . " " . $resourceLastName;
		
		if($resourceFullName == "") 
		{
			
			echo "Username or Password is invalid";
		}
		else
		{
			echo "we have authenticated okay";
		}
	}
	
	
?>

**Comment by SirPoot-** [comment]
@MattTak I am using a framework that I catch SOAP-ERROR exception.

If the Autotask domain is correct and the credentials were incorrect, you would get an error on 

`$client = new ATWS\Client($wsdl, $authOpts);`
